# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cordum/agent/v1/heartbeat.proto

require 'google/protobuf'


descriptor_data = "\n\x1f\x63ordum/agent/v1/heartbeat.proto\x12\x0f\x63ordum.agent.v1\"\xc9\x04\n\tHeartbeat\x12\x1b\n\tworker_id\x18\x01 \x01(\tR\x08workerId\x12\x16\n\x06region\x18\x02 \x01(\tR\x06region\x12\x12\n\x04type\x18\x03 \x01(\tR\x04type\x12\x19\n\x08\x63pu_load\x18\x04 \x01(\x02R\x07\x63puLoad\x12\'\n\x0fgpu_utilization\x18\x05 \x01(\x02R\x0egpuUtilization\x12\x1f\n\x0b\x61\x63tive_jobs\x18\x06 \x01(\x05R\nactiveJobs\x12\"\n\x0c\x63\x61pabilities\x18\x07 \x03(\tR\x0c\x63\x61pabilities\x12\x12\n\x04pool\x18\x0b \x01(\tR\x04pool\x12*\n\x11max_parallel_jobs\x18\x0c \x01(\x05R\x0fmaxParallelJobs\x12>\n\x06labels\x18\r \x03(\x0b\x32&.cordum.agent.v1.Heartbeat.LabelsEntryR\x06labels\x12\x1f\n\x0bmemory_load\x18\x0e \x01(\x02R\nmemoryLoad\x12!\n\x0cprogress_pct\x18\x0f \x01(\x05R\x0bprogressPct\x12\x1b\n\tlast_memo\x18\x10 \x01(\tR\x08lastMemo\x12\x1d\n\nauth_token\x18\x12 \x01(\tR\tauthToken\x12\x1d\n\nagent_name\x18\x13 \x01(\tR\tagentName\x1a\x39\n\x0bLabelsEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value:\x02\x38\x01J\x04\x08\x08\x10\tJ\x04\x08\t\x10\nJ\x04\x08\n\x10\x0b\x42\x7f\n\x16io.cordum.cap.agent.v1P\x01Z+github.com/cordum-io/cap/v2/cordum/agent/v1\xaa\x02\x0f\x43ordum.Agent.V1\xca\x02\x0f\x63ordum\\Agent\\V1\xea\x02\x11\x43ordum::Agent::V1b\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Cordum
  module Agent
    module V1
      Heartbeat = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cordum.agent.v1.Heartbeat").msgclass
    end
  end
end
