plugins {
    id 'java-library'
    id 'com.google.protobuf' version '0.9.4'
}

group = 'io.cordum.cap'
version = '2.5.3'

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

repositories {
    mavenCentral()
}

def protobufVersion = '3.25.3'
def grpcVersion = '1.62.2'

dependencies {
    implementation "com.google.protobuf:protobuf-java:${protobufVersion}"
    implementation "com.google.protobuf:protobuf-java-util:${protobufVersion}"
    implementation "io.grpc:grpc-protobuf:${grpcVersion}"
    implementation "io.grpc:grpc-stub:${grpcVersion}"
    implementation 'io.nats:jnats:2.19.1'

    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
}

protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:${protobufVersion}"
    }
    plugins {
        grpc {
            artifact = "io.grpc:protoc-gen-grpc-java:${grpcVersion}"
        }
    }
    generateProtoTasks {
        all()*.plugins {
            grpc {}
        }
    }
}

sourceSets {
    main {
        proto {
            srcDir "${rootProject.projectDir}/../../proto"
        }
    }
}

test {
    useJUnitPlatform()
}
