// source: cordum/agent/v1/alert.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

var cordum_agent_v1_job_pb = require('../../../cordum/agent/v1/job_pb.js');
goog.object.extend(proto, cordum_agent_v1_job_pb);
goog.exportSymbol('proto.cordum.agent.v1.AlertSeverity', null, global);
goog.exportSymbol('proto.cordum.agent.v1.SystemAlert', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cordum.agent.v1.SystemAlert = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.cordum.agent.v1.SystemAlert, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cordum.agent.v1.SystemAlert.displayName = 'proto.cordum.agent.v1.SystemAlert';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cordum.agent.v1.SystemAlert.prototype.toObject = function(opt_includeInstance) {
  return proto.cordum.agent.v1.SystemAlert.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cordum.agent.v1.SystemAlert} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cordum.agent.v1.SystemAlert.toObject = function(includeInstance, msg) {
  var f, obj = {
    level: jspb.Message.getFieldWithDefault(msg, 1, ""),
    message: jspb.Message.getFieldWithDefault(msg, 2, ""),
    component: jspb.Message.getFieldWithDefault(msg, 3, ""),
    code: jspb.Message.getFieldWithDefault(msg, 4, ""),
    severity: jspb.Message.getFieldWithDefault(msg, 5, 0),
    errorCodeEnum: jspb.Message.getFieldWithDefault(msg, 6, 0),
    sourceComponent: jspb.Message.getFieldWithDefault(msg, 7, ""),
    detailsMap: (f = msg.getDetailsMap()) ? f.toObject(includeInstance, undefined) : [],
    traceId: jspb.Message.getFieldWithDefault(msg, 9, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cordum.agent.v1.SystemAlert}
 */
proto.cordum.agent.v1.SystemAlert.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cordum.agent.v1.SystemAlert;
  return proto.cordum.agent.v1.SystemAlert.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cordum.agent.v1.SystemAlert} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cordum.agent.v1.SystemAlert}
 */
proto.cordum.agent.v1.SystemAlert.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setLevel(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setMessage(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setComponent(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setCode(value);
      break;
    case 5:
      var value = /** @type {!proto.cordum.agent.v1.AlertSeverity} */ (reader.readEnum());
      msg.setSeverity(value);
      break;
    case 6:
      var value = /** @type {!proto.cordum.agent.v1.ErrorCode} */ (reader.readEnum());
      msg.setErrorCodeEnum(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setSourceComponent(value);
      break;
    case 8:
      var value = msg.getDetailsMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString, null, "", "");
         });
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setTraceId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cordum.agent.v1.SystemAlert.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cordum.agent.v1.SystemAlert.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cordum.agent.v1.SystemAlert} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cordum.agent.v1.SystemAlert.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getLevel();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getMessage();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getComponent();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getCode();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getSeverity();
  if (f !== 0.0) {
    writer.writeEnum(
      5,
      f
    );
  }
  f = message.getErrorCodeEnum();
  if (f !== 0.0) {
    writer.writeEnum(
      6,
      f
    );
  }
  f = message.getSourceComponent();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getDetailsMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(8, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString);
  }
  f = message.getTraceId();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
};


/**
 * optional string level = 1;
 * @return {string}
 */
proto.cordum.agent.v1.SystemAlert.prototype.getLevel = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.cordum.agent.v1.SystemAlert} returns this
 */
proto.cordum.agent.v1.SystemAlert.prototype.setLevel = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string message = 2;
 * @return {string}
 */
proto.cordum.agent.v1.SystemAlert.prototype.getMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.cordum.agent.v1.SystemAlert} returns this
 */
proto.cordum.agent.v1.SystemAlert.prototype.setMessage = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string component = 3;
 * @return {string}
 */
proto.cordum.agent.v1.SystemAlert.prototype.getComponent = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.cordum.agent.v1.SystemAlert} returns this
 */
proto.cordum.agent.v1.SystemAlert.prototype.setComponent = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string code = 4;
 * @return {string}
 */
proto.cordum.agent.v1.SystemAlert.prototype.getCode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.cordum.agent.v1.SystemAlert} returns this
 */
proto.cordum.agent.v1.SystemAlert.prototype.setCode = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional AlertSeverity severity = 5;
 * @return {!proto.cordum.agent.v1.AlertSeverity}
 */
proto.cordum.agent.v1.SystemAlert.prototype.getSeverity = function() {
  return /** @type {!proto.cordum.agent.v1.AlertSeverity} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {!proto.cordum.agent.v1.AlertSeverity} value
 * @return {!proto.cordum.agent.v1.SystemAlert} returns this
 */
proto.cordum.agent.v1.SystemAlert.prototype.setSeverity = function(value) {
  return jspb.Message.setProto3EnumField(this, 5, value);
};


/**
 * optional ErrorCode error_code_enum = 6;
 * @return {!proto.cordum.agent.v1.ErrorCode}
 */
proto.cordum.agent.v1.SystemAlert.prototype.getErrorCodeEnum = function() {
  return /** @type {!proto.cordum.agent.v1.ErrorCode} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {!proto.cordum.agent.v1.ErrorCode} value
 * @return {!proto.cordum.agent.v1.SystemAlert} returns this
 */
proto.cordum.agent.v1.SystemAlert.prototype.setErrorCodeEnum = function(value) {
  return jspb.Message.setProto3EnumField(this, 6, value);
};


/**
 * optional string source_component = 7;
 * @return {string}
 */
proto.cordum.agent.v1.SystemAlert.prototype.getSourceComponent = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.cordum.agent.v1.SystemAlert} returns this
 */
proto.cordum.agent.v1.SystemAlert.prototype.setSourceComponent = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * map<string, string> details = 8;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.cordum.agent.v1.SystemAlert.prototype.getDetailsMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 8, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.cordum.agent.v1.SystemAlert} returns this
 */
proto.cordum.agent.v1.SystemAlert.prototype.clearDetailsMap = function() {
  this.getDetailsMap().clear();
  return this;};


/**
 * optional string trace_id = 9;
 * @return {string}
 */
proto.cordum.agent.v1.SystemAlert.prototype.getTraceId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/**
 * @param {string} value
 * @return {!proto.cordum.agent.v1.SystemAlert} returns this
 */
proto.cordum.agent.v1.SystemAlert.prototype.setTraceId = function(value) {
  return jspb.Message.setProto3StringField(this, 9, value);
};


/**
 * @enum {number}
 */
proto.cordum.agent.v1.AlertSeverity = {
  ALERT_SEVERITY_UNSPECIFIED: 0,
  ALERT_SEVERITY_INFO: 1,
  ALERT_SEVERITY_WARNING: 2,
  ALERT_SEVERITY_ERROR: 3,
  ALERT_SEVERITY_CRITICAL: 4
};

goog.object.extend(exports, proto.cordum.agent.v1);
