// source: cordum/agent/v1/buspacket.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
var cordum_agent_v1_job_pb = require('../../../cordum/agent/v1/job_pb.js');
goog.object.extend(proto, cordum_agent_v1_job_pb);
var cordum_agent_v1_heartbeat_pb = require('../../../cordum/agent/v1/heartbeat_pb.js');
goog.object.extend(proto, cordum_agent_v1_heartbeat_pb);
var cordum_agent_v1_alert_pb = require('../../../cordum/agent/v1/alert_pb.js');
goog.object.extend(proto, cordum_agent_v1_alert_pb);
var cordum_agent_v1_handshake_pb = require('../../../cordum/agent/v1/handshake_pb.js');
goog.object.extend(proto, cordum_agent_v1_handshake_pb);
goog.exportSymbol('proto.cordum.agent.v1.BusPacket', null, global);
goog.exportSymbol('proto.cordum.agent.v1.BusPacket.PayloadCase', null, global);
goog.exportSymbol('proto.cordum.agent.v1.SignatureMetadata', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cordum.agent.v1.BusPacket = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.cordum.agent.v1.BusPacket.oneofGroups_);
};
goog.inherits(proto.cordum.agent.v1.BusPacket, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cordum.agent.v1.BusPacket.displayName = 'proto.cordum.agent.v1.BusPacket';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cordum.agent.v1.SignatureMetadata = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.cordum.agent.v1.SignatureMetadata, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cordum.agent.v1.SignatureMetadata.displayName = 'proto.cordum.agent.v1.SignatureMetadata';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.cordum.agent.v1.BusPacket.oneofGroups_ = [[10,11,12,13,15,16,17,19,20,21,22]];

/**
 * @enum {number}
 */
proto.cordum.agent.v1.BusPacket.PayloadCase = {
  PAYLOAD_NOT_SET: 0,
  JOB_REQUEST: 10,
  JOB_RESULT: 11,
  HEARTBEAT: 12,
  ALERT: 13,
  JOB_PROGRESS: 15,
  JOB_CANCEL: 16,
  HANDSHAKE: 17,
  WORKER_HANDSHAKE_CHALLENGE_REQUEST: 19,
  WORKER_HANDSHAKE_CHALLENGE: 20,
  WORKER_HANDSHAKE_AUTHENTICATE: 21,
  WORKER_HANDSHAKE_RESULT: 22
};

/**
 * @return {proto.cordum.agent.v1.BusPacket.PayloadCase}
 */
proto.cordum.agent.v1.BusPacket.prototype.getPayloadCase = function() {
  return /** @type {proto.cordum.agent.v1.BusPacket.PayloadCase} */(jspb.Message.computeOneofCase(this, proto.cordum.agent.v1.BusPacket.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cordum.agent.v1.BusPacket.prototype.toObject = function(opt_includeInstance) {
  return proto.cordum.agent.v1.BusPacket.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cordum.agent.v1.BusPacket} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cordum.agent.v1.BusPacket.toObject = function(includeInstance, msg) {
  var f, obj = {
traceId: jspb.Message.getFieldWithDefault(msg, 1, ""),
senderId: jspb.Message.getFieldWithDefault(msg, 2, ""),
createdAt: (f = msg.getCreatedAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
protocolVersion: jspb.Message.getFieldWithDefault(msg, 4, 0),
signatureMetadata: (f = msg.getSignatureMetadata()) && proto.cordum.agent.v1.SignatureMetadata.toObject(includeInstance, f),
identity: (f = msg.getIdentity()) && cordum_agent_v1_job_pb.IdentityBinding.toObject(includeInstance, f),
jobRequest: (f = msg.getJobRequest()) && cordum_agent_v1_job_pb.JobRequest.toObject(includeInstance, f),
jobResult: (f = msg.getJobResult()) && cordum_agent_v1_job_pb.JobResult.toObject(includeInstance, f),
heartbeat: (f = msg.getHeartbeat()) && cordum_agent_v1_heartbeat_pb.Heartbeat.toObject(includeInstance, f),
alert: (f = msg.getAlert()) && cordum_agent_v1_alert_pb.SystemAlert.toObject(includeInstance, f),
jobProgress: (f = msg.getJobProgress()) && cordum_agent_v1_job_pb.JobProgress.toObject(includeInstance, f),
jobCancel: (f = msg.getJobCancel()) && cordum_agent_v1_job_pb.JobCancel.toObject(includeInstance, f),
handshake: (f = msg.getHandshake()) && cordum_agent_v1_handshake_pb.Handshake.toObject(includeInstance, f),
workerHandshakeChallengeRequest: (f = msg.getWorkerHandshakeChallengeRequest()) && cordum_agent_v1_handshake_pb.WorkerHandshakeChallengeRequest.toObject(includeInstance, f),
workerHandshakeChallenge: (f = msg.getWorkerHandshakeChallenge()) && cordum_agent_v1_handshake_pb.WorkerHandshakeChallenge.toObject(includeInstance, f),
workerHandshakeAuthenticate: (f = msg.getWorkerHandshakeAuthenticate()) && cordum_agent_v1_handshake_pb.WorkerHandshakeAuthenticate.toObject(includeInstance, f),
workerHandshakeResult: (f = msg.getWorkerHandshakeResult()) && cordum_agent_v1_handshake_pb.WorkerHandshakeResult.toObject(includeInstance, f),
signature: msg.getSignature_asB64(),
authToken: jspb.Message.getFieldWithDefault(msg, 18, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cordum.agent.v1.BusPacket}
 */
proto.cordum.agent.v1.BusPacket.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cordum.agent.v1.BusPacket;
  return proto.cordum.agent.v1.BusPacket.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cordum.agent.v1.BusPacket} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cordum.agent.v1.BusPacket}
 */
proto.cordum.agent.v1.BusPacket.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setTraceId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setSenderId(value);
      break;
    case 3:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setCreatedAt(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setProtocolVersion(value);
      break;
    case 5:
      var value = new proto.cordum.agent.v1.SignatureMetadata;
      reader.readMessage(value,proto.cordum.agent.v1.SignatureMetadata.deserializeBinaryFromReader);
      msg.setSignatureMetadata(value);
      break;
    case 6:
      var value = new cordum_agent_v1_job_pb.IdentityBinding;
      reader.readMessage(value,cordum_agent_v1_job_pb.IdentityBinding.deserializeBinaryFromReader);
      msg.setIdentity(value);
      break;
    case 10:
      var value = new cordum_agent_v1_job_pb.JobRequest;
      reader.readMessage(value,cordum_agent_v1_job_pb.JobRequest.deserializeBinaryFromReader);
      msg.setJobRequest(value);
      break;
    case 11:
      var value = new cordum_agent_v1_job_pb.JobResult;
      reader.readMessage(value,cordum_agent_v1_job_pb.JobResult.deserializeBinaryFromReader);
      msg.setJobResult(value);
      break;
    case 12:
      var value = new cordum_agent_v1_heartbeat_pb.Heartbeat;
      reader.readMessage(value,cordum_agent_v1_heartbeat_pb.Heartbeat.deserializeBinaryFromReader);
      msg.setHeartbeat(value);
      break;
    case 13:
      var value = new cordum_agent_v1_alert_pb.SystemAlert;
      reader.readMessage(value,cordum_agent_v1_alert_pb.SystemAlert.deserializeBinaryFromReader);
      msg.setAlert(value);
      break;
    case 15:
      var value = new cordum_agent_v1_job_pb.JobProgress;
      reader.readMessage(value,cordum_agent_v1_job_pb.JobProgress.deserializeBinaryFromReader);
      msg.setJobProgress(value);
      break;
    case 16:
      var value = new cordum_agent_v1_job_pb.JobCancel;
      reader.readMessage(value,cordum_agent_v1_job_pb.JobCancel.deserializeBinaryFromReader);
      msg.setJobCancel(value);
      break;
    case 17:
      var value = new cordum_agent_v1_handshake_pb.Handshake;
      reader.readMessage(value,cordum_agent_v1_handshake_pb.Handshake.deserializeBinaryFromReader);
      msg.setHandshake(value);
      break;
    case 19:
      var value = new cordum_agent_v1_handshake_pb.WorkerHandshakeChallengeRequest;
      reader.readMessage(value,cordum_agent_v1_handshake_pb.WorkerHandshakeChallengeRequest.deserializeBinaryFromReader);
      msg.setWorkerHandshakeChallengeRequest(value);
      break;
    case 20:
      var value = new cordum_agent_v1_handshake_pb.WorkerHandshakeChallenge;
      reader.readMessage(value,cordum_agent_v1_handshake_pb.WorkerHandshakeChallenge.deserializeBinaryFromReader);
      msg.setWorkerHandshakeChallenge(value);
      break;
    case 21:
      var value = new cordum_agent_v1_handshake_pb.WorkerHandshakeAuthenticate;
      reader.readMessage(value,cordum_agent_v1_handshake_pb.WorkerHandshakeAuthenticate.deserializeBinaryFromReader);
      msg.setWorkerHandshakeAuthenticate(value);
      break;
    case 22:
      var value = new cordum_agent_v1_handshake_pb.WorkerHandshakeResult;
      reader.readMessage(value,cordum_agent_v1_handshake_pb.WorkerHandshakeResult.deserializeBinaryFromReader);
      msg.setWorkerHandshakeResult(value);
      break;
    case 14:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setSignature(value);
      break;
    case 18:
      var value = /** @type {string} */ (reader.readString());
      msg.setAuthToken(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cordum.agent.v1.BusPacket.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cordum.agent.v1.BusPacket.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cordum.agent.v1.BusPacket} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cordum.agent.v1.BusPacket.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTraceId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getSenderId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getCreatedAt();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getProtocolVersion();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getSignatureMetadata();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.cordum.agent.v1.SignatureMetadata.serializeBinaryToWriter
    );
  }
  f = message.getIdentity();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      cordum_agent_v1_job_pb.IdentityBinding.serializeBinaryToWriter
    );
  }
  f = message.getJobRequest();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      cordum_agent_v1_job_pb.JobRequest.serializeBinaryToWriter
    );
  }
  f = message.getJobResult();
  if (f != null) {
    writer.writeMessage(
      11,
      f,
      cordum_agent_v1_job_pb.JobResult.serializeBinaryToWriter
    );
  }
  f = message.getHeartbeat();
  if (f != null) {
    writer.writeMessage(
      12,
      f,
      cordum_agent_v1_heartbeat_pb.Heartbeat.serializeBinaryToWriter
    );
  }
  f = message.getAlert();
  if (f != null) {
    writer.writeMessage(
      13,
      f,
      cordum_agent_v1_alert_pb.SystemAlert.serializeBinaryToWriter
    );
  }
  f = message.getJobProgress();
  if (f != null) {
    writer.writeMessage(
      15,
      f,
      cordum_agent_v1_job_pb.JobProgress.serializeBinaryToWriter
    );
  }
  f = message.getJobCancel();
  if (f != null) {
    writer.writeMessage(
      16,
      f,
      cordum_agent_v1_job_pb.JobCancel.serializeBinaryToWriter
    );
  }
  f = message.getHandshake();
  if (f != null) {
    writer.writeMessage(
      17,
      f,
      cordum_agent_v1_handshake_pb.Handshake.serializeBinaryToWriter
    );
  }
  f = message.getWorkerHandshakeChallengeRequest();
  if (f != null) {
    writer.writeMessage(
      19,
      f,
      cordum_agent_v1_handshake_pb.WorkerHandshakeChallengeRequest.serializeBinaryToWriter
    );
  }
  f = message.getWorkerHandshakeChallenge();
  if (f != null) {
    writer.writeMessage(
      20,
      f,
      cordum_agent_v1_handshake_pb.WorkerHandshakeChallenge.serializeBinaryToWriter
    );
  }
  f = message.getWorkerHandshakeAuthenticate();
  if (f != null) {
    writer.writeMessage(
      21,
      f,
      cordum_agent_v1_handshake_pb.WorkerHandshakeAuthenticate.serializeBinaryToWriter
    );
  }
  f = message.getWorkerHandshakeResult();
  if (f != null) {
    writer.writeMessage(
      22,
      f,
      cordum_agent_v1_handshake_pb.WorkerHandshakeResult.serializeBinaryToWriter
    );
  }
  f = message.getSignature_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      14,
      f
    );
  }
  f = message.getAuthToken();
  if (f.length > 0) {
    writer.writeString(
      18,
      f
    );
  }
};


/**
 * optional string trace_id = 1;
 * @return {string}
 */
proto.cordum.agent.v1.BusPacket.prototype.getTraceId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.cordum.agent.v1.BusPacket} returns this
 */
proto.cordum.agent.v1.BusPacket.prototype.setTraceId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string sender_id = 2;
 * @return {string}
 */
proto.cordum.agent.v1.BusPacket.prototype.getSenderId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.cordum.agent.v1.BusPacket} returns this
 */
proto.cordum.agent.v1.BusPacket.prototype.setSenderId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional google.protobuf.Timestamp created_at = 3;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.cordum.agent.v1.BusPacket.prototype.getCreatedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 3));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.cordum.agent.v1.BusPacket} returns this
*/
proto.cordum.agent.v1.BusPacket.prototype.setCreatedAt = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cordum.agent.v1.BusPacket} returns this
 */
proto.cordum.agent.v1.BusPacket.prototype.clearCreatedAt = function() {
  return this.setCreatedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cordum.agent.v1.BusPacket.prototype.hasCreatedAt = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional int32 protocol_version = 4;
 * @return {number}
 */
proto.cordum.agent.v1.BusPacket.prototype.getProtocolVersion = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.cordum.agent.v1.BusPacket} returns this
 */
proto.cordum.agent.v1.BusPacket.prototype.setProtocolVersion = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional SignatureMetadata signature_metadata = 5;
 * @return {?proto.cordum.agent.v1.SignatureMetadata}
 */
proto.cordum.agent.v1.BusPacket.prototype.getSignatureMetadata = function() {
  return /** @type{?proto.cordum.agent.v1.SignatureMetadata} */ (
    jspb.Message.getWrapperField(this, proto.cordum.agent.v1.SignatureMetadata, 5));
};


/**
 * @param {?proto.cordum.agent.v1.SignatureMetadata|undefined} value
 * @return {!proto.cordum.agent.v1.BusPacket} returns this
*/
proto.cordum.agent.v1.BusPacket.prototype.setSignatureMetadata = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cordum.agent.v1.BusPacket} returns this
 */
proto.cordum.agent.v1.BusPacket.prototype.clearSignatureMetadata = function() {
  return this.setSignatureMetadata(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cordum.agent.v1.BusPacket.prototype.hasSignatureMetadata = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional IdentityBinding identity = 6;
 * @return {?proto.cordum.agent.v1.IdentityBinding}
 */
proto.cordum.agent.v1.BusPacket.prototype.getIdentity = function() {
  return /** @type{?proto.cordum.agent.v1.IdentityBinding} */ (
    jspb.Message.getWrapperField(this, cordum_agent_v1_job_pb.IdentityBinding, 6));
};


/**
 * @param {?proto.cordum.agent.v1.IdentityBinding|undefined} value
 * @return {!proto.cordum.agent.v1.BusPacket} returns this
*/
proto.cordum.agent.v1.BusPacket.prototype.setIdentity = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cordum.agent.v1.BusPacket} returns this
 */
proto.cordum.agent.v1.BusPacket.prototype.clearIdentity = function() {
  return this.setIdentity(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cordum.agent.v1.BusPacket.prototype.hasIdentity = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional JobRequest job_request = 10;
 * @return {?proto.cordum.agent.v1.JobRequest}
 */
proto.cordum.agent.v1.BusPacket.prototype.getJobRequest = function() {
  return /** @type{?proto.cordum.agent.v1.JobRequest} */ (
    jspb.Message.getWrapperField(this, cordum_agent_v1_job_pb.JobRequest, 10));
};


/**
 * @param {?proto.cordum.agent.v1.JobRequest|undefined} value
 * @return {!proto.cordum.agent.v1.BusPacket} returns this
*/
proto.cordum.agent.v1.BusPacket.prototype.setJobRequest = function(value) {
  return jspb.Message.setOneofWrapperField(this, 10, proto.cordum.agent.v1.BusPacket.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cordum.agent.v1.BusPacket} returns this
 */
proto.cordum.agent.v1.BusPacket.prototype.clearJobRequest = function() {
  return this.setJobRequest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cordum.agent.v1.BusPacket.prototype.hasJobRequest = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional JobResult job_result = 11;
 * @return {?proto.cordum.agent.v1.JobResult}
 */
proto.cordum.agent.v1.BusPacket.prototype.getJobResult = function() {
  return /** @type{?proto.cordum.agent.v1.JobResult} */ (
    jspb.Message.getWrapperField(this, cordum_agent_v1_job_pb.JobResult, 11));
};


/**
 * @param {?proto.cordum.agent.v1.JobResult|undefined} value
 * @return {!proto.cordum.agent.v1.BusPacket} returns this
*/
proto.cordum.agent.v1.BusPacket.prototype.setJobResult = function(value) {
  return jspb.Message.setOneofWrapperField(this, 11, proto.cordum.agent.v1.BusPacket.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cordum.agent.v1.BusPacket} returns this
 */
proto.cordum.agent.v1.BusPacket.prototype.clearJobResult = function() {
  return this.setJobResult(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cordum.agent.v1.BusPacket.prototype.hasJobResult = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * optional Heartbeat heartbeat = 12;
 * @return {?proto.cordum.agent.v1.Heartbeat}
 */
proto.cordum.agent.v1.BusPacket.prototype.getHeartbeat = function() {
  return /** @type{?proto.cordum.agent.v1.Heartbeat} */ (
    jspb.Message.getWrapperField(this, cordum_agent_v1_heartbeat_pb.Heartbeat, 12));
};


/**
 * @param {?proto.cordum.agent.v1.Heartbeat|undefined} value
 * @return {!proto.cordum.agent.v1.BusPacket} returns this
*/
proto.cordum.agent.v1.BusPacket.prototype.setHeartbeat = function(value) {
  return jspb.Message.setOneofWrapperField(this, 12, proto.cordum.agent.v1.BusPacket.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cordum.agent.v1.BusPacket} returns this
 */
proto.cordum.agent.v1.BusPacket.prototype.clearHeartbeat = function() {
  return this.setHeartbeat(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cordum.agent.v1.BusPacket.prototype.hasHeartbeat = function() {
  return jspb.Message.getField(this, 12) != null;
};


/**
 * optional SystemAlert alert = 13;
 * @return {?proto.cordum.agent.v1.SystemAlert}
 */
proto.cordum.agent.v1.BusPacket.prototype.getAlert = function() {
  return /** @type{?proto.cordum.agent.v1.SystemAlert} */ (
    jspb.Message.getWrapperField(this, cordum_agent_v1_alert_pb.SystemAlert, 13));
};


/**
 * @param {?proto.cordum.agent.v1.SystemAlert|undefined} value
 * @return {!proto.cordum.agent.v1.BusPacket} returns this
*/
proto.cordum.agent.v1.BusPacket.prototype.setAlert = function(value) {
  return jspb.Message.setOneofWrapperField(this, 13, proto.cordum.agent.v1.BusPacket.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cordum.agent.v1.BusPacket} returns this
 */
proto.cordum.agent.v1.BusPacket.prototype.clearAlert = function() {
  return this.setAlert(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cordum.agent.v1.BusPacket.prototype.hasAlert = function() {
  return jspb.Message.getField(this, 13) != null;
};


/**
 * optional JobProgress job_progress = 15;
 * @return {?proto.cordum.agent.v1.JobProgress}
 */
proto.cordum.agent.v1.BusPacket.prototype.getJobProgress = function() {
  return /** @type{?proto.cordum.agent.v1.JobProgress} */ (
    jspb.Message.getWrapperField(this, cordum_agent_v1_job_pb.JobProgress, 15));
};


/**
 * @param {?proto.cordum.agent.v1.JobProgress|undefined} value
 * @return {!proto.cordum.agent.v1.BusPacket} returns this
*/
proto.cordum.agent.v1.BusPacket.prototype.setJobProgress = function(value) {
  return jspb.Message.setOneofWrapperField(this, 15, proto.cordum.agent.v1.BusPacket.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cordum.agent.v1.BusPacket} returns this
 */
proto.cordum.agent.v1.BusPacket.prototype.clearJobProgress = function() {
  return this.setJobProgress(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cordum.agent.v1.BusPacket.prototype.hasJobProgress = function() {
  return jspb.Message.getField(this, 15) != null;
};


/**
 * optional JobCancel job_cancel = 16;
 * @return {?proto.cordum.agent.v1.JobCancel}
 */
proto.cordum.agent.v1.BusPacket.prototype.getJobCancel = function() {
  return /** @type{?proto.cordum.agent.v1.JobCancel} */ (
    jspb.Message.getWrapperField(this, cordum_agent_v1_job_pb.JobCancel, 16));
};


/**
 * @param {?proto.cordum.agent.v1.JobCancel|undefined} value
 * @return {!proto.cordum.agent.v1.BusPacket} returns this
*/
proto.cordum.agent.v1.BusPacket.prototype.setJobCancel = function(value) {
  return jspb.Message.setOneofWrapperField(this, 16, proto.cordum.agent.v1.BusPacket.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cordum.agent.v1.BusPacket} returns this
 */
proto.cordum.agent.v1.BusPacket.prototype.clearJobCancel = function() {
  return this.setJobCancel(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cordum.agent.v1.BusPacket.prototype.hasJobCancel = function() {
  return jspb.Message.getField(this, 16) != null;
};


/**
 * optional Handshake handshake = 17;
 * @return {?proto.cordum.agent.v1.Handshake}
 */
proto.cordum.agent.v1.BusPacket.prototype.getHandshake = function() {
  return /** @type{?proto.cordum.agent.v1.Handshake} */ (
    jspb.Message.getWrapperField(this, cordum_agent_v1_handshake_pb.Handshake, 17));
};


/**
 * @param {?proto.cordum.agent.v1.Handshake|undefined} value
 * @return {!proto.cordum.agent.v1.BusPacket} returns this
*/
proto.cordum.agent.v1.BusPacket.prototype.setHandshake = function(value) {
  return jspb.Message.setOneofWrapperField(this, 17, proto.cordum.agent.v1.BusPacket.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cordum.agent.v1.BusPacket} returns this
 */
proto.cordum.agent.v1.BusPacket.prototype.clearHandshake = function() {
  return this.setHandshake(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cordum.agent.v1.BusPacket.prototype.hasHandshake = function() {
  return jspb.Message.getField(this, 17) != null;
};


/**
 * optional WorkerHandshakeChallengeRequest worker_handshake_challenge_request = 19;
 * @return {?proto.cordum.agent.v1.WorkerHandshakeChallengeRequest}
 */
proto.cordum.agent.v1.BusPacket.prototype.getWorkerHandshakeChallengeRequest = function() {
  return /** @type{?proto.cordum.agent.v1.WorkerHandshakeChallengeRequest} */ (
    jspb.Message.getWrapperField(this, cordum_agent_v1_handshake_pb.WorkerHandshakeChallengeRequest, 19));
};


/**
 * @param {?proto.cordum.agent.v1.WorkerHandshakeChallengeRequest|undefined} value
 * @return {!proto.cordum.agent.v1.BusPacket} returns this
*/
proto.cordum.agent.v1.BusPacket.prototype.setWorkerHandshakeChallengeRequest = function(value) {
  return jspb.Message.setOneofWrapperField(this, 19, proto.cordum.agent.v1.BusPacket.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cordum.agent.v1.BusPacket} returns this
 */
proto.cordum.agent.v1.BusPacket.prototype.clearWorkerHandshakeChallengeRequest = function() {
  return this.setWorkerHandshakeChallengeRequest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cordum.agent.v1.BusPacket.prototype.hasWorkerHandshakeChallengeRequest = function() {
  return jspb.Message.getField(this, 19) != null;
};


/**
 * optional WorkerHandshakeChallenge worker_handshake_challenge = 20;
 * @return {?proto.cordum.agent.v1.WorkerHandshakeChallenge}
 */
proto.cordum.agent.v1.BusPacket.prototype.getWorkerHandshakeChallenge = function() {
  return /** @type{?proto.cordum.agent.v1.WorkerHandshakeChallenge} */ (
    jspb.Message.getWrapperField(this, cordum_agent_v1_handshake_pb.WorkerHandshakeChallenge, 20));
};


/**
 * @param {?proto.cordum.agent.v1.WorkerHandshakeChallenge|undefined} value
 * @return {!proto.cordum.agent.v1.BusPacket} returns this
*/
proto.cordum.agent.v1.BusPacket.prototype.setWorkerHandshakeChallenge = function(value) {
  return jspb.Message.setOneofWrapperField(this, 20, proto.cordum.agent.v1.BusPacket.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cordum.agent.v1.BusPacket} returns this
 */
proto.cordum.agent.v1.BusPacket.prototype.clearWorkerHandshakeChallenge = function() {
  return this.setWorkerHandshakeChallenge(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cordum.agent.v1.BusPacket.prototype.hasWorkerHandshakeChallenge = function() {
  return jspb.Message.getField(this, 20) != null;
};


/**
 * optional WorkerHandshakeAuthenticate worker_handshake_authenticate = 21;
 * @return {?proto.cordum.agent.v1.WorkerHandshakeAuthenticate}
 */
proto.cordum.agent.v1.BusPacket.prototype.getWorkerHandshakeAuthenticate = function() {
  return /** @type{?proto.cordum.agent.v1.WorkerHandshakeAuthenticate} */ (
    jspb.Message.getWrapperField(this, cordum_agent_v1_handshake_pb.WorkerHandshakeAuthenticate, 21));
};


/**
 * @param {?proto.cordum.agent.v1.WorkerHandshakeAuthenticate|undefined} value
 * @return {!proto.cordum.agent.v1.BusPacket} returns this
*/
proto.cordum.agent.v1.BusPacket.prototype.setWorkerHandshakeAuthenticate = function(value) {
  return jspb.Message.setOneofWrapperField(this, 21, proto.cordum.agent.v1.BusPacket.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cordum.agent.v1.BusPacket} returns this
 */
proto.cordum.agent.v1.BusPacket.prototype.clearWorkerHandshakeAuthenticate = function() {
  return this.setWorkerHandshakeAuthenticate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cordum.agent.v1.BusPacket.prototype.hasWorkerHandshakeAuthenticate = function() {
  return jspb.Message.getField(this, 21) != null;
};


/**
 * optional WorkerHandshakeResult worker_handshake_result = 22;
 * @return {?proto.cordum.agent.v1.WorkerHandshakeResult}
 */
proto.cordum.agent.v1.BusPacket.prototype.getWorkerHandshakeResult = function() {
  return /** @type{?proto.cordum.agent.v1.WorkerHandshakeResult} */ (
    jspb.Message.getWrapperField(this, cordum_agent_v1_handshake_pb.WorkerHandshakeResult, 22));
};


/**
 * @param {?proto.cordum.agent.v1.WorkerHandshakeResult|undefined} value
 * @return {!proto.cordum.agent.v1.BusPacket} returns this
*/
proto.cordum.agent.v1.BusPacket.prototype.setWorkerHandshakeResult = function(value) {
  return jspb.Message.setOneofWrapperField(this, 22, proto.cordum.agent.v1.BusPacket.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cordum.agent.v1.BusPacket} returns this
 */
proto.cordum.agent.v1.BusPacket.prototype.clearWorkerHandshakeResult = function() {
  return this.setWorkerHandshakeResult(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cordum.agent.v1.BusPacket.prototype.hasWorkerHandshakeResult = function() {
  return jspb.Message.getField(this, 22) != null;
};


/**
 * optional bytes signature = 14;
 * @return {!(string|Uint8Array)}
 */
proto.cordum.agent.v1.BusPacket.prototype.getSignature = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 14, ""));
};


/**
 * optional bytes signature = 14;
 * This is a type-conversion wrapper around `getSignature()`
 * @return {string}
 */
proto.cordum.agent.v1.BusPacket.prototype.getSignature_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getSignature()));
};


/**
 * optional bytes signature = 14;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getSignature()`
 * @return {!Uint8Array}
 */
proto.cordum.agent.v1.BusPacket.prototype.getSignature_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getSignature()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.cordum.agent.v1.BusPacket} returns this
 */
proto.cordum.agent.v1.BusPacket.prototype.setSignature = function(value) {
  return jspb.Message.setProto3BytesField(this, 14, value);
};


/**
 * optional string auth_token = 18;
 * @return {string}
 */
proto.cordum.agent.v1.BusPacket.prototype.getAuthToken = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 18, ""));
};


/**
 * @param {string} value
 * @return {!proto.cordum.agent.v1.BusPacket} returns this
 */
proto.cordum.agent.v1.BusPacket.prototype.setAuthToken = function(value) {
  return jspb.Message.setProto3StringField(this, 18, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cordum.agent.v1.SignatureMetadata.prototype.toObject = function(opt_includeInstance) {
  return proto.cordum.agent.v1.SignatureMetadata.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cordum.agent.v1.SignatureMetadata} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cordum.agent.v1.SignatureMetadata.toObject = function(includeInstance, msg) {
  var f, obj = {
profileVersion: jspb.Message.getFieldWithDefault(msg, 1, ""),
algorithm: jspb.Message.getFieldWithDefault(msg, 2, ""),
messageId: msg.getMessageId_asB64(),
audience: jspb.Message.getFieldWithDefault(msg, 4, ""),
expiresAt: (f = msg.getExpiresAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
keyId: jspb.Message.getFieldWithDefault(msg, 6, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cordum.agent.v1.SignatureMetadata}
 */
proto.cordum.agent.v1.SignatureMetadata.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cordum.agent.v1.SignatureMetadata;
  return proto.cordum.agent.v1.SignatureMetadata.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cordum.agent.v1.SignatureMetadata} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cordum.agent.v1.SignatureMetadata}
 */
proto.cordum.agent.v1.SignatureMetadata.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setProfileVersion(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setAlgorithm(value);
      break;
    case 3:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setMessageId(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setAudience(value);
      break;
    case 5:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setExpiresAt(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setKeyId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cordum.agent.v1.SignatureMetadata.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cordum.agent.v1.SignatureMetadata.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cordum.agent.v1.SignatureMetadata} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cordum.agent.v1.SignatureMetadata.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getProfileVersion();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getAlgorithm();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getMessageId_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      3,
      f
    );
  }
  f = message.getAudience();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getExpiresAt();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getKeyId();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
};


/**
 * optional string profile_version = 1;
 * @return {string}
 */
proto.cordum.agent.v1.SignatureMetadata.prototype.getProfileVersion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.cordum.agent.v1.SignatureMetadata} returns this
 */
proto.cordum.agent.v1.SignatureMetadata.prototype.setProfileVersion = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string algorithm = 2;
 * @return {string}
 */
proto.cordum.agent.v1.SignatureMetadata.prototype.getAlgorithm = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.cordum.agent.v1.SignatureMetadata} returns this
 */
proto.cordum.agent.v1.SignatureMetadata.prototype.setAlgorithm = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional bytes message_id = 3;
 * @return {!(string|Uint8Array)}
 */
proto.cordum.agent.v1.SignatureMetadata.prototype.getMessageId = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * optional bytes message_id = 3;
 * This is a type-conversion wrapper around `getMessageId()`
 * @return {string}
 */
proto.cordum.agent.v1.SignatureMetadata.prototype.getMessageId_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getMessageId()));
};


/**
 * optional bytes message_id = 3;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getMessageId()`
 * @return {!Uint8Array}
 */
proto.cordum.agent.v1.SignatureMetadata.prototype.getMessageId_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getMessageId()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.cordum.agent.v1.SignatureMetadata} returns this
 */
proto.cordum.agent.v1.SignatureMetadata.prototype.setMessageId = function(value) {
  return jspb.Message.setProto3BytesField(this, 3, value);
};


/**
 * optional string audience = 4;
 * @return {string}
 */
proto.cordum.agent.v1.SignatureMetadata.prototype.getAudience = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.cordum.agent.v1.SignatureMetadata} returns this
 */
proto.cordum.agent.v1.SignatureMetadata.prototype.setAudience = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional google.protobuf.Timestamp expires_at = 5;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.cordum.agent.v1.SignatureMetadata.prototype.getExpiresAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 5));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.cordum.agent.v1.SignatureMetadata} returns this
*/
proto.cordum.agent.v1.SignatureMetadata.prototype.setExpiresAt = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cordum.agent.v1.SignatureMetadata} returns this
 */
proto.cordum.agent.v1.SignatureMetadata.prototype.clearExpiresAt = function() {
  return this.setExpiresAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cordum.agent.v1.SignatureMetadata.prototype.hasExpiresAt = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional string key_id = 6;
 * @return {string}
 */
proto.cordum.agent.v1.SignatureMetadata.prototype.getKeyId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.cordum.agent.v1.SignatureMetadata} returns this
 */
proto.cordum.agent.v1.SignatureMetadata.prototype.setKeyId = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


goog.object.extend(exports, proto.cordum.agent.v1);
