// source: cordum/agent/v1/handshake.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
goog.exportSymbol('proto.cordum.agent.v1.ComponentRole', null, global);
goog.exportSymbol('proto.cordum.agent.v1.Handshake', null, global);
goog.exportSymbol('proto.cordum.agent.v1.WorkerHandshakeAuthenticate', null, global);
goog.exportSymbol('proto.cordum.agent.v1.WorkerHandshakeChallenge', null, global);
goog.exportSymbol('proto.cordum.agent.v1.WorkerHandshakeChallengeRequest', null, global);
goog.exportSymbol('proto.cordum.agent.v1.WorkerHandshakeProofAlgorithm', null, global);
goog.exportSymbol('proto.cordum.agent.v1.WorkerHandshakePurpose', null, global);
goog.exportSymbol('proto.cordum.agent.v1.WorkerHandshakeRejectionReason', null, global);
goog.exportSymbol('proto.cordum.agent.v1.WorkerHandshakeResult', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cordum.agent.v1.Handshake = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.cordum.agent.v1.Handshake.repeatedFields_, null);
};
goog.inherits(proto.cordum.agent.v1.Handshake, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cordum.agent.v1.Handshake.displayName = 'proto.cordum.agent.v1.Handshake';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cordum.agent.v1.WorkerHandshakeChallengeRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.cordum.agent.v1.WorkerHandshakeChallengeRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cordum.agent.v1.WorkerHandshakeChallengeRequest.displayName = 'proto.cordum.agent.v1.WorkerHandshakeChallengeRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cordum.agent.v1.WorkerHandshakeChallenge = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.cordum.agent.v1.WorkerHandshakeChallenge, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cordum.agent.v1.WorkerHandshakeChallenge.displayName = 'proto.cordum.agent.v1.WorkerHandshakeChallenge';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cordum.agent.v1.WorkerHandshakeAuthenticate = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.cordum.agent.v1.WorkerHandshakeAuthenticate, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cordum.agent.v1.WorkerHandshakeAuthenticate.displayName = 'proto.cordum.agent.v1.WorkerHandshakeAuthenticate';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cordum.agent.v1.WorkerHandshakeResult = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.cordum.agent.v1.WorkerHandshakeResult, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cordum.agent.v1.WorkerHandshakeResult.displayName = 'proto.cordum.agent.v1.WorkerHandshakeResult';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.cordum.agent.v1.Handshake.repeatedFields_ = [3,6];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cordum.agent.v1.Handshake.prototype.toObject = function(opt_includeInstance) {
  return proto.cordum.agent.v1.Handshake.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cordum.agent.v1.Handshake} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cordum.agent.v1.Handshake.toObject = function(includeInstance, msg) {
  var f, obj = {
componentId: jspb.Message.getFieldWithDefault(msg, 1, ""),
role: jspb.Message.getFieldWithDefault(msg, 2, 0),
supportedVersionsList: (f = jspb.Message.getRepeatedField(msg, 3)) == null ? undefined : f,
capabilitiesMap: (f = msg.getCapabilitiesMap()) ? f.toObject(includeInstance, undefined) : [],
sdkVersion: jspb.Message.getFieldWithDefault(msg, 5, ""),
readyTopicsList: (f = jspb.Message.getRepeatedField(msg, 6)) == null ? undefined : f,
agentName: jspb.Message.getFieldWithDefault(msg, 7, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cordum.agent.v1.Handshake}
 */
proto.cordum.agent.v1.Handshake.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cordum.agent.v1.Handshake;
  return proto.cordum.agent.v1.Handshake.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cordum.agent.v1.Handshake} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cordum.agent.v1.Handshake}
 */
proto.cordum.agent.v1.Handshake.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setComponentId(value);
      break;
    case 2:
      var value = /** @type {!proto.cordum.agent.v1.ComponentRole} */ (reader.readEnum());
      msg.setRole(value);
      break;
    case 3:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedInt32() : [reader.readInt32()]);
      for (var i = 0; i < values.length; i++) {
        msg.addSupportedVersions(values[i]);
      }
      break;
    case 4:
      var value = msg.getCapabilitiesMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readBool, null, "", false);
         });
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setSdkVersion(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.addReadyTopics(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setAgentName(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cordum.agent.v1.Handshake.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cordum.agent.v1.Handshake.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cordum.agent.v1.Handshake} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cordum.agent.v1.Handshake.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getComponentId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getRole();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getSupportedVersionsList();
  if (f.length > 0) {
    writer.writePackedInt32(
      3,
      f
    );
  }
  f = message.getCapabilitiesMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(4, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeBool);
  }
  f = message.getSdkVersion();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getReadyTopicsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      6,
      f
    );
  }
  f = message.getAgentName();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
};


/**
 * optional string component_id = 1;
 * @return {string}
 */
proto.cordum.agent.v1.Handshake.prototype.getComponentId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.cordum.agent.v1.Handshake} returns this
 */
proto.cordum.agent.v1.Handshake.prototype.setComponentId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional ComponentRole role = 2;
 * @return {!proto.cordum.agent.v1.ComponentRole}
 */
proto.cordum.agent.v1.Handshake.prototype.getRole = function() {
  return /** @type {!proto.cordum.agent.v1.ComponentRole} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.cordum.agent.v1.ComponentRole} value
 * @return {!proto.cordum.agent.v1.Handshake} returns this
 */
proto.cordum.agent.v1.Handshake.prototype.setRole = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * repeated int32 supported_versions = 3;
 * @return {!Array<number>}
 */
proto.cordum.agent.v1.Handshake.prototype.getSupportedVersionsList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 3));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.cordum.agent.v1.Handshake} returns this
 */
proto.cordum.agent.v1.Handshake.prototype.setSupportedVersionsList = function(value) {
  return jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.cordum.agent.v1.Handshake} returns this
 */
proto.cordum.agent.v1.Handshake.prototype.addSupportedVersions = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.cordum.agent.v1.Handshake} returns this
 */
proto.cordum.agent.v1.Handshake.prototype.clearSupportedVersionsList = function() {
  return this.setSupportedVersionsList([]);
};


/**
 * map<string, bool> capabilities = 4;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,boolean>}
 */
proto.cordum.agent.v1.Handshake.prototype.getCapabilitiesMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,boolean>} */ (
      jspb.Message.getMapField(this, 4, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.cordum.agent.v1.Handshake} returns this
 */
proto.cordum.agent.v1.Handshake.prototype.clearCapabilitiesMap = function() {
  this.getCapabilitiesMap().clear();
  return this;
};


/**
 * optional string sdk_version = 5;
 * @return {string}
 */
proto.cordum.agent.v1.Handshake.prototype.getSdkVersion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.cordum.agent.v1.Handshake} returns this
 */
proto.cordum.agent.v1.Handshake.prototype.setSdkVersion = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * repeated string ready_topics = 6;
 * @return {!Array<string>}
 */
proto.cordum.agent.v1.Handshake.prototype.getReadyTopicsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 6));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.cordum.agent.v1.Handshake} returns this
 */
proto.cordum.agent.v1.Handshake.prototype.setReadyTopicsList = function(value) {
  return jspb.Message.setField(this, 6, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.cordum.agent.v1.Handshake} returns this
 */
proto.cordum.agent.v1.Handshake.prototype.addReadyTopics = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 6, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.cordum.agent.v1.Handshake} returns this
 */
proto.cordum.agent.v1.Handshake.prototype.clearReadyTopicsList = function() {
  return this.setReadyTopicsList([]);
};


/**
 * optional string agent_name = 7;
 * @return {string}
 */
proto.cordum.agent.v1.Handshake.prototype.getAgentName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.cordum.agent.v1.Handshake} returns this
 */
proto.cordum.agent.v1.Handshake.prototype.setAgentName = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cordum.agent.v1.WorkerHandshakeChallengeRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.cordum.agent.v1.WorkerHandshakeChallengeRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cordum.agent.v1.WorkerHandshakeChallengeRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cordum.agent.v1.WorkerHandshakeChallengeRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
requestId: jspb.Message.getFieldWithDefault(msg, 1, ""),
traceId: jspb.Message.getFieldWithDefault(msg, 2, ""),
workerId: jspb.Message.getFieldWithDefault(msg, 3, ""),
proofKeyId: jspb.Message.getFieldWithDefault(msg, 4, ""),
proofAlgorithm: jspb.Message.getFieldWithDefault(msg, 5, 0),
audience: jspb.Message.getFieldWithDefault(msg, 6, ""),
purpose: jspb.Message.getFieldWithDefault(msg, 7, 0),
clientNonce: msg.getClientNonce_asB64(),
protocolVersion: jspb.Message.getFieldWithDefault(msg, 9, 0),
sdkVersion: jspb.Message.getFieldWithDefault(msg, 10, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cordum.agent.v1.WorkerHandshakeChallengeRequest}
 */
proto.cordum.agent.v1.WorkerHandshakeChallengeRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cordum.agent.v1.WorkerHandshakeChallengeRequest;
  return proto.cordum.agent.v1.WorkerHandshakeChallengeRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cordum.agent.v1.WorkerHandshakeChallengeRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cordum.agent.v1.WorkerHandshakeChallengeRequest}
 */
proto.cordum.agent.v1.WorkerHandshakeChallengeRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setRequestId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setTraceId(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setWorkerId(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setProofKeyId(value);
      break;
    case 5:
      var value = /** @type {!proto.cordum.agent.v1.WorkerHandshakeProofAlgorithm} */ (reader.readEnum());
      msg.setProofAlgorithm(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setAudience(value);
      break;
    case 7:
      var value = /** @type {!proto.cordum.agent.v1.WorkerHandshakePurpose} */ (reader.readEnum());
      msg.setPurpose(value);
      break;
    case 8:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setClientNonce(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setProtocolVersion(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setSdkVersion(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cordum.agent.v1.WorkerHandshakeChallengeRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cordum.agent.v1.WorkerHandshakeChallengeRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cordum.agent.v1.WorkerHandshakeChallengeRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cordum.agent.v1.WorkerHandshakeChallengeRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRequestId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getTraceId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getWorkerId();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getProofKeyId();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getProofAlgorithm();
  if (f !== 0.0) {
    writer.writeEnum(
      5,
      f
    );
  }
  f = message.getAudience();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getPurpose();
  if (f !== 0.0) {
    writer.writeEnum(
      7,
      f
    );
  }
  f = message.getClientNonce_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      8,
      f
    );
  }
  f = message.getProtocolVersion();
  if (f !== 0) {
    writer.writeInt32(
      9,
      f
    );
  }
  f = message.getSdkVersion();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
};


/**
 * optional string request_id = 1;
 * @return {string}
 */
proto.cordum.agent.v1.WorkerHandshakeChallengeRequest.prototype.getRequestId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.cordum.agent.v1.WorkerHandshakeChallengeRequest} returns this
 */
proto.cordum.agent.v1.WorkerHandshakeChallengeRequest.prototype.setRequestId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string trace_id = 2;
 * @return {string}
 */
proto.cordum.agent.v1.WorkerHandshakeChallengeRequest.prototype.getTraceId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.cordum.agent.v1.WorkerHandshakeChallengeRequest} returns this
 */
proto.cordum.agent.v1.WorkerHandshakeChallengeRequest.prototype.setTraceId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string worker_id = 3;
 * @return {string}
 */
proto.cordum.agent.v1.WorkerHandshakeChallengeRequest.prototype.getWorkerId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.cordum.agent.v1.WorkerHandshakeChallengeRequest} returns this
 */
proto.cordum.agent.v1.WorkerHandshakeChallengeRequest.prototype.setWorkerId = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string proof_key_id = 4;
 * @return {string}
 */
proto.cordum.agent.v1.WorkerHandshakeChallengeRequest.prototype.getProofKeyId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.cordum.agent.v1.WorkerHandshakeChallengeRequest} returns this
 */
proto.cordum.agent.v1.WorkerHandshakeChallengeRequest.prototype.setProofKeyId = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional WorkerHandshakeProofAlgorithm proof_algorithm = 5;
 * @return {!proto.cordum.agent.v1.WorkerHandshakeProofAlgorithm}
 */
proto.cordum.agent.v1.WorkerHandshakeChallengeRequest.prototype.getProofAlgorithm = function() {
  return /** @type {!proto.cordum.agent.v1.WorkerHandshakeProofAlgorithm} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {!proto.cordum.agent.v1.WorkerHandshakeProofAlgorithm} value
 * @return {!proto.cordum.agent.v1.WorkerHandshakeChallengeRequest} returns this
 */
proto.cordum.agent.v1.WorkerHandshakeChallengeRequest.prototype.setProofAlgorithm = function(value) {
  return jspb.Message.setProto3EnumField(this, 5, value);
};


/**
 * optional string audience = 6;
 * @return {string}
 */
proto.cordum.agent.v1.WorkerHandshakeChallengeRequest.prototype.getAudience = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.cordum.agent.v1.WorkerHandshakeChallengeRequest} returns this
 */
proto.cordum.agent.v1.WorkerHandshakeChallengeRequest.prototype.setAudience = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional WorkerHandshakePurpose purpose = 7;
 * @return {!proto.cordum.agent.v1.WorkerHandshakePurpose}
 */
proto.cordum.agent.v1.WorkerHandshakeChallengeRequest.prototype.getPurpose = function() {
  return /** @type {!proto.cordum.agent.v1.WorkerHandshakePurpose} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {!proto.cordum.agent.v1.WorkerHandshakePurpose} value
 * @return {!proto.cordum.agent.v1.WorkerHandshakeChallengeRequest} returns this
 */
proto.cordum.agent.v1.WorkerHandshakeChallengeRequest.prototype.setPurpose = function(value) {
  return jspb.Message.setProto3EnumField(this, 7, value);
};


/**
 * optional bytes client_nonce = 8;
 * @return {!(string|Uint8Array)}
 */
proto.cordum.agent.v1.WorkerHandshakeChallengeRequest.prototype.getClientNonce = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * optional bytes client_nonce = 8;
 * This is a type-conversion wrapper around `getClientNonce()`
 * @return {string}
 */
proto.cordum.agent.v1.WorkerHandshakeChallengeRequest.prototype.getClientNonce_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getClientNonce()));
};


/**
 * optional bytes client_nonce = 8;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getClientNonce()`
 * @return {!Uint8Array}
 */
proto.cordum.agent.v1.WorkerHandshakeChallengeRequest.prototype.getClientNonce_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getClientNonce()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.cordum.agent.v1.WorkerHandshakeChallengeRequest} returns this
 */
proto.cordum.agent.v1.WorkerHandshakeChallengeRequest.prototype.setClientNonce = function(value) {
  return jspb.Message.setProto3BytesField(this, 8, value);
};


/**
 * optional int32 protocol_version = 9;
 * @return {number}
 */
proto.cordum.agent.v1.WorkerHandshakeChallengeRequest.prototype.getProtocolVersion = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {number} value
 * @return {!proto.cordum.agent.v1.WorkerHandshakeChallengeRequest} returns this
 */
proto.cordum.agent.v1.WorkerHandshakeChallengeRequest.prototype.setProtocolVersion = function(value) {
  return jspb.Message.setProto3IntField(this, 9, value);
};


/**
 * optional string sdk_version = 10;
 * @return {string}
 */
proto.cordum.agent.v1.WorkerHandshakeChallengeRequest.prototype.getSdkVersion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/**
 * @param {string} value
 * @return {!proto.cordum.agent.v1.WorkerHandshakeChallengeRequest} returns this
 */
proto.cordum.agent.v1.WorkerHandshakeChallengeRequest.prototype.setSdkVersion = function(value) {
  return jspb.Message.setProto3StringField(this, 10, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cordum.agent.v1.WorkerHandshakeChallenge.prototype.toObject = function(opt_includeInstance) {
  return proto.cordum.agent.v1.WorkerHandshakeChallenge.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cordum.agent.v1.WorkerHandshakeChallenge} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cordum.agent.v1.WorkerHandshakeChallenge.toObject = function(includeInstance, msg) {
  var f, obj = {
requestId: jspb.Message.getFieldWithDefault(msg, 1, ""),
challengeId: jspb.Message.getFieldWithDefault(msg, 2, ""),
traceId: jspb.Message.getFieldWithDefault(msg, 3, ""),
workerId: jspb.Message.getFieldWithDefault(msg, 4, ""),
agentId: jspb.Message.getFieldWithDefault(msg, 5, ""),
tenantId: jspb.Message.getFieldWithDefault(msg, 6, ""),
proofKeyId: jspb.Message.getFieldWithDefault(msg, 7, ""),
proofAlgorithm: jspb.Message.getFieldWithDefault(msg, 8, 0),
serverKeyId: jspb.Message.getFieldWithDefault(msg, 9, ""),
audience: jspb.Message.getFieldWithDefault(msg, 10, ""),
purpose: jspb.Message.getFieldWithDefault(msg, 11, 0),
clientNonce: msg.getClientNonce_asB64(),
serverNonce: msg.getServerNonce_asB64(),
protocolVersion: jspb.Message.getFieldWithDefault(msg, 14, 0),
sdkVersion: jspb.Message.getFieldWithDefault(msg, 15, ""),
issuedAt: (f = msg.getIssuedAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
expiresAt: (f = msg.getExpiresAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cordum.agent.v1.WorkerHandshakeChallenge}
 */
proto.cordum.agent.v1.WorkerHandshakeChallenge.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cordum.agent.v1.WorkerHandshakeChallenge;
  return proto.cordum.agent.v1.WorkerHandshakeChallenge.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cordum.agent.v1.WorkerHandshakeChallenge} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cordum.agent.v1.WorkerHandshakeChallenge}
 */
proto.cordum.agent.v1.WorkerHandshakeChallenge.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setRequestId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setChallengeId(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setTraceId(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setWorkerId(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setAgentId(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setTenantId(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setProofKeyId(value);
      break;
    case 8:
      var value = /** @type {!proto.cordum.agent.v1.WorkerHandshakeProofAlgorithm} */ (reader.readEnum());
      msg.setProofAlgorithm(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setServerKeyId(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setAudience(value);
      break;
    case 11:
      var value = /** @type {!proto.cordum.agent.v1.WorkerHandshakePurpose} */ (reader.readEnum());
      msg.setPurpose(value);
      break;
    case 12:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setClientNonce(value);
      break;
    case 13:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setServerNonce(value);
      break;
    case 14:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setProtocolVersion(value);
      break;
    case 15:
      var value = /** @type {string} */ (reader.readString());
      msg.setSdkVersion(value);
      break;
    case 16:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setIssuedAt(value);
      break;
    case 17:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setExpiresAt(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cordum.agent.v1.WorkerHandshakeChallenge.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cordum.agent.v1.WorkerHandshakeChallenge.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cordum.agent.v1.WorkerHandshakeChallenge} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cordum.agent.v1.WorkerHandshakeChallenge.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRequestId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getChallengeId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getTraceId();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getWorkerId();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getAgentId();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getTenantId();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getProofKeyId();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getProofAlgorithm();
  if (f !== 0.0) {
    writer.writeEnum(
      8,
      f
    );
  }
  f = message.getServerKeyId();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
  f = message.getAudience();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
  f = message.getPurpose();
  if (f !== 0.0) {
    writer.writeEnum(
      11,
      f
    );
  }
  f = message.getClientNonce_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      12,
      f
    );
  }
  f = message.getServerNonce_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      13,
      f
    );
  }
  f = message.getProtocolVersion();
  if (f !== 0) {
    writer.writeInt32(
      14,
      f
    );
  }
  f = message.getSdkVersion();
  if (f.length > 0) {
    writer.writeString(
      15,
      f
    );
  }
  f = message.getIssuedAt();
  if (f != null) {
    writer.writeMessage(
      16,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getExpiresAt();
  if (f != null) {
    writer.writeMessage(
      17,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
};


/**
 * optional string request_id = 1;
 * @return {string}
 */
proto.cordum.agent.v1.WorkerHandshakeChallenge.prototype.getRequestId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.cordum.agent.v1.WorkerHandshakeChallenge} returns this
 */
proto.cordum.agent.v1.WorkerHandshakeChallenge.prototype.setRequestId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string challenge_id = 2;
 * @return {string}
 */
proto.cordum.agent.v1.WorkerHandshakeChallenge.prototype.getChallengeId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.cordum.agent.v1.WorkerHandshakeChallenge} returns this
 */
proto.cordum.agent.v1.WorkerHandshakeChallenge.prototype.setChallengeId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string trace_id = 3;
 * @return {string}
 */
proto.cordum.agent.v1.WorkerHandshakeChallenge.prototype.getTraceId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.cordum.agent.v1.WorkerHandshakeChallenge} returns this
 */
proto.cordum.agent.v1.WorkerHandshakeChallenge.prototype.setTraceId = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string worker_id = 4;
 * @return {string}
 */
proto.cordum.agent.v1.WorkerHandshakeChallenge.prototype.getWorkerId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.cordum.agent.v1.WorkerHandshakeChallenge} returns this
 */
proto.cordum.agent.v1.WorkerHandshakeChallenge.prototype.setWorkerId = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string agent_id = 5;
 * @return {string}
 */
proto.cordum.agent.v1.WorkerHandshakeChallenge.prototype.getAgentId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.cordum.agent.v1.WorkerHandshakeChallenge} returns this
 */
proto.cordum.agent.v1.WorkerHandshakeChallenge.prototype.setAgentId = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string tenant_id = 6;
 * @return {string}
 */
proto.cordum.agent.v1.WorkerHandshakeChallenge.prototype.getTenantId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.cordum.agent.v1.WorkerHandshakeChallenge} returns this
 */
proto.cordum.agent.v1.WorkerHandshakeChallenge.prototype.setTenantId = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string proof_key_id = 7;
 * @return {string}
 */
proto.cordum.agent.v1.WorkerHandshakeChallenge.prototype.getProofKeyId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.cordum.agent.v1.WorkerHandshakeChallenge} returns this
 */
proto.cordum.agent.v1.WorkerHandshakeChallenge.prototype.setProofKeyId = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional WorkerHandshakeProofAlgorithm proof_algorithm = 8;
 * @return {!proto.cordum.agent.v1.WorkerHandshakeProofAlgorithm}
 */
proto.cordum.agent.v1.WorkerHandshakeChallenge.prototype.getProofAlgorithm = function() {
  return /** @type {!proto.cordum.agent.v1.WorkerHandshakeProofAlgorithm} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {!proto.cordum.agent.v1.WorkerHandshakeProofAlgorithm} value
 * @return {!proto.cordum.agent.v1.WorkerHandshakeChallenge} returns this
 */
proto.cordum.agent.v1.WorkerHandshakeChallenge.prototype.setProofAlgorithm = function(value) {
  return jspb.Message.setProto3EnumField(this, 8, value);
};


/**
 * optional string server_key_id = 9;
 * @return {string}
 */
proto.cordum.agent.v1.WorkerHandshakeChallenge.prototype.getServerKeyId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/**
 * @param {string} value
 * @return {!proto.cordum.agent.v1.WorkerHandshakeChallenge} returns this
 */
proto.cordum.agent.v1.WorkerHandshakeChallenge.prototype.setServerKeyId = function(value) {
  return jspb.Message.setProto3StringField(this, 9, value);
};


/**
 * optional string audience = 10;
 * @return {string}
 */
proto.cordum.agent.v1.WorkerHandshakeChallenge.prototype.getAudience = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/**
 * @param {string} value
 * @return {!proto.cordum.agent.v1.WorkerHandshakeChallenge} returns this
 */
proto.cordum.agent.v1.WorkerHandshakeChallenge.prototype.setAudience = function(value) {
  return jspb.Message.setProto3StringField(this, 10, value);
};


/**
 * optional WorkerHandshakePurpose purpose = 11;
 * @return {!proto.cordum.agent.v1.WorkerHandshakePurpose}
 */
proto.cordum.agent.v1.WorkerHandshakeChallenge.prototype.getPurpose = function() {
  return /** @type {!proto.cordum.agent.v1.WorkerHandshakePurpose} */ (jspb.Message.getFieldWithDefault(this, 11, 0));
};


/**
 * @param {!proto.cordum.agent.v1.WorkerHandshakePurpose} value
 * @return {!proto.cordum.agent.v1.WorkerHandshakeChallenge} returns this
 */
proto.cordum.agent.v1.WorkerHandshakeChallenge.prototype.setPurpose = function(value) {
  return jspb.Message.setProto3EnumField(this, 11, value);
};


/**
 * optional bytes client_nonce = 12;
 * @return {!(string|Uint8Array)}
 */
proto.cordum.agent.v1.WorkerHandshakeChallenge.prototype.getClientNonce = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 12, ""));
};


/**
 * optional bytes client_nonce = 12;
 * This is a type-conversion wrapper around `getClientNonce()`
 * @return {string}
 */
proto.cordum.agent.v1.WorkerHandshakeChallenge.prototype.getClientNonce_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getClientNonce()));
};


/**
 * optional bytes client_nonce = 12;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getClientNonce()`
 * @return {!Uint8Array}
 */
proto.cordum.agent.v1.WorkerHandshakeChallenge.prototype.getClientNonce_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getClientNonce()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.cordum.agent.v1.WorkerHandshakeChallenge} returns this
 */
proto.cordum.agent.v1.WorkerHandshakeChallenge.prototype.setClientNonce = function(value) {
  return jspb.Message.setProto3BytesField(this, 12, value);
};


/**
 * optional bytes server_nonce = 13;
 * @return {!(string|Uint8Array)}
 */
proto.cordum.agent.v1.WorkerHandshakeChallenge.prototype.getServerNonce = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 13, ""));
};


/**
 * optional bytes server_nonce = 13;
 * This is a type-conversion wrapper around `getServerNonce()`
 * @return {string}
 */
proto.cordum.agent.v1.WorkerHandshakeChallenge.prototype.getServerNonce_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getServerNonce()));
};


/**
 * optional bytes server_nonce = 13;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getServerNonce()`
 * @return {!Uint8Array}
 */
proto.cordum.agent.v1.WorkerHandshakeChallenge.prototype.getServerNonce_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getServerNonce()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.cordum.agent.v1.WorkerHandshakeChallenge} returns this
 */
proto.cordum.agent.v1.WorkerHandshakeChallenge.prototype.setServerNonce = function(value) {
  return jspb.Message.setProto3BytesField(this, 13, value);
};


/**
 * optional int32 protocol_version = 14;
 * @return {number}
 */
proto.cordum.agent.v1.WorkerHandshakeChallenge.prototype.getProtocolVersion = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 14, 0));
};


/**
 * @param {number} value
 * @return {!proto.cordum.agent.v1.WorkerHandshakeChallenge} returns this
 */
proto.cordum.agent.v1.WorkerHandshakeChallenge.prototype.setProtocolVersion = function(value) {
  return jspb.Message.setProto3IntField(this, 14, value);
};


/**
 * optional string sdk_version = 15;
 * @return {string}
 */
proto.cordum.agent.v1.WorkerHandshakeChallenge.prototype.getSdkVersion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 15, ""));
};


/**
 * @param {string} value
 * @return {!proto.cordum.agent.v1.WorkerHandshakeChallenge} returns this
 */
proto.cordum.agent.v1.WorkerHandshakeChallenge.prototype.setSdkVersion = function(value) {
  return jspb.Message.setProto3StringField(this, 15, value);
};


/**
 * optional google.protobuf.Timestamp issued_at = 16;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.cordum.agent.v1.WorkerHandshakeChallenge.prototype.getIssuedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 16));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.cordum.agent.v1.WorkerHandshakeChallenge} returns this
*/
proto.cordum.agent.v1.WorkerHandshakeChallenge.prototype.setIssuedAt = function(value) {
  return jspb.Message.setWrapperField(this, 16, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cordum.agent.v1.WorkerHandshakeChallenge} returns this
 */
proto.cordum.agent.v1.WorkerHandshakeChallenge.prototype.clearIssuedAt = function() {
  return this.setIssuedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cordum.agent.v1.WorkerHandshakeChallenge.prototype.hasIssuedAt = function() {
  return jspb.Message.getField(this, 16) != null;
};


/**
 * optional google.protobuf.Timestamp expires_at = 17;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.cordum.agent.v1.WorkerHandshakeChallenge.prototype.getExpiresAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 17));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.cordum.agent.v1.WorkerHandshakeChallenge} returns this
*/
proto.cordum.agent.v1.WorkerHandshakeChallenge.prototype.setExpiresAt = function(value) {
  return jspb.Message.setWrapperField(this, 17, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cordum.agent.v1.WorkerHandshakeChallenge} returns this
 */
proto.cordum.agent.v1.WorkerHandshakeChallenge.prototype.clearExpiresAt = function() {
  return this.setExpiresAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cordum.agent.v1.WorkerHandshakeChallenge.prototype.hasExpiresAt = function() {
  return jspb.Message.getField(this, 17) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cordum.agent.v1.WorkerHandshakeAuthenticate.prototype.toObject = function(opt_includeInstance) {
  return proto.cordum.agent.v1.WorkerHandshakeAuthenticate.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cordum.agent.v1.WorkerHandshakeAuthenticate} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cordum.agent.v1.WorkerHandshakeAuthenticate.toObject = function(includeInstance, msg) {
  var f, obj = {
challenge: (f = msg.getChallenge()) && proto.cordum.agent.v1.WorkerHandshakeChallenge.toObject(includeInstance, f),
capabilityHandshake: (f = msg.getCapabilityHandshake()) && proto.cordum.agent.v1.Handshake.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cordum.agent.v1.WorkerHandshakeAuthenticate}
 */
proto.cordum.agent.v1.WorkerHandshakeAuthenticate.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cordum.agent.v1.WorkerHandshakeAuthenticate;
  return proto.cordum.agent.v1.WorkerHandshakeAuthenticate.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cordum.agent.v1.WorkerHandshakeAuthenticate} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cordum.agent.v1.WorkerHandshakeAuthenticate}
 */
proto.cordum.agent.v1.WorkerHandshakeAuthenticate.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.cordum.agent.v1.WorkerHandshakeChallenge;
      reader.readMessage(value,proto.cordum.agent.v1.WorkerHandshakeChallenge.deserializeBinaryFromReader);
      msg.setChallenge(value);
      break;
    case 2:
      var value = new proto.cordum.agent.v1.Handshake;
      reader.readMessage(value,proto.cordum.agent.v1.Handshake.deserializeBinaryFromReader);
      msg.setCapabilityHandshake(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cordum.agent.v1.WorkerHandshakeAuthenticate.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cordum.agent.v1.WorkerHandshakeAuthenticate.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cordum.agent.v1.WorkerHandshakeAuthenticate} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cordum.agent.v1.WorkerHandshakeAuthenticate.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getChallenge();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.cordum.agent.v1.WorkerHandshakeChallenge.serializeBinaryToWriter
    );
  }
  f = message.getCapabilityHandshake();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.cordum.agent.v1.Handshake.serializeBinaryToWriter
    );
  }
};


/**
 * optional WorkerHandshakeChallenge challenge = 1;
 * @return {?proto.cordum.agent.v1.WorkerHandshakeChallenge}
 */
proto.cordum.agent.v1.WorkerHandshakeAuthenticate.prototype.getChallenge = function() {
  return /** @type{?proto.cordum.agent.v1.WorkerHandshakeChallenge} */ (
    jspb.Message.getWrapperField(this, proto.cordum.agent.v1.WorkerHandshakeChallenge, 1));
};


/**
 * @param {?proto.cordum.agent.v1.WorkerHandshakeChallenge|undefined} value
 * @return {!proto.cordum.agent.v1.WorkerHandshakeAuthenticate} returns this
*/
proto.cordum.agent.v1.WorkerHandshakeAuthenticate.prototype.setChallenge = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cordum.agent.v1.WorkerHandshakeAuthenticate} returns this
 */
proto.cordum.agent.v1.WorkerHandshakeAuthenticate.prototype.clearChallenge = function() {
  return this.setChallenge(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cordum.agent.v1.WorkerHandshakeAuthenticate.prototype.hasChallenge = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Handshake capability_handshake = 2;
 * @return {?proto.cordum.agent.v1.Handshake}
 */
proto.cordum.agent.v1.WorkerHandshakeAuthenticate.prototype.getCapabilityHandshake = function() {
  return /** @type{?proto.cordum.agent.v1.Handshake} */ (
    jspb.Message.getWrapperField(this, proto.cordum.agent.v1.Handshake, 2));
};


/**
 * @param {?proto.cordum.agent.v1.Handshake|undefined} value
 * @return {!proto.cordum.agent.v1.WorkerHandshakeAuthenticate} returns this
*/
proto.cordum.agent.v1.WorkerHandshakeAuthenticate.prototype.setCapabilityHandshake = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cordum.agent.v1.WorkerHandshakeAuthenticate} returns this
 */
proto.cordum.agent.v1.WorkerHandshakeAuthenticate.prototype.clearCapabilityHandshake = function() {
  return this.setCapabilityHandshake(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cordum.agent.v1.WorkerHandshakeAuthenticate.prototype.hasCapabilityHandshake = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cordum.agent.v1.WorkerHandshakeResult.prototype.toObject = function(opt_includeInstance) {
  return proto.cordum.agent.v1.WorkerHandshakeResult.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cordum.agent.v1.WorkerHandshakeResult} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cordum.agent.v1.WorkerHandshakeResult.toObject = function(includeInstance, msg) {
  var f, obj = {
challenge: (f = msg.getChallenge()) && proto.cordum.agent.v1.WorkerHandshakeChallenge.toObject(includeInstance, f),
accepted: jspb.Message.getBooleanFieldWithDefault(msg, 2, false),
rejectionReason: jspb.Message.getFieldWithDefault(msg, 3, 0),
tokenExpiresAt: (f = msg.getTokenExpiresAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
issuedAt: (f = msg.getIssuedAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cordum.agent.v1.WorkerHandshakeResult}
 */
proto.cordum.agent.v1.WorkerHandshakeResult.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cordum.agent.v1.WorkerHandshakeResult;
  return proto.cordum.agent.v1.WorkerHandshakeResult.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cordum.agent.v1.WorkerHandshakeResult} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cordum.agent.v1.WorkerHandshakeResult}
 */
proto.cordum.agent.v1.WorkerHandshakeResult.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.cordum.agent.v1.WorkerHandshakeChallenge;
      reader.readMessage(value,proto.cordum.agent.v1.WorkerHandshakeChallenge.deserializeBinaryFromReader);
      msg.setChallenge(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setAccepted(value);
      break;
    case 3:
      var value = /** @type {!proto.cordum.agent.v1.WorkerHandshakeRejectionReason} */ (reader.readEnum());
      msg.setRejectionReason(value);
      break;
    case 4:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setTokenExpiresAt(value);
      break;
    case 5:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setIssuedAt(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cordum.agent.v1.WorkerHandshakeResult.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cordum.agent.v1.WorkerHandshakeResult.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cordum.agent.v1.WorkerHandshakeResult} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cordum.agent.v1.WorkerHandshakeResult.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getChallenge();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.cordum.agent.v1.WorkerHandshakeChallenge.serializeBinaryToWriter
    );
  }
  f = message.getAccepted();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
  f = message.getRejectionReason();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
  f = message.getTokenExpiresAt();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getIssuedAt();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
};


/**
 * optional WorkerHandshakeChallenge challenge = 1;
 * @return {?proto.cordum.agent.v1.WorkerHandshakeChallenge}
 */
proto.cordum.agent.v1.WorkerHandshakeResult.prototype.getChallenge = function() {
  return /** @type{?proto.cordum.agent.v1.WorkerHandshakeChallenge} */ (
    jspb.Message.getWrapperField(this, proto.cordum.agent.v1.WorkerHandshakeChallenge, 1));
};


/**
 * @param {?proto.cordum.agent.v1.WorkerHandshakeChallenge|undefined} value
 * @return {!proto.cordum.agent.v1.WorkerHandshakeResult} returns this
*/
proto.cordum.agent.v1.WorkerHandshakeResult.prototype.setChallenge = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cordum.agent.v1.WorkerHandshakeResult} returns this
 */
proto.cordum.agent.v1.WorkerHandshakeResult.prototype.clearChallenge = function() {
  return this.setChallenge(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cordum.agent.v1.WorkerHandshakeResult.prototype.hasChallenge = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional bool accepted = 2;
 * @return {boolean}
 */
proto.cordum.agent.v1.WorkerHandshakeResult.prototype.getAccepted = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.cordum.agent.v1.WorkerHandshakeResult} returns this
 */
proto.cordum.agent.v1.WorkerHandshakeResult.prototype.setAccepted = function(value) {
  return jspb.Message.setProto3BooleanField(this, 2, value);
};


/**
 * optional WorkerHandshakeRejectionReason rejection_reason = 3;
 * @return {!proto.cordum.agent.v1.WorkerHandshakeRejectionReason}
 */
proto.cordum.agent.v1.WorkerHandshakeResult.prototype.getRejectionReason = function() {
  return /** @type {!proto.cordum.agent.v1.WorkerHandshakeRejectionReason} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {!proto.cordum.agent.v1.WorkerHandshakeRejectionReason} value
 * @return {!proto.cordum.agent.v1.WorkerHandshakeResult} returns this
 */
proto.cordum.agent.v1.WorkerHandshakeResult.prototype.setRejectionReason = function(value) {
  return jspb.Message.setProto3EnumField(this, 3, value);
};


/**
 * optional google.protobuf.Timestamp token_expires_at = 4;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.cordum.agent.v1.WorkerHandshakeResult.prototype.getTokenExpiresAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 4));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.cordum.agent.v1.WorkerHandshakeResult} returns this
*/
proto.cordum.agent.v1.WorkerHandshakeResult.prototype.setTokenExpiresAt = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cordum.agent.v1.WorkerHandshakeResult} returns this
 */
proto.cordum.agent.v1.WorkerHandshakeResult.prototype.clearTokenExpiresAt = function() {
  return this.setTokenExpiresAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cordum.agent.v1.WorkerHandshakeResult.prototype.hasTokenExpiresAt = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional google.protobuf.Timestamp issued_at = 5;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.cordum.agent.v1.WorkerHandshakeResult.prototype.getIssuedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 5));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.cordum.agent.v1.WorkerHandshakeResult} returns this
*/
proto.cordum.agent.v1.WorkerHandshakeResult.prototype.setIssuedAt = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cordum.agent.v1.WorkerHandshakeResult} returns this
 */
proto.cordum.agent.v1.WorkerHandshakeResult.prototype.clearIssuedAt = function() {
  return this.setIssuedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cordum.agent.v1.WorkerHandshakeResult.prototype.hasIssuedAt = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * @enum {number}
 */
proto.cordum.agent.v1.ComponentRole = {
  COMPONENT_ROLE_UNSPECIFIED: 0,
  COMPONENT_ROLE_GATEWAY: 1,
  COMPONENT_ROLE_SCHEDULER: 2,
  COMPONENT_ROLE_WORKER: 3,
  COMPONENT_ROLE_ORCHESTRATOR: 4,
  COMPONENT_ROLE_CONTROLLER: 5
};

/**
 * @enum {number}
 */
proto.cordum.agent.v1.WorkerHandshakePurpose = {
  WORKER_HANDSHAKE_PURPOSE_UNSPECIFIED: 0,
  WORKER_HANDSHAKE_PURPOSE_ISSUE: 1,
  WORKER_HANDSHAKE_PURPOSE_RENEW: 2
};

/**
 * @enum {number}
 */
proto.cordum.agent.v1.WorkerHandshakeProofAlgorithm = {
  WORKER_HANDSHAKE_PROOF_ALGORITHM_UNSPECIFIED: 0,
  WORKER_HANDSHAKE_PROOF_ALGORITHM_ECDSA_P256_SHA256: 1
};

/**
 * @enum {number}
 */
proto.cordum.agent.v1.WorkerHandshakeRejectionReason = {
  WORKER_HANDSHAKE_REJECTION_REASON_UNSPECIFIED: 0,
  WORKER_HANDSHAKE_REJECTION_REASON_INVALID_REQUEST: 1,
  WORKER_HANDSHAKE_REJECTION_REASON_AUTHENTICATION_FAILED: 2,
  WORKER_HANDSHAKE_REJECTION_REASON_REPLAY_DETECTED: 3,
  WORKER_HANDSHAKE_REJECTION_REASON_CLOCK_SKEW: 4,
  WORKER_HANDSHAKE_REJECTION_REASON_CHALLENGE_EXPIRED: 5,
  WORKER_HANDSHAKE_REJECTION_REASON_SESSION_REQUIRED: 6,
  WORKER_HANDSHAKE_REJECTION_REASON_SESSION_INVALID: 7,
  WORKER_HANDSHAKE_REJECTION_REASON_UNSUPPORTED_VERSION: 8,
  WORKER_HANDSHAKE_REJECTION_REASON_INTERNAL_ERROR: 9
};

goog.object.extend(exports, proto.cordum.agent.v1);
