package codegen

import (
	"encoding/json"
	"io/fs"
	"os"
	"path"
	"path/filepath"
	"sort"
	"strings"
	"testing"
)

// generatedSurface is one checked-in directory that a pinned generator owns,
// plus the suffixes that generator emits into it. It mirrors the LANGUAGES
// table in tools/proto_codegen.py, which is the generator's own view of what it
// writes. Anything matching a surface here is generated by definition, so the
// manifest must declare it or `cap-codegen check` cannot detect its drift.
type generatedSurface struct {
	dir      string
	suffixes []string
}

var generatedSurfaces = []generatedSurface{
	{"cordum/agent/v1", []string{".pb.go"}},
	{"cpp/cordum/agent/v1", []string{".pb.cc", ".pb.h"}},
	{"node", []string{"_pb.js", "_pb.d.ts"}},
	{"python/cordum/agent/v1", []string{"_pb2.py", "_pb2_grpc.py"}},
	{"sdk/python/cap/pb/cordum/agent/v1", []string{"_pb2.py", "_pb2_grpc.py"}},
	{"sdk/ruby/proto/cordum/agent/v1", []string{"_pb.rb"}},
}

func loadShippedManifest(t *testing.T) *Manifest {
	t.Helper()
	data, err := os.ReadFile("manifest.json")
	if err != nil {
		t.Fatalf("read shipped manifest: %v", err)
	}
	var m Manifest
	if err := json.Unmarshal(data, &m); err != nil {
		t.Fatalf("parse manifest: %v", err)
	}
	return &m
}

// walkGeneratedTree returns every file in the real repository that lands on a
// generated surface.
func walkGeneratedTree(t *testing.T) []string {
	t.Helper()
	root := os.DirFS(filepath.Join("..", ".."))
	var found []string
	for _, surface := range generatedSurfaces {
		err := fs.WalkDir(root, surface.dir, func(name string, d fs.DirEntry, walkErr error) error {
			if walkErr != nil || d.IsDir() {
				return walkErr
			}
			for _, suffix := range surface.suffixes {
				if strings.HasSuffix(name, suffix) {
					found = append(found, name)
					return nil
				}
			}
			return nil
		})
		if err != nil {
			t.Fatalf("walk %s: %v", surface.dir, err)
		}
	}
	sort.Strings(found)
	return found
}

// Every generated file on disk must be declared in the manifest. A generated
// artifact the manifest omits is invisible to `cap-codegen check`: it can be
// hand-edited or left stale and CI stays green. This is the completeness half
// of drift detection — CodeOutputUnmanifested only fires for files a
// generatedGlob already claims, so a file no glob matches is silently exempt.
func TestManifestDeclaresEveryGeneratedFileInTree(t *testing.T) {
	m := loadShippedManifest(t)
	declared := make(map[string]bool, len(m.Outputs))
	for _, output := range m.Outputs {
		declared[output.Path] = true
	}
	var undeclared []string
	for _, name := range walkGeneratedTree(t) {
		if !declared[name] {
			undeclared = append(undeclared, name)
		}
	}
	if len(undeclared) > 0 {
		t.Fatalf("%d generated files are not declared in the manifest, so their drift is undetectable:\n%s",
			len(undeclared), strings.Join(undeclared, "\n"))
	}
}

// The converse: every generatedGlob must be matched by at least one declared
// output. A glob that matches nothing is a generator silently producing no
// output — the "skipped generator wearing a green badge" failure mode.
func TestEveryGeneratedGlobClaimsAtLeastOneOutput(t *testing.T) {
	m := loadShippedManifest(t)
	for _, glob := range m.GeneratedGlobs {
		matched := false
		for _, output := range m.Outputs {
			if ok, err := path.Match(glob, output.Path); err != nil {
				t.Fatalf("bad glob %q: %v", glob, err)
			} else if ok {
				matched = true
				break
			}
		}
		if !matched {
			t.Errorf("generatedGlob %q matches no declared output", glob)
		}
	}
}
