// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: cordum/agent/v1/alert.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AlertSeverity represents the severity of a system alert.
type AlertSeverity int32

const (
	AlertSeverity_ALERT_SEVERITY_UNSPECIFIED AlertSeverity = 0
	AlertSeverity_ALERT_SEVERITY_INFO        AlertSeverity = 1
	AlertSeverity_ALERT_SEVERITY_WARNING     AlertSeverity = 2
	AlertSeverity_ALERT_SEVERITY_ERROR       AlertSeverity = 3
	AlertSeverity_ALERT_SEVERITY_CRITICAL    AlertSeverity = 4
)

// Enum value maps for AlertSeverity.
var (
	AlertSeverity_name = map[int32]string{
		0: "ALERT_SEVERITY_UNSPECIFIED",
		1: "ALERT_SEVERITY_INFO",
		2: "ALERT_SEVERITY_WARNING",
		3: "ALERT_SEVERITY_ERROR",
		4: "ALERT_SEVERITY_CRITICAL",
	}
	AlertSeverity_value = map[string]int32{
		"ALERT_SEVERITY_UNSPECIFIED": 0,
		"ALERT_SEVERITY_INFO":        1,
		"ALERT_SEVERITY_WARNING":     2,
		"ALERT_SEVERITY_ERROR":       3,
		"ALERT_SEVERITY_CRITICAL":    4,
	}
)

func (x AlertSeverity) Enum() *AlertSeverity {
	p := new(AlertSeverity)
	*p = x
	return p
}

func (x AlertSeverity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AlertSeverity) Descriptor() protoreflect.EnumDescriptor {
	return file_cordum_agent_v1_alert_proto_enumTypes[0].Descriptor()
}

func (AlertSeverity) Type() protoreflect.EnumType {
	return &file_cordum_agent_v1_alert_proto_enumTypes[0]
}

func (x AlertSeverity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AlertSeverity.Descriptor instead.
func (AlertSeverity) EnumDescriptor() ([]byte, []int) {
	return file_cordum_agent_v1_alert_proto_rawDescGZIP(), []int{0}
}

// SystemAlert is a lightweight signal for system-level issues.
type SystemAlert struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Deprecated: Marked as deprecated in cordum/agent/v1/alert.proto.
	Level   string `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"`     // Deprecated: use severity enum instead.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // Human-readable detail of the alert.
	// Deprecated: Marked as deprecated in cordum/agent/v1/alert.proto.
	Component string `protobuf:"bytes,3,opt,name=component,proto3" json:"component,omitempty"` // Deprecated: use source_component instead.
	// Deprecated: Marked as deprecated in cordum/agent/v1/alert.proto.
	Code            string            `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`                                                                                 // Deprecated: use error_code_enum instead.
	Severity        AlertSeverity     `protobuf:"varint,5,opt,name=severity,proto3,enum=cordum.agent.v1.AlertSeverity" json:"severity,omitempty"`                                     // structured severity level
	ErrorCodeEnum   ErrorCode         `protobuf:"varint,6,opt,name=error_code_enum,json=errorCodeEnum,proto3,enum=cordum.agent.v1.ErrorCode" json:"error_code_enum,omitempty"`        // structured error code from ErrorCode registry
	SourceComponent string            `protobuf:"bytes,7,opt,name=source_component,json=sourceComponent,proto3" json:"source_component,omitempty"`                                    // component ID that emitted the alert
	Details         map[string]string `protobuf:"bytes,8,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // structured key-value context
	TraceId         string            `protobuf:"bytes,9,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`                                                            // optional correlation to a specific BusPacket
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SystemAlert) Reset() {
	*x = SystemAlert{}
	mi := &file_cordum_agent_v1_alert_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemAlert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemAlert) ProtoMessage() {}

func (x *SystemAlert) ProtoReflect() protoreflect.Message {
	mi := &file_cordum_agent_v1_alert_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemAlert.ProtoReflect.Descriptor instead.
func (*SystemAlert) Descriptor() ([]byte, []int) {
	return file_cordum_agent_v1_alert_proto_rawDescGZIP(), []int{0}
}

// Deprecated: Marked as deprecated in cordum/agent/v1/alert.proto.
func (x *SystemAlert) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *SystemAlert) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Deprecated: Marked as deprecated in cordum/agent/v1/alert.proto.
func (x *SystemAlert) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

// Deprecated: Marked as deprecated in cordum/agent/v1/alert.proto.
func (x *SystemAlert) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *SystemAlert) GetSeverity() AlertSeverity {
	if x != nil {
		return x.Severity
	}
	return AlertSeverity_ALERT_SEVERITY_UNSPECIFIED
}

func (x *SystemAlert) GetErrorCodeEnum() ErrorCode {
	if x != nil {
		return x.ErrorCodeEnum
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

func (x *SystemAlert) GetSourceComponent() string {
	if x != nil {
		return x.SourceComponent
	}
	return ""
}

func (x *SystemAlert) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *SystemAlert) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

var File_cordum_agent_v1_alert_proto protoreflect.FileDescriptor

const file_cordum_agent_v1_alert_proto_rawDesc = "" +
	"\n" +
	"\x1bcordum/agent/v1/alert.proto\x12\x0fcordum.agent.v1\x1a\x19cordum/agent/v1/job.proto\"\xc2\x03\n" +
	"\vSystemAlert\x12\x18\n" +
	"\x05level\x18\x01 \x01(\tB\x02\x18\x01R\x05level\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12 \n" +
	"\tcomponent\x18\x03 \x01(\tB\x02\x18\x01R\tcomponent\x12\x16\n" +
	"\x04code\x18\x04 \x01(\tB\x02\x18\x01R\x04code\x12:\n" +
	"\bseverity\x18\x05 \x01(\x0e2\x1e.cordum.agent.v1.AlertSeverityR\bseverity\x12B\n" +
	"\x0ferror_code_enum\x18\x06 \x01(\x0e2\x1a.cordum.agent.v1.ErrorCodeR\rerrorCodeEnum\x12)\n" +
	"\x10source_component\x18\a \x01(\tR\x0fsourceComponent\x12C\n" +
	"\adetails\x18\b \x03(\v2).cordum.agent.v1.SystemAlert.DetailsEntryR\adetails\x12\x19\n" +
	"\btrace_id\x18\t \x01(\tR\atraceId\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\x9b\x01\n" +
	"\rAlertSeverity\x12\x1e\n" +
	"\x1aALERT_SEVERITY_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13ALERT_SEVERITY_INFO\x10\x01\x12\x1a\n" +
	"\x16ALERT_SEVERITY_WARNING\x10\x02\x12\x18\n" +
	"\x14ALERT_SEVERITY_ERROR\x10\x03\x12\x1b\n" +
	"\x17ALERT_SEVERITY_CRITICAL\x10\x04B\x7f\n" +
	"\x16io.cordum.cap.agent.v1P\x01Z+github.com/cordum-io/cap/v2/cordum/agent/v1\xaa\x02\x0fCordum.Agent.V1\xca\x02\x0fcordum\\Agent\\V1\xea\x02\x11Cordum::Agent::V1b\x06proto3"

var (
	file_cordum_agent_v1_alert_proto_rawDescOnce sync.Once
	file_cordum_agent_v1_alert_proto_rawDescData []byte
)

func file_cordum_agent_v1_alert_proto_rawDescGZIP() []byte {
	file_cordum_agent_v1_alert_proto_rawDescOnce.Do(func() {
		file_cordum_agent_v1_alert_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cordum_agent_v1_alert_proto_rawDesc), len(file_cordum_agent_v1_alert_proto_rawDesc)))
	})
	return file_cordum_agent_v1_alert_proto_rawDescData
}

var file_cordum_agent_v1_alert_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cordum_agent_v1_alert_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_cordum_agent_v1_alert_proto_goTypes = []any{
	(AlertSeverity)(0),  // 0: cordum.agent.v1.AlertSeverity
	(*SystemAlert)(nil), // 1: cordum.agent.v1.SystemAlert
	nil,                 // 2: cordum.agent.v1.SystemAlert.DetailsEntry
	(ErrorCode)(0),      // 3: cordum.agent.v1.ErrorCode
}
var file_cordum_agent_v1_alert_proto_depIdxs = []int32{
	0, // 0: cordum.agent.v1.SystemAlert.severity:type_name -> cordum.agent.v1.AlertSeverity
	3, // 1: cordum.agent.v1.SystemAlert.error_code_enum:type_name -> cordum.agent.v1.ErrorCode
	2, // 2: cordum.agent.v1.SystemAlert.details:type_name -> cordum.agent.v1.SystemAlert.DetailsEntry
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_cordum_agent_v1_alert_proto_init() }
func file_cordum_agent_v1_alert_proto_init() {
	if File_cordum_agent_v1_alert_proto != nil {
		return
	}
	file_cordum_agent_v1_job_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cordum_agent_v1_alert_proto_rawDesc), len(file_cordum_agent_v1_alert_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cordum_agent_v1_alert_proto_goTypes,
		DependencyIndexes: file_cordum_agent_v1_alert_proto_depIdxs,
		EnumInfos:         file_cordum_agent_v1_alert_proto_enumTypes,
		MessageInfos:      file_cordum_agent_v1_alert_proto_msgTypes,
	}.Build()
	File_cordum_agent_v1_alert_proto = out.File
	file_cordum_agent_v1_alert_proto_goTypes = nil
	file_cordum_agent_v1_alert_proto_depIdxs = nil
}
