// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: cordum/agent/v1/buspacket.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BusPacket is the envelope for all traffic on the bus.
type BusPacket struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TraceId           string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`                               // correlates related packets
	SenderId          string                 `protobuf:"bytes,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`                            // emitting agent id
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                         // emission time
	ProtocolVersion   int32                  `protobuf:"varint,4,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`      // CAP wire version
	SignatureMetadata *SignatureMetadata     `protobuf:"bytes,5,opt,name=signature_metadata,json=signatureMetadata,proto3" json:"signature_metadata,omitempty"` // CAP-PRODUCTION signing profile
	Identity          *IdentityBinding       `protobuf:"bytes,6,opt,name=identity,proto3" json:"identity,omitempty"`                                            // mirrors authenticated session identity
	// Types that are valid to be assigned to Payload:
	//
	//	*BusPacket_JobRequest
	//	*BusPacket_JobResult
	//	*BusPacket_Heartbeat
	//	*BusPacket_Alert
	//	*BusPacket_JobProgress
	//	*BusPacket_JobCancel
	//	*BusPacket_Handshake
	//	*BusPacket_WorkerHandshakeChallengeRequest
	//	*BusPacket_WorkerHandshakeChallenge
	//	*BusPacket_WorkerHandshakeAuthenticate
	//	*BusPacket_WorkerHandshakeResult
	Payload       isBusPacket_Payload `protobuf_oneof:"payload"`
	Signature     []byte              `protobuf:"bytes,14,opt,name=signature,proto3" json:"signature,omitempty"`                  // digital signature of the serialized BusPacket
	AuthToken     string              `protobuf:"bytes,18,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"` // trusted runtime session token
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BusPacket) Reset() {
	*x = BusPacket{}
	mi := &file_cordum_agent_v1_buspacket_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BusPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BusPacket) ProtoMessage() {}

func (x *BusPacket) ProtoReflect() protoreflect.Message {
	mi := &file_cordum_agent_v1_buspacket_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BusPacket.ProtoReflect.Descriptor instead.
func (*BusPacket) Descriptor() ([]byte, []int) {
	return file_cordum_agent_v1_buspacket_proto_rawDescGZIP(), []int{0}
}

func (x *BusPacket) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *BusPacket) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *BusPacket) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *BusPacket) GetProtocolVersion() int32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *BusPacket) GetSignatureMetadata() *SignatureMetadata {
	if x != nil {
		return x.SignatureMetadata
	}
	return nil
}

func (x *BusPacket) GetIdentity() *IdentityBinding {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *BusPacket) GetPayload() isBusPacket_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *BusPacket) GetJobRequest() *JobRequest {
	if x != nil {
		if x, ok := x.Payload.(*BusPacket_JobRequest); ok {
			return x.JobRequest
		}
	}
	return nil
}

func (x *BusPacket) GetJobResult() *JobResult {
	if x != nil {
		if x, ok := x.Payload.(*BusPacket_JobResult); ok {
			return x.JobResult
		}
	}
	return nil
}

func (x *BusPacket) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*BusPacket_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *BusPacket) GetAlert() *SystemAlert {
	if x != nil {
		if x, ok := x.Payload.(*BusPacket_Alert); ok {
			return x.Alert
		}
	}
	return nil
}

func (x *BusPacket) GetJobProgress() *JobProgress {
	if x != nil {
		if x, ok := x.Payload.(*BusPacket_JobProgress); ok {
			return x.JobProgress
		}
	}
	return nil
}

func (x *BusPacket) GetJobCancel() *JobCancel {
	if x != nil {
		if x, ok := x.Payload.(*BusPacket_JobCancel); ok {
			return x.JobCancel
		}
	}
	return nil
}

func (x *BusPacket) GetHandshake() *Handshake {
	if x != nil {
		if x, ok := x.Payload.(*BusPacket_Handshake); ok {
			return x.Handshake
		}
	}
	return nil
}

func (x *BusPacket) GetWorkerHandshakeChallengeRequest() *WorkerHandshakeChallengeRequest {
	if x != nil {
		if x, ok := x.Payload.(*BusPacket_WorkerHandshakeChallengeRequest); ok {
			return x.WorkerHandshakeChallengeRequest
		}
	}
	return nil
}

func (x *BusPacket) GetWorkerHandshakeChallenge() *WorkerHandshakeChallenge {
	if x != nil {
		if x, ok := x.Payload.(*BusPacket_WorkerHandshakeChallenge); ok {
			return x.WorkerHandshakeChallenge
		}
	}
	return nil
}

func (x *BusPacket) GetWorkerHandshakeAuthenticate() *WorkerHandshakeAuthenticate {
	if x != nil {
		if x, ok := x.Payload.(*BusPacket_WorkerHandshakeAuthenticate); ok {
			return x.WorkerHandshakeAuthenticate
		}
	}
	return nil
}

func (x *BusPacket) GetWorkerHandshakeResult() *WorkerHandshakeResult {
	if x != nil {
		if x, ok := x.Payload.(*BusPacket_WorkerHandshakeResult); ok {
			return x.WorkerHandshakeResult
		}
	}
	return nil
}

func (x *BusPacket) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *BusPacket) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

type isBusPacket_Payload interface {
	isBusPacket_Payload()
}

type BusPacket_JobRequest struct {
	JobRequest *JobRequest `protobuf:"bytes,10,opt,name=job_request,json=jobRequest,proto3,oneof"`
}

type BusPacket_JobResult struct {
	JobResult *JobResult `protobuf:"bytes,11,opt,name=job_result,json=jobResult,proto3,oneof"`
}

type BusPacket_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,12,opt,name=heartbeat,proto3,oneof"`
}

type BusPacket_Alert struct {
	Alert *SystemAlert `protobuf:"bytes,13,opt,name=alert,proto3,oneof"`
}

type BusPacket_JobProgress struct {
	JobProgress *JobProgress `protobuf:"bytes,15,opt,name=job_progress,json=jobProgress,proto3,oneof"`
}

type BusPacket_JobCancel struct {
	JobCancel *JobCancel `protobuf:"bytes,16,opt,name=job_cancel,json=jobCancel,proto3,oneof"`
}

type BusPacket_Handshake struct {
	Handshake *Handshake `protobuf:"bytes,17,opt,name=handshake,proto3,oneof"`
}

type BusPacket_WorkerHandshakeChallengeRequest struct {
	WorkerHandshakeChallengeRequest *WorkerHandshakeChallengeRequest `protobuf:"bytes,19,opt,name=worker_handshake_challenge_request,json=workerHandshakeChallengeRequest,proto3,oneof"`
}

type BusPacket_WorkerHandshakeChallenge struct {
	WorkerHandshakeChallenge *WorkerHandshakeChallenge `protobuf:"bytes,20,opt,name=worker_handshake_challenge,json=workerHandshakeChallenge,proto3,oneof"`
}

type BusPacket_WorkerHandshakeAuthenticate struct {
	WorkerHandshakeAuthenticate *WorkerHandshakeAuthenticate `protobuf:"bytes,21,opt,name=worker_handshake_authenticate,json=workerHandshakeAuthenticate,proto3,oneof"`
}

type BusPacket_WorkerHandshakeResult struct {
	WorkerHandshakeResult *WorkerHandshakeResult `protobuf:"bytes,22,opt,name=worker_handshake_result,json=workerHandshakeResult,proto3,oneof"`
}

func (*BusPacket_JobRequest) isBusPacket_Payload() {}

func (*BusPacket_JobResult) isBusPacket_Payload() {}

func (*BusPacket_Heartbeat) isBusPacket_Payload() {}

func (*BusPacket_Alert) isBusPacket_Payload() {}

func (*BusPacket_JobProgress) isBusPacket_Payload() {}

func (*BusPacket_JobCancel) isBusPacket_Payload() {}

func (*BusPacket_Handshake) isBusPacket_Payload() {}

func (*BusPacket_WorkerHandshakeChallengeRequest) isBusPacket_Payload() {}

func (*BusPacket_WorkerHandshakeChallenge) isBusPacket_Payload() {}

func (*BusPacket_WorkerHandshakeAuthenticate) isBusPacket_Payload() {}

func (*BusPacket_WorkerHandshakeResult) isBusPacket_Payload() {}

// SignatureMetadata binds a signature to one profile, packet identity,
// audience, validity window, and locally trusted key identifier.
type SignatureMetadata struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProfileVersion string                 `protobuf:"bytes,1,opt,name=profile_version,json=profileVersion,proto3" json:"profile_version,omitempty"`
	Algorithm      string                 `protobuf:"bytes,2,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	MessageId      []byte                 `protobuf:"bytes,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"` // exactly 16 unpredictable bytes
	Audience       string                 `protobuf:"bytes,4,opt,name=audience,proto3" json:"audience,omitempty"`
	ExpiresAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	KeyId          string                 `protobuf:"bytes,6,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SignatureMetadata) Reset() {
	*x = SignatureMetadata{}
	mi := &file_cordum_agent_v1_buspacket_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignatureMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignatureMetadata) ProtoMessage() {}

func (x *SignatureMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_cordum_agent_v1_buspacket_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignatureMetadata.ProtoReflect.Descriptor instead.
func (*SignatureMetadata) Descriptor() ([]byte, []int) {
	return file_cordum_agent_v1_buspacket_proto_rawDescGZIP(), []int{1}
}

func (x *SignatureMetadata) GetProfileVersion() string {
	if x != nil {
		return x.ProfileVersion
	}
	return ""
}

func (x *SignatureMetadata) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *SignatureMetadata) GetMessageId() []byte {
	if x != nil {
		return x.MessageId
	}
	return nil
}

func (x *SignatureMetadata) GetAudience() string {
	if x != nil {
		return x.Audience
	}
	return ""
}

func (x *SignatureMetadata) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *SignatureMetadata) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

var File_cordum_agent_v1_buspacket_proto protoreflect.FileDescriptor

const file_cordum_agent_v1_buspacket_proto_rawDesc = "" +
	"\n" +
	"\x1fcordum/agent/v1/buspacket.proto\x12\x0fcordum.agent.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19cordum/agent/v1/job.proto\x1a\x1fcordum/agent/v1/heartbeat.proto\x1a\x1bcordum/agent/v1/alert.proto\x1a\x1fcordum/agent/v1/handshake.proto\"\xf5\t\n" +
	"\tBusPacket\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\tR\bsenderId\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12)\n" +
	"\x10protocol_version\x18\x04 \x01(\x05R\x0fprotocolVersion\x12Q\n" +
	"\x12signature_metadata\x18\x05 \x01(\v2\".cordum.agent.v1.SignatureMetadataR\x11signatureMetadata\x12<\n" +
	"\bidentity\x18\x06 \x01(\v2 .cordum.agent.v1.IdentityBindingR\bidentity\x12>\n" +
	"\vjob_request\x18\n" +
	" \x01(\v2\x1b.cordum.agent.v1.JobRequestH\x00R\n" +
	"jobRequest\x12;\n" +
	"\n" +
	"job_result\x18\v \x01(\v2\x1a.cordum.agent.v1.JobResultH\x00R\tjobResult\x12:\n" +
	"\theartbeat\x18\f \x01(\v2\x1a.cordum.agent.v1.HeartbeatH\x00R\theartbeat\x124\n" +
	"\x05alert\x18\r \x01(\v2\x1c.cordum.agent.v1.SystemAlertH\x00R\x05alert\x12A\n" +
	"\fjob_progress\x18\x0f \x01(\v2\x1c.cordum.agent.v1.JobProgressH\x00R\vjobProgress\x12;\n" +
	"\n" +
	"job_cancel\x18\x10 \x01(\v2\x1a.cordum.agent.v1.JobCancelH\x00R\tjobCancel\x12:\n" +
	"\thandshake\x18\x11 \x01(\v2\x1a.cordum.agent.v1.HandshakeH\x00R\thandshake\x12\x7f\n" +
	"\"worker_handshake_challenge_request\x18\x13 \x01(\v20.cordum.agent.v1.WorkerHandshakeChallengeRequestH\x00R\x1fworkerHandshakeChallengeRequest\x12i\n" +
	"\x1aworker_handshake_challenge\x18\x14 \x01(\v2).cordum.agent.v1.WorkerHandshakeChallengeH\x00R\x18workerHandshakeChallenge\x12r\n" +
	"\x1dworker_handshake_authenticate\x18\x15 \x01(\v2,.cordum.agent.v1.WorkerHandshakeAuthenticateH\x00R\x1bworkerHandshakeAuthenticate\x12`\n" +
	"\x17worker_handshake_result\x18\x16 \x01(\v2&.cordum.agent.v1.WorkerHandshakeResultH\x00R\x15workerHandshakeResult\x12\x1c\n" +
	"\tsignature\x18\x0e \x01(\fR\tsignature\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x12 \x01(\tR\tauthTokenB\t\n" +
	"\apayloadJ\x04\b\x17\x10\x1c\"\xe7\x01\n" +
	"\x11SignatureMetadata\x12'\n" +
	"\x0fprofile_version\x18\x01 \x01(\tR\x0eprofileVersion\x12\x1c\n" +
	"\talgorithm\x18\x02 \x01(\tR\talgorithm\x12\x1d\n" +
	"\n" +
	"message_id\x18\x03 \x01(\fR\tmessageId\x12\x1a\n" +
	"\baudience\x18\x04 \x01(\tR\baudience\x129\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x15\n" +
	"\x06key_id\x18\x06 \x01(\tR\x05keyIdB\x7f\n" +
	"\x16io.cordum.cap.agent.v1P\x01Z+github.com/cordum-io/cap/v2/cordum/agent/v1\xaa\x02\x0fCordum.Agent.V1\xca\x02\x0fcordum\\Agent\\V1\xea\x02\x11Cordum::Agent::V1b\x06proto3"

var (
	file_cordum_agent_v1_buspacket_proto_rawDescOnce sync.Once
	file_cordum_agent_v1_buspacket_proto_rawDescData []byte
)

func file_cordum_agent_v1_buspacket_proto_rawDescGZIP() []byte {
	file_cordum_agent_v1_buspacket_proto_rawDescOnce.Do(func() {
		file_cordum_agent_v1_buspacket_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cordum_agent_v1_buspacket_proto_rawDesc), len(file_cordum_agent_v1_buspacket_proto_rawDesc)))
	})
	return file_cordum_agent_v1_buspacket_proto_rawDescData
}

var file_cordum_agent_v1_buspacket_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_cordum_agent_v1_buspacket_proto_goTypes = []any{
	(*BusPacket)(nil),                       // 0: cordum.agent.v1.BusPacket
	(*SignatureMetadata)(nil),               // 1: cordum.agent.v1.SignatureMetadata
	(*timestamppb.Timestamp)(nil),           // 2: google.protobuf.Timestamp
	(*IdentityBinding)(nil),                 // 3: cordum.agent.v1.IdentityBinding
	(*JobRequest)(nil),                      // 4: cordum.agent.v1.JobRequest
	(*JobResult)(nil),                       // 5: cordum.agent.v1.JobResult
	(*Heartbeat)(nil),                       // 6: cordum.agent.v1.Heartbeat
	(*SystemAlert)(nil),                     // 7: cordum.agent.v1.SystemAlert
	(*JobProgress)(nil),                     // 8: cordum.agent.v1.JobProgress
	(*JobCancel)(nil),                       // 9: cordum.agent.v1.JobCancel
	(*Handshake)(nil),                       // 10: cordum.agent.v1.Handshake
	(*WorkerHandshakeChallengeRequest)(nil), // 11: cordum.agent.v1.WorkerHandshakeChallengeRequest
	(*WorkerHandshakeChallenge)(nil),        // 12: cordum.agent.v1.WorkerHandshakeChallenge
	(*WorkerHandshakeAuthenticate)(nil),     // 13: cordum.agent.v1.WorkerHandshakeAuthenticate
	(*WorkerHandshakeResult)(nil),           // 14: cordum.agent.v1.WorkerHandshakeResult
}
var file_cordum_agent_v1_buspacket_proto_depIdxs = []int32{
	2,  // 0: cordum.agent.v1.BusPacket.created_at:type_name -> google.protobuf.Timestamp
	1,  // 1: cordum.agent.v1.BusPacket.signature_metadata:type_name -> cordum.agent.v1.SignatureMetadata
	3,  // 2: cordum.agent.v1.BusPacket.identity:type_name -> cordum.agent.v1.IdentityBinding
	4,  // 3: cordum.agent.v1.BusPacket.job_request:type_name -> cordum.agent.v1.JobRequest
	5,  // 4: cordum.agent.v1.BusPacket.job_result:type_name -> cordum.agent.v1.JobResult
	6,  // 5: cordum.agent.v1.BusPacket.heartbeat:type_name -> cordum.agent.v1.Heartbeat
	7,  // 6: cordum.agent.v1.BusPacket.alert:type_name -> cordum.agent.v1.SystemAlert
	8,  // 7: cordum.agent.v1.BusPacket.job_progress:type_name -> cordum.agent.v1.JobProgress
	9,  // 8: cordum.agent.v1.BusPacket.job_cancel:type_name -> cordum.agent.v1.JobCancel
	10, // 9: cordum.agent.v1.BusPacket.handshake:type_name -> cordum.agent.v1.Handshake
	11, // 10: cordum.agent.v1.BusPacket.worker_handshake_challenge_request:type_name -> cordum.agent.v1.WorkerHandshakeChallengeRequest
	12, // 11: cordum.agent.v1.BusPacket.worker_handshake_challenge:type_name -> cordum.agent.v1.WorkerHandshakeChallenge
	13, // 12: cordum.agent.v1.BusPacket.worker_handshake_authenticate:type_name -> cordum.agent.v1.WorkerHandshakeAuthenticate
	14, // 13: cordum.agent.v1.BusPacket.worker_handshake_result:type_name -> cordum.agent.v1.WorkerHandshakeResult
	2,  // 14: cordum.agent.v1.SignatureMetadata.expires_at:type_name -> google.protobuf.Timestamp
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_cordum_agent_v1_buspacket_proto_init() }
func file_cordum_agent_v1_buspacket_proto_init() {
	if File_cordum_agent_v1_buspacket_proto != nil {
		return
	}
	file_cordum_agent_v1_job_proto_init()
	file_cordum_agent_v1_heartbeat_proto_init()
	file_cordum_agent_v1_alert_proto_init()
	file_cordum_agent_v1_handshake_proto_init()
	file_cordum_agent_v1_buspacket_proto_msgTypes[0].OneofWrappers = []any{
		(*BusPacket_JobRequest)(nil),
		(*BusPacket_JobResult)(nil),
		(*BusPacket_Heartbeat)(nil),
		(*BusPacket_Alert)(nil),
		(*BusPacket_JobProgress)(nil),
		(*BusPacket_JobCancel)(nil),
		(*BusPacket_Handshake)(nil),
		(*BusPacket_WorkerHandshakeChallengeRequest)(nil),
		(*BusPacket_WorkerHandshakeChallenge)(nil),
		(*BusPacket_WorkerHandshakeAuthenticate)(nil),
		(*BusPacket_WorkerHandshakeResult)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cordum_agent_v1_buspacket_proto_rawDesc), len(file_cordum_agent_v1_buspacket_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cordum_agent_v1_buspacket_proto_goTypes,
		DependencyIndexes: file_cordum_agent_v1_buspacket_proto_depIdxs,
		MessageInfos:      file_cordum_agent_v1_buspacket_proto_msgTypes,
	}.Build()
	File_cordum_agent_v1_buspacket_proto = out.File
	file_cordum_agent_v1_buspacket_proto_goTypes = nil
	file_cordum_agent_v1_buspacket_proto_depIdxs = nil
}
