// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: cordum/agent/v1/handshake.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ComponentRole identifies the role of a component in the CAP topology.
type ComponentRole int32

const (
	ComponentRole_COMPONENT_ROLE_UNSPECIFIED  ComponentRole = 0
	ComponentRole_COMPONENT_ROLE_GATEWAY      ComponentRole = 1
	ComponentRole_COMPONENT_ROLE_SCHEDULER    ComponentRole = 2
	ComponentRole_COMPONENT_ROLE_WORKER       ComponentRole = 3
	ComponentRole_COMPONENT_ROLE_ORCHESTRATOR ComponentRole = 4
	ComponentRole_COMPONENT_ROLE_CONTROLLER   ComponentRole = 5
)

// Enum value maps for ComponentRole.
var (
	ComponentRole_name = map[int32]string{
		0: "COMPONENT_ROLE_UNSPECIFIED",
		1: "COMPONENT_ROLE_GATEWAY",
		2: "COMPONENT_ROLE_SCHEDULER",
		3: "COMPONENT_ROLE_WORKER",
		4: "COMPONENT_ROLE_ORCHESTRATOR",
		5: "COMPONENT_ROLE_CONTROLLER",
	}
	ComponentRole_value = map[string]int32{
		"COMPONENT_ROLE_UNSPECIFIED":  0,
		"COMPONENT_ROLE_GATEWAY":      1,
		"COMPONENT_ROLE_SCHEDULER":    2,
		"COMPONENT_ROLE_WORKER":       3,
		"COMPONENT_ROLE_ORCHESTRATOR": 4,
		"COMPONENT_ROLE_CONTROLLER":   5,
	}
)

func (x ComponentRole) Enum() *ComponentRole {
	p := new(ComponentRole)
	*p = x
	return p
}

func (x ComponentRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ComponentRole) Descriptor() protoreflect.EnumDescriptor {
	return file_cordum_agent_v1_handshake_proto_enumTypes[0].Descriptor()
}

func (ComponentRole) Type() protoreflect.EnumType {
	return &file_cordum_agent_v1_handshake_proto_enumTypes[0]
}

func (x ComponentRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ComponentRole.Descriptor instead.
func (ComponentRole) EnumDescriptor() ([]byte, []int) {
	return file_cordum_agent_v1_handshake_proto_rawDescGZIP(), []int{0}
}

// Handshake is published by components on connect to advertise their
// role, supported protocol versions, and capabilities.
type Handshake struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ComponentId       string                 `protobuf:"bytes,1,opt,name=component_id,json=componentId,proto3" json:"component_id,omitempty"`                                                           // unique ID of the connecting component
	Role              ComponentRole          `protobuf:"varint,2,opt,name=role,proto3,enum=cordum.agent.v1.ComponentRole" json:"role,omitempty"`                                                        // component's role
	SupportedVersions []int32                `protobuf:"varint,3,rep,packed,name=supported_versions,json=supportedVersions,proto3" json:"supported_versions,omitempty"`                                 // wire versions this component supports
	Capabilities      map[string]bool        `protobuf:"bytes,4,rep,name=capabilities,proto3" json:"capabilities,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // feature flags (signatures, compensation, progress, cancel, etc.)
	SdkVersion        string                 `protobuf:"bytes,5,opt,name=sdk_version,json=sdkVersion,proto3" json:"sdk_version,omitempty"`                                                              // optional SDK version string
	ReadyTopics       []string               `protobuf:"bytes,6,rep,name=ready_topics,json=readyTopics,proto3" json:"ready_topics,omitempty"`                                                           // topics this worker is ready to serve
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Handshake) Reset() {
	*x = Handshake{}
	mi := &file_cordum_agent_v1_handshake_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Handshake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Handshake) ProtoMessage() {}

func (x *Handshake) ProtoReflect() protoreflect.Message {
	mi := &file_cordum_agent_v1_handshake_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Handshake.ProtoReflect.Descriptor instead.
func (*Handshake) Descriptor() ([]byte, []int) {
	return file_cordum_agent_v1_handshake_proto_rawDescGZIP(), []int{0}
}

func (x *Handshake) GetComponentId() string {
	if x != nil {
		return x.ComponentId
	}
	return ""
}

func (x *Handshake) GetRole() ComponentRole {
	if x != nil {
		return x.Role
	}
	return ComponentRole_COMPONENT_ROLE_UNSPECIFIED
}

func (x *Handshake) GetSupportedVersions() []int32 {
	if x != nil {
		return x.SupportedVersions
	}
	return nil
}

func (x *Handshake) GetCapabilities() map[string]bool {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *Handshake) GetSdkVersion() string {
	if x != nil {
		return x.SdkVersion
	}
	return ""
}

func (x *Handshake) GetReadyTopics() []string {
	if x != nil {
		return x.ReadyTopics
	}
	return nil
}

var File_cordum_agent_v1_handshake_proto protoreflect.FileDescriptor

const file_cordum_agent_v1_handshake_proto_rawDesc = "" +
	"\n" +
	"\x1fcordum/agent/v1/handshake.proto\x12\x0fcordum.agent.v1\"\xe8\x02\n" +
	"\tHandshake\x12!\n" +
	"\fcomponent_id\x18\x01 \x01(\tR\vcomponentId\x122\n" +
	"\x04role\x18\x02 \x01(\x0e2\x1e.cordum.agent.v1.ComponentRoleR\x04role\x12-\n" +
	"\x12supported_versions\x18\x03 \x03(\x05R\x11supportedVersions\x12P\n" +
	"\fcapabilities\x18\x04 \x03(\v2,.cordum.agent.v1.Handshake.CapabilitiesEntryR\fcapabilities\x12\x1f\n" +
	"\vsdk_version\x18\x05 \x01(\tR\n" +
	"sdkVersion\x12!\n" +
	"\fready_topics\x18\x06 \x03(\tR\vreadyTopics\x1a?\n" +
	"\x11CapabilitiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01*\xc4\x01\n" +
	"\rComponentRole\x12\x1e\n" +
	"\x1aCOMPONENT_ROLE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16COMPONENT_ROLE_GATEWAY\x10\x01\x12\x1c\n" +
	"\x18COMPONENT_ROLE_SCHEDULER\x10\x02\x12\x19\n" +
	"\x15COMPONENT_ROLE_WORKER\x10\x03\x12\x1f\n" +
	"\x1bCOMPONENT_ROLE_ORCHESTRATOR\x10\x04\x12\x1d\n" +
	"\x19COMPONENT_ROLE_CONTROLLER\x10\x05B\x7f\n" +
	"\x16io.cordum.cap.agent.v1P\x01Z+github.com/cordum-io/cap/v2/cordum/agent/v1\xaa\x02\x0fCordum.Agent.V1\xca\x02\x0fcordum\\Agent\\V1\xea\x02\x11Cordum::Agent::V1b\x06proto3"

var (
	file_cordum_agent_v1_handshake_proto_rawDescOnce sync.Once
	file_cordum_agent_v1_handshake_proto_rawDescData []byte
)

func file_cordum_agent_v1_handshake_proto_rawDescGZIP() []byte {
	file_cordum_agent_v1_handshake_proto_rawDescOnce.Do(func() {
		file_cordum_agent_v1_handshake_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cordum_agent_v1_handshake_proto_rawDesc), len(file_cordum_agent_v1_handshake_proto_rawDesc)))
	})
	return file_cordum_agent_v1_handshake_proto_rawDescData
}

var file_cordum_agent_v1_handshake_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cordum_agent_v1_handshake_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_cordum_agent_v1_handshake_proto_goTypes = []any{
	(ComponentRole)(0), // 0: cordum.agent.v1.ComponentRole
	(*Handshake)(nil),  // 1: cordum.agent.v1.Handshake
	nil,                // 2: cordum.agent.v1.Handshake.CapabilitiesEntry
}
var file_cordum_agent_v1_handshake_proto_depIdxs = []int32{
	0, // 0: cordum.agent.v1.Handshake.role:type_name -> cordum.agent.v1.ComponentRole
	2, // 1: cordum.agent.v1.Handshake.capabilities:type_name -> cordum.agent.v1.Handshake.CapabilitiesEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_cordum_agent_v1_handshake_proto_init() }
func file_cordum_agent_v1_handshake_proto_init() {
	if File_cordum_agent_v1_handshake_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cordum_agent_v1_handshake_proto_rawDesc), len(file_cordum_agent_v1_handshake_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cordum_agent_v1_handshake_proto_goTypes,
		DependencyIndexes: file_cordum_agent_v1_handshake_proto_depIdxs,
		EnumInfos:         file_cordum_agent_v1_handshake_proto_enumTypes,
		MessageInfos:      file_cordum_agent_v1_handshake_proto_msgTypes,
	}.Build()
	File_cordum_agent_v1_handshake_proto = out.File
	file_cordum_agent_v1_handshake_proto_goTypes = nil
	file_cordum_agent_v1_handshake_proto_depIdxs = nil
}
