// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: cordum/agent/v1/handshake.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ComponentRole identifies the role of a component in the CAP topology.
type ComponentRole int32

const (
	ComponentRole_COMPONENT_ROLE_UNSPECIFIED  ComponentRole = 0
	ComponentRole_COMPONENT_ROLE_GATEWAY      ComponentRole = 1
	ComponentRole_COMPONENT_ROLE_SCHEDULER    ComponentRole = 2
	ComponentRole_COMPONENT_ROLE_WORKER       ComponentRole = 3
	ComponentRole_COMPONENT_ROLE_ORCHESTRATOR ComponentRole = 4
	ComponentRole_COMPONENT_ROLE_CONTROLLER   ComponentRole = 5
)

// Enum value maps for ComponentRole.
var (
	ComponentRole_name = map[int32]string{
		0: "COMPONENT_ROLE_UNSPECIFIED",
		1: "COMPONENT_ROLE_GATEWAY",
		2: "COMPONENT_ROLE_SCHEDULER",
		3: "COMPONENT_ROLE_WORKER",
		4: "COMPONENT_ROLE_ORCHESTRATOR",
		5: "COMPONENT_ROLE_CONTROLLER",
	}
	ComponentRole_value = map[string]int32{
		"COMPONENT_ROLE_UNSPECIFIED":  0,
		"COMPONENT_ROLE_GATEWAY":      1,
		"COMPONENT_ROLE_SCHEDULER":    2,
		"COMPONENT_ROLE_WORKER":       3,
		"COMPONENT_ROLE_ORCHESTRATOR": 4,
		"COMPONENT_ROLE_CONTROLLER":   5,
	}
)

func (x ComponentRole) Enum() *ComponentRole {
	p := new(ComponentRole)
	*p = x
	return p
}

func (x ComponentRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ComponentRole) Descriptor() protoreflect.EnumDescriptor {
	return file_cordum_agent_v1_handshake_proto_enumTypes[0].Descriptor()
}

func (ComponentRole) Type() protoreflect.EnumType {
	return &file_cordum_agent_v1_handshake_proto_enumTypes[0]
}

func (x ComponentRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ComponentRole.Descriptor instead.
func (ComponentRole) EnumDescriptor() ([]byte, []int) {
	return file_cordum_agent_v1_handshake_proto_rawDescGZIP(), []int{0}
}

// WorkerHandshakePurpose distinguishes initial session issue from renewal.
type WorkerHandshakePurpose int32

const (
	WorkerHandshakePurpose_WORKER_HANDSHAKE_PURPOSE_UNSPECIFIED WorkerHandshakePurpose = 0
	WorkerHandshakePurpose_WORKER_HANDSHAKE_PURPOSE_ISSUE       WorkerHandshakePurpose = 1
	WorkerHandshakePurpose_WORKER_HANDSHAKE_PURPOSE_RENEW       WorkerHandshakePurpose = 2
)

// Enum value maps for WorkerHandshakePurpose.
var (
	WorkerHandshakePurpose_name = map[int32]string{
		0: "WORKER_HANDSHAKE_PURPOSE_UNSPECIFIED",
		1: "WORKER_HANDSHAKE_PURPOSE_ISSUE",
		2: "WORKER_HANDSHAKE_PURPOSE_RENEW",
	}
	WorkerHandshakePurpose_value = map[string]int32{
		"WORKER_HANDSHAKE_PURPOSE_UNSPECIFIED": 0,
		"WORKER_HANDSHAKE_PURPOSE_ISSUE":       1,
		"WORKER_HANDSHAKE_PURPOSE_RENEW":       2,
	}
)

func (x WorkerHandshakePurpose) Enum() *WorkerHandshakePurpose {
	p := new(WorkerHandshakePurpose)
	*p = x
	return p
}

func (x WorkerHandshakePurpose) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkerHandshakePurpose) Descriptor() protoreflect.EnumDescriptor {
	return file_cordum_agent_v1_handshake_proto_enumTypes[1].Descriptor()
}

func (WorkerHandshakePurpose) Type() protoreflect.EnumType {
	return &file_cordum_agent_v1_handshake_proto_enumTypes[1]
}

func (x WorkerHandshakePurpose) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkerHandshakePurpose.Descriptor instead.
func (WorkerHandshakePurpose) EnumDescriptor() ([]byte, []int) {
	return file_cordum_agent_v1_handshake_proto_rawDescGZIP(), []int{1}
}

// WorkerHandshakeProofAlgorithm identifies the registered proof-key algorithm.
type WorkerHandshakeProofAlgorithm int32

const (
	WorkerHandshakeProofAlgorithm_WORKER_HANDSHAKE_PROOF_ALGORITHM_UNSPECIFIED       WorkerHandshakeProofAlgorithm = 0
	WorkerHandshakeProofAlgorithm_WORKER_HANDSHAKE_PROOF_ALGORITHM_ECDSA_P256_SHA256 WorkerHandshakeProofAlgorithm = 1
)

// Enum value maps for WorkerHandshakeProofAlgorithm.
var (
	WorkerHandshakeProofAlgorithm_name = map[int32]string{
		0: "WORKER_HANDSHAKE_PROOF_ALGORITHM_UNSPECIFIED",
		1: "WORKER_HANDSHAKE_PROOF_ALGORITHM_ECDSA_P256_SHA256",
	}
	WorkerHandshakeProofAlgorithm_value = map[string]int32{
		"WORKER_HANDSHAKE_PROOF_ALGORITHM_UNSPECIFIED":       0,
		"WORKER_HANDSHAKE_PROOF_ALGORITHM_ECDSA_P256_SHA256": 1,
	}
)

func (x WorkerHandshakeProofAlgorithm) Enum() *WorkerHandshakeProofAlgorithm {
	p := new(WorkerHandshakeProofAlgorithm)
	*p = x
	return p
}

func (x WorkerHandshakeProofAlgorithm) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkerHandshakeProofAlgorithm) Descriptor() protoreflect.EnumDescriptor {
	return file_cordum_agent_v1_handshake_proto_enumTypes[2].Descriptor()
}

func (WorkerHandshakeProofAlgorithm) Type() protoreflect.EnumType {
	return &file_cordum_agent_v1_handshake_proto_enumTypes[2]
}

func (x WorkerHandshakeProofAlgorithm) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkerHandshakeProofAlgorithm.Descriptor instead.
func (WorkerHandshakeProofAlgorithm) EnumDescriptor() ([]byte, []int) {
	return file_cordum_agent_v1_handshake_proto_rawDescGZIP(), []int{2}
}

// WorkerHandshakeRejectionReason is intentionally coarse to avoid identity oracles.
type WorkerHandshakeRejectionReason int32

const (
	WorkerHandshakeRejectionReason_WORKER_HANDSHAKE_REJECTION_REASON_UNSPECIFIED           WorkerHandshakeRejectionReason = 0
	WorkerHandshakeRejectionReason_WORKER_HANDSHAKE_REJECTION_REASON_INVALID_REQUEST       WorkerHandshakeRejectionReason = 1
	WorkerHandshakeRejectionReason_WORKER_HANDSHAKE_REJECTION_REASON_AUTHENTICATION_FAILED WorkerHandshakeRejectionReason = 2
	WorkerHandshakeRejectionReason_WORKER_HANDSHAKE_REJECTION_REASON_REPLAY_DETECTED       WorkerHandshakeRejectionReason = 3
	WorkerHandshakeRejectionReason_WORKER_HANDSHAKE_REJECTION_REASON_CLOCK_SKEW            WorkerHandshakeRejectionReason = 4
	WorkerHandshakeRejectionReason_WORKER_HANDSHAKE_REJECTION_REASON_CHALLENGE_EXPIRED     WorkerHandshakeRejectionReason = 5
	WorkerHandshakeRejectionReason_WORKER_HANDSHAKE_REJECTION_REASON_SESSION_REQUIRED      WorkerHandshakeRejectionReason = 6
	WorkerHandshakeRejectionReason_WORKER_HANDSHAKE_REJECTION_REASON_SESSION_INVALID       WorkerHandshakeRejectionReason = 7
	WorkerHandshakeRejectionReason_WORKER_HANDSHAKE_REJECTION_REASON_UNSUPPORTED_VERSION   WorkerHandshakeRejectionReason = 8
	WorkerHandshakeRejectionReason_WORKER_HANDSHAKE_REJECTION_REASON_INTERNAL_ERROR        WorkerHandshakeRejectionReason = 9
)

// Enum value maps for WorkerHandshakeRejectionReason.
var (
	WorkerHandshakeRejectionReason_name = map[int32]string{
		0: "WORKER_HANDSHAKE_REJECTION_REASON_UNSPECIFIED",
		1: "WORKER_HANDSHAKE_REJECTION_REASON_INVALID_REQUEST",
		2: "WORKER_HANDSHAKE_REJECTION_REASON_AUTHENTICATION_FAILED",
		3: "WORKER_HANDSHAKE_REJECTION_REASON_REPLAY_DETECTED",
		4: "WORKER_HANDSHAKE_REJECTION_REASON_CLOCK_SKEW",
		5: "WORKER_HANDSHAKE_REJECTION_REASON_CHALLENGE_EXPIRED",
		6: "WORKER_HANDSHAKE_REJECTION_REASON_SESSION_REQUIRED",
		7: "WORKER_HANDSHAKE_REJECTION_REASON_SESSION_INVALID",
		8: "WORKER_HANDSHAKE_REJECTION_REASON_UNSUPPORTED_VERSION",
		9: "WORKER_HANDSHAKE_REJECTION_REASON_INTERNAL_ERROR",
	}
	WorkerHandshakeRejectionReason_value = map[string]int32{
		"WORKER_HANDSHAKE_REJECTION_REASON_UNSPECIFIED":           0,
		"WORKER_HANDSHAKE_REJECTION_REASON_INVALID_REQUEST":       1,
		"WORKER_HANDSHAKE_REJECTION_REASON_AUTHENTICATION_FAILED": 2,
		"WORKER_HANDSHAKE_REJECTION_REASON_REPLAY_DETECTED":       3,
		"WORKER_HANDSHAKE_REJECTION_REASON_CLOCK_SKEW":            4,
		"WORKER_HANDSHAKE_REJECTION_REASON_CHALLENGE_EXPIRED":     5,
		"WORKER_HANDSHAKE_REJECTION_REASON_SESSION_REQUIRED":      6,
		"WORKER_HANDSHAKE_REJECTION_REASON_SESSION_INVALID":       7,
		"WORKER_HANDSHAKE_REJECTION_REASON_UNSUPPORTED_VERSION":   8,
		"WORKER_HANDSHAKE_REJECTION_REASON_INTERNAL_ERROR":        9,
	}
)

func (x WorkerHandshakeRejectionReason) Enum() *WorkerHandshakeRejectionReason {
	p := new(WorkerHandshakeRejectionReason)
	*p = x
	return p
}

func (x WorkerHandshakeRejectionReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkerHandshakeRejectionReason) Descriptor() protoreflect.EnumDescriptor {
	return file_cordum_agent_v1_handshake_proto_enumTypes[3].Descriptor()
}

func (WorkerHandshakeRejectionReason) Type() protoreflect.EnumType {
	return &file_cordum_agent_v1_handshake_proto_enumTypes[3]
}

func (x WorkerHandshakeRejectionReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkerHandshakeRejectionReason.Descriptor instead.
func (WorkerHandshakeRejectionReason) EnumDescriptor() ([]byte, []int) {
	return file_cordum_agent_v1_handshake_proto_rawDescGZIP(), []int{3}
}

// Handshake is published by components on connect to advertise their
// role, supported protocol versions, and capabilities.
type Handshake struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ComponentId       string                 `protobuf:"bytes,1,opt,name=component_id,json=componentId,proto3" json:"component_id,omitempty"`                                                           // unique ID of the connecting component
	Role              ComponentRole          `protobuf:"varint,2,opt,name=role,proto3,enum=cordum.agent.v1.ComponentRole" json:"role,omitempty"`                                                        // component's role
	SupportedVersions []int32                `protobuf:"varint,3,rep,packed,name=supported_versions,json=supportedVersions,proto3" json:"supported_versions,omitempty"`                                 // wire versions this component supports
	Capabilities      map[string]bool        `protobuf:"bytes,4,rep,name=capabilities,proto3" json:"capabilities,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // feature flags (signatures, compensation, progress, cancel, etc.)
	SdkVersion        string                 `protobuf:"bytes,5,opt,name=sdk_version,json=sdkVersion,proto3" json:"sdk_version,omitempty"`                                                              // optional SDK version string
	ReadyTopics       []string               `protobuf:"bytes,6,rep,name=ready_topics,json=readyTopics,proto3" json:"ready_topics,omitempty"`                                                           // topics this worker is ready to serve
	// agent_name is a human-facing DISPLAY label only; NOT an authentication authority.
	// Consumers MUST prefer authenticated identity records over this self-reported value.
	// Additive/append-only; safe to omit (old clients send empty).
	AgentName     string `protobuf:"bytes,7,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Handshake) Reset() {
	*x = Handshake{}
	mi := &file_cordum_agent_v1_handshake_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Handshake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Handshake) ProtoMessage() {}

func (x *Handshake) ProtoReflect() protoreflect.Message {
	mi := &file_cordum_agent_v1_handshake_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Handshake.ProtoReflect.Descriptor instead.
func (*Handshake) Descriptor() ([]byte, []int) {
	return file_cordum_agent_v1_handshake_proto_rawDescGZIP(), []int{0}
}

func (x *Handshake) GetComponentId() string {
	if x != nil {
		return x.ComponentId
	}
	return ""
}

func (x *Handshake) GetRole() ComponentRole {
	if x != nil {
		return x.Role
	}
	return ComponentRole_COMPONENT_ROLE_UNSPECIFIED
}

func (x *Handshake) GetSupportedVersions() []int32 {
	if x != nil {
		return x.SupportedVersions
	}
	return nil
}

func (x *Handshake) GetCapabilities() map[string]bool {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *Handshake) GetSdkVersion() string {
	if x != nil {
		return x.SdkVersion
	}
	return ""
}

func (x *Handshake) GetReadyTopics() []string {
	if x != nil {
		return x.ReadyTopics
	}
	return nil
}

func (x *Handshake) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

// WorkerHandshakeChallengeRequest asks the scheduler for a one-time challenge.
type WorkerHandshakeChallengeRequest struct {
	state           protoimpl.MessageState        `protogen:"open.v1"`
	RequestId       string                        `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	TraceId         string                        `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	WorkerId        string                        `protobuf:"bytes,3,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	ProofKeyId      string                        `protobuf:"bytes,4,opt,name=proof_key_id,json=proofKeyId,proto3" json:"proof_key_id,omitempty"`
	ProofAlgorithm  WorkerHandshakeProofAlgorithm `protobuf:"varint,5,opt,name=proof_algorithm,json=proofAlgorithm,proto3,enum=cordum.agent.v1.WorkerHandshakeProofAlgorithm" json:"proof_algorithm,omitempty"`
	Audience        string                        `protobuf:"bytes,6,opt,name=audience,proto3" json:"audience,omitempty"`
	Purpose         WorkerHandshakePurpose        `protobuf:"varint,7,opt,name=purpose,proto3,enum=cordum.agent.v1.WorkerHandshakePurpose" json:"purpose,omitempty"`
	ClientNonce     []byte                        `protobuf:"bytes,8,opt,name=client_nonce,json=clientNonce,proto3" json:"client_nonce,omitempty"`
	ProtocolVersion int32                         `protobuf:"varint,9,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	SdkVersion      string                        `protobuf:"bytes,10,opt,name=sdk_version,json=sdkVersion,proto3" json:"sdk_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WorkerHandshakeChallengeRequest) Reset() {
	*x = WorkerHandshakeChallengeRequest{}
	mi := &file_cordum_agent_v1_handshake_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerHandshakeChallengeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerHandshakeChallengeRequest) ProtoMessage() {}

func (x *WorkerHandshakeChallengeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cordum_agent_v1_handshake_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerHandshakeChallengeRequest.ProtoReflect.Descriptor instead.
func (*WorkerHandshakeChallengeRequest) Descriptor() ([]byte, []int) {
	return file_cordum_agent_v1_handshake_proto_rawDescGZIP(), []int{1}
}

func (x *WorkerHandshakeChallengeRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *WorkerHandshakeChallengeRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *WorkerHandshakeChallengeRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *WorkerHandshakeChallengeRequest) GetProofKeyId() string {
	if x != nil {
		return x.ProofKeyId
	}
	return ""
}

func (x *WorkerHandshakeChallengeRequest) GetProofAlgorithm() WorkerHandshakeProofAlgorithm {
	if x != nil {
		return x.ProofAlgorithm
	}
	return WorkerHandshakeProofAlgorithm_WORKER_HANDSHAKE_PROOF_ALGORITHM_UNSPECIFIED
}

func (x *WorkerHandshakeChallengeRequest) GetAudience() string {
	if x != nil {
		return x.Audience
	}
	return ""
}

func (x *WorkerHandshakeChallengeRequest) GetPurpose() WorkerHandshakePurpose {
	if x != nil {
		return x.Purpose
	}
	return WorkerHandshakePurpose_WORKER_HANDSHAKE_PURPOSE_UNSPECIFIED
}

func (x *WorkerHandshakeChallengeRequest) GetClientNonce() []byte {
	if x != nil {
		return x.ClientNonce
	}
	return nil
}

func (x *WorkerHandshakeChallengeRequest) GetProtocolVersion() int32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *WorkerHandshakeChallengeRequest) GetSdkVersion() string {
	if x != nil {
		return x.SdkVersion
	}
	return ""
}

// WorkerHandshakeChallenge binds authoritative identity to fresh client/server nonces.
type WorkerHandshakeChallenge struct {
	state           protoimpl.MessageState        `protogen:"open.v1"`
	RequestId       string                        `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ChallengeId     string                        `protobuf:"bytes,2,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
	TraceId         string                        `protobuf:"bytes,3,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	WorkerId        string                        `protobuf:"bytes,4,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	AgentId         string                        `protobuf:"bytes,5,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	TenantId        string                        `protobuf:"bytes,6,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ProofKeyId      string                        `protobuf:"bytes,7,opt,name=proof_key_id,json=proofKeyId,proto3" json:"proof_key_id,omitempty"`
	ProofAlgorithm  WorkerHandshakeProofAlgorithm `protobuf:"varint,8,opt,name=proof_algorithm,json=proofAlgorithm,proto3,enum=cordum.agent.v1.WorkerHandshakeProofAlgorithm" json:"proof_algorithm,omitempty"`
	ServerKeyId     string                        `protobuf:"bytes,9,opt,name=server_key_id,json=serverKeyId,proto3" json:"server_key_id,omitempty"`
	Audience        string                        `protobuf:"bytes,10,opt,name=audience,proto3" json:"audience,omitempty"`
	Purpose         WorkerHandshakePurpose        `protobuf:"varint,11,opt,name=purpose,proto3,enum=cordum.agent.v1.WorkerHandshakePurpose" json:"purpose,omitempty"`
	ClientNonce     []byte                        `protobuf:"bytes,12,opt,name=client_nonce,json=clientNonce,proto3" json:"client_nonce,omitempty"`
	ServerNonce     []byte                        `protobuf:"bytes,13,opt,name=server_nonce,json=serverNonce,proto3" json:"server_nonce,omitempty"`
	ProtocolVersion int32                         `protobuf:"varint,14,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	SdkVersion      string                        `protobuf:"bytes,15,opt,name=sdk_version,json=sdkVersion,proto3" json:"sdk_version,omitempty"`
	IssuedAt        *timestamppb.Timestamp        `protobuf:"bytes,16,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	ExpiresAt       *timestamppb.Timestamp        `protobuf:"bytes,17,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WorkerHandshakeChallenge) Reset() {
	*x = WorkerHandshakeChallenge{}
	mi := &file_cordum_agent_v1_handshake_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerHandshakeChallenge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerHandshakeChallenge) ProtoMessage() {}

func (x *WorkerHandshakeChallenge) ProtoReflect() protoreflect.Message {
	mi := &file_cordum_agent_v1_handshake_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerHandshakeChallenge.ProtoReflect.Descriptor instead.
func (*WorkerHandshakeChallenge) Descriptor() ([]byte, []int) {
	return file_cordum_agent_v1_handshake_proto_rawDescGZIP(), []int{2}
}

func (x *WorkerHandshakeChallenge) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *WorkerHandshakeChallenge) GetChallengeId() string {
	if x != nil {
		return x.ChallengeId
	}
	return ""
}

func (x *WorkerHandshakeChallenge) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *WorkerHandshakeChallenge) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *WorkerHandshakeChallenge) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *WorkerHandshakeChallenge) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *WorkerHandshakeChallenge) GetProofKeyId() string {
	if x != nil {
		return x.ProofKeyId
	}
	return ""
}

func (x *WorkerHandshakeChallenge) GetProofAlgorithm() WorkerHandshakeProofAlgorithm {
	if x != nil {
		return x.ProofAlgorithm
	}
	return WorkerHandshakeProofAlgorithm_WORKER_HANDSHAKE_PROOF_ALGORITHM_UNSPECIFIED
}

func (x *WorkerHandshakeChallenge) GetServerKeyId() string {
	if x != nil {
		return x.ServerKeyId
	}
	return ""
}

func (x *WorkerHandshakeChallenge) GetAudience() string {
	if x != nil {
		return x.Audience
	}
	return ""
}

func (x *WorkerHandshakeChallenge) GetPurpose() WorkerHandshakePurpose {
	if x != nil {
		return x.Purpose
	}
	return WorkerHandshakePurpose_WORKER_HANDSHAKE_PURPOSE_UNSPECIFIED
}

func (x *WorkerHandshakeChallenge) GetClientNonce() []byte {
	if x != nil {
		return x.ClientNonce
	}
	return nil
}

func (x *WorkerHandshakeChallenge) GetServerNonce() []byte {
	if x != nil {
		return x.ServerNonce
	}
	return nil
}

func (x *WorkerHandshakeChallenge) GetProtocolVersion() int32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *WorkerHandshakeChallenge) GetSdkVersion() string {
	if x != nil {
		return x.SdkVersion
	}
	return ""
}

func (x *WorkerHandshakeChallenge) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

func (x *WorkerHandshakeChallenge) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

// WorkerHandshakeAuthenticate proves possession and advertises capabilities.
type WorkerHandshakeAuthenticate struct {
	state               protoimpl.MessageState    `protogen:"open.v1"`
	Challenge           *WorkerHandshakeChallenge `protobuf:"bytes,1,opt,name=challenge,proto3" json:"challenge,omitempty"`
	CapabilityHandshake *Handshake                `protobuf:"bytes,2,opt,name=capability_handshake,json=capabilityHandshake,proto3" json:"capability_handshake,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *WorkerHandshakeAuthenticate) Reset() {
	*x = WorkerHandshakeAuthenticate{}
	mi := &file_cordum_agent_v1_handshake_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerHandshakeAuthenticate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerHandshakeAuthenticate) ProtoMessage() {}

func (x *WorkerHandshakeAuthenticate) ProtoReflect() protoreflect.Message {
	mi := &file_cordum_agent_v1_handshake_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerHandshakeAuthenticate.ProtoReflect.Descriptor instead.
func (*WorkerHandshakeAuthenticate) Descriptor() ([]byte, []int) {
	return file_cordum_agent_v1_handshake_proto_rawDescGZIP(), []int{3}
}

func (x *WorkerHandshakeAuthenticate) GetChallenge() *WorkerHandshakeChallenge {
	if x != nil {
		return x.Challenge
	}
	return nil
}

func (x *WorkerHandshakeAuthenticate) GetCapabilityHandshake() *Handshake {
	if x != nil {
		return x.CapabilityHandshake
	}
	return nil
}

// WorkerHandshakeResult returns an opaque rejection or token metadata; an
// accepted result carries the signed session token in BusPacket.auth_token.
type WorkerHandshakeResult struct {
	state           protoimpl.MessageState         `protogen:"open.v1"`
	Challenge       *WorkerHandshakeChallenge      `protobuf:"bytes,1,opt,name=challenge,proto3" json:"challenge,omitempty"`
	Accepted        bool                           `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	RejectionReason WorkerHandshakeRejectionReason `protobuf:"varint,3,opt,name=rejection_reason,json=rejectionReason,proto3,enum=cordum.agent.v1.WorkerHandshakeRejectionReason" json:"rejection_reason,omitempty"`
	TokenExpiresAt  *timestamppb.Timestamp         `protobuf:"bytes,4,opt,name=token_expires_at,json=tokenExpiresAt,proto3" json:"token_expires_at,omitempty"`
	IssuedAt        *timestamppb.Timestamp         `protobuf:"bytes,5,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WorkerHandshakeResult) Reset() {
	*x = WorkerHandshakeResult{}
	mi := &file_cordum_agent_v1_handshake_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerHandshakeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerHandshakeResult) ProtoMessage() {}

func (x *WorkerHandshakeResult) ProtoReflect() protoreflect.Message {
	mi := &file_cordum_agent_v1_handshake_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerHandshakeResult.ProtoReflect.Descriptor instead.
func (*WorkerHandshakeResult) Descriptor() ([]byte, []int) {
	return file_cordum_agent_v1_handshake_proto_rawDescGZIP(), []int{4}
}

func (x *WorkerHandshakeResult) GetChallenge() *WorkerHandshakeChallenge {
	if x != nil {
		return x.Challenge
	}
	return nil
}

func (x *WorkerHandshakeResult) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *WorkerHandshakeResult) GetRejectionReason() WorkerHandshakeRejectionReason {
	if x != nil {
		return x.RejectionReason
	}
	return WorkerHandshakeRejectionReason_WORKER_HANDSHAKE_REJECTION_REASON_UNSPECIFIED
}

func (x *WorkerHandshakeResult) GetTokenExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TokenExpiresAt
	}
	return nil
}

func (x *WorkerHandshakeResult) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

var File_cordum_agent_v1_handshake_proto protoreflect.FileDescriptor

const file_cordum_agent_v1_handshake_proto_rawDesc = "" +
	"\n" +
	"\x1fcordum/agent/v1/handshake.proto\x12\x0fcordum.agent.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x87\x03\n" +
	"\tHandshake\x12!\n" +
	"\fcomponent_id\x18\x01 \x01(\tR\vcomponentId\x122\n" +
	"\x04role\x18\x02 \x01(\x0e2\x1e.cordum.agent.v1.ComponentRoleR\x04role\x12-\n" +
	"\x12supported_versions\x18\x03 \x03(\x05R\x11supportedVersions\x12P\n" +
	"\fcapabilities\x18\x04 \x03(\v2,.cordum.agent.v1.Handshake.CapabilitiesEntryR\fcapabilities\x12\x1f\n" +
	"\vsdk_version\x18\x05 \x01(\tR\n" +
	"sdkVersion\x12!\n" +
	"\fready_topics\x18\x06 \x03(\tR\vreadyTopics\x12\x1d\n" +
	"\n" +
	"agent_name\x18\a \x01(\tR\tagentName\x1a?\n" +
	"\x11CapabilitiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\"\xc1\x03\n" +
	"\x1fWorkerHandshakeChallengeRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x19\n" +
	"\btrace_id\x18\x02 \x01(\tR\atraceId\x12\x1b\n" +
	"\tworker_id\x18\x03 \x01(\tR\bworkerId\x12 \n" +
	"\fproof_key_id\x18\x04 \x01(\tR\n" +
	"proofKeyId\x12W\n" +
	"\x0fproof_algorithm\x18\x05 \x01(\x0e2..cordum.agent.v1.WorkerHandshakeProofAlgorithmR\x0eproofAlgorithm\x12\x1a\n" +
	"\baudience\x18\x06 \x01(\tR\baudience\x12A\n" +
	"\apurpose\x18\a \x01(\x0e2'.cordum.agent.v1.WorkerHandshakePurposeR\apurpose\x12!\n" +
	"\fclient_nonce\x18\b \x01(\fR\vclientNonce\x12)\n" +
	"\x10protocol_version\x18\t \x01(\x05R\x0fprotocolVersion\x12\x1f\n" +
	"\vsdk_version\x18\n" +
	" \x01(\tR\n" +
	"sdkVersion\"\xd0\x05\n" +
	"\x18WorkerHandshakeChallenge\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12!\n" +
	"\fchallenge_id\x18\x02 \x01(\tR\vchallengeId\x12\x19\n" +
	"\btrace_id\x18\x03 \x01(\tR\atraceId\x12\x1b\n" +
	"\tworker_id\x18\x04 \x01(\tR\bworkerId\x12\x19\n" +
	"\bagent_id\x18\x05 \x01(\tR\aagentId\x12\x1b\n" +
	"\ttenant_id\x18\x06 \x01(\tR\btenantId\x12 \n" +
	"\fproof_key_id\x18\a \x01(\tR\n" +
	"proofKeyId\x12W\n" +
	"\x0fproof_algorithm\x18\b \x01(\x0e2..cordum.agent.v1.WorkerHandshakeProofAlgorithmR\x0eproofAlgorithm\x12\"\n" +
	"\rserver_key_id\x18\t \x01(\tR\vserverKeyId\x12\x1a\n" +
	"\baudience\x18\n" +
	" \x01(\tR\baudience\x12A\n" +
	"\apurpose\x18\v \x01(\x0e2'.cordum.agent.v1.WorkerHandshakePurposeR\apurpose\x12!\n" +
	"\fclient_nonce\x18\f \x01(\fR\vclientNonce\x12!\n" +
	"\fserver_nonce\x18\r \x01(\fR\vserverNonce\x12)\n" +
	"\x10protocol_version\x18\x0e \x01(\x05R\x0fprotocolVersion\x12\x1f\n" +
	"\vsdk_version\x18\x0f \x01(\tR\n" +
	"sdkVersion\x127\n" +
	"\tissued_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\bissuedAt\x129\n" +
	"\n" +
	"expires_at\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\xb5\x01\n" +
	"\x1bWorkerHandshakeAuthenticate\x12G\n" +
	"\tchallenge\x18\x01 \x01(\v2).cordum.agent.v1.WorkerHandshakeChallengeR\tchallenge\x12M\n" +
	"\x14capability_handshake\x18\x02 \x01(\v2\x1a.cordum.agent.v1.HandshakeR\x13capabilityHandshake\"\xd7\x02\n" +
	"\x15WorkerHandshakeResult\x12G\n" +
	"\tchallenge\x18\x01 \x01(\v2).cordum.agent.v1.WorkerHandshakeChallengeR\tchallenge\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\x12Z\n" +
	"\x10rejection_reason\x18\x03 \x01(\x0e2/.cordum.agent.v1.WorkerHandshakeRejectionReasonR\x0frejectionReason\x12D\n" +
	"\x10token_expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x0etokenExpiresAt\x127\n" +
	"\tissued_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bissuedAt*\xc4\x01\n" +
	"\rComponentRole\x12\x1e\n" +
	"\x1aCOMPONENT_ROLE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16COMPONENT_ROLE_GATEWAY\x10\x01\x12\x1c\n" +
	"\x18COMPONENT_ROLE_SCHEDULER\x10\x02\x12\x19\n" +
	"\x15COMPONENT_ROLE_WORKER\x10\x03\x12\x1f\n" +
	"\x1bCOMPONENT_ROLE_ORCHESTRATOR\x10\x04\x12\x1d\n" +
	"\x19COMPONENT_ROLE_CONTROLLER\x10\x05*\x8a\x01\n" +
	"\x16WorkerHandshakePurpose\x12(\n" +
	"$WORKER_HANDSHAKE_PURPOSE_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eWORKER_HANDSHAKE_PURPOSE_ISSUE\x10\x01\x12\"\n" +
	"\x1eWORKER_HANDSHAKE_PURPOSE_RENEW\x10\x02*\x89\x01\n" +
	"\x1dWorkerHandshakeProofAlgorithm\x120\n" +
	",WORKER_HANDSHAKE_PROOF_ALGORITHM_UNSPECIFIED\x10\x00\x126\n" +
	"2WORKER_HANDSHAKE_PROOF_ALGORITHM_ECDSA_P256_SHA256\x10\x01*\xc9\x04\n" +
	"\x1eWorkerHandshakeRejectionReason\x121\n" +
	"-WORKER_HANDSHAKE_REJECTION_REASON_UNSPECIFIED\x10\x00\x125\n" +
	"1WORKER_HANDSHAKE_REJECTION_REASON_INVALID_REQUEST\x10\x01\x12;\n" +
	"7WORKER_HANDSHAKE_REJECTION_REASON_AUTHENTICATION_FAILED\x10\x02\x125\n" +
	"1WORKER_HANDSHAKE_REJECTION_REASON_REPLAY_DETECTED\x10\x03\x120\n" +
	",WORKER_HANDSHAKE_REJECTION_REASON_CLOCK_SKEW\x10\x04\x127\n" +
	"3WORKER_HANDSHAKE_REJECTION_REASON_CHALLENGE_EXPIRED\x10\x05\x126\n" +
	"2WORKER_HANDSHAKE_REJECTION_REASON_SESSION_REQUIRED\x10\x06\x125\n" +
	"1WORKER_HANDSHAKE_REJECTION_REASON_SESSION_INVALID\x10\a\x129\n" +
	"5WORKER_HANDSHAKE_REJECTION_REASON_UNSUPPORTED_VERSION\x10\b\x124\n" +
	"0WORKER_HANDSHAKE_REJECTION_REASON_INTERNAL_ERROR\x10\tB\x7f\n" +
	"\x16io.cordum.cap.agent.v1P\x01Z+github.com/cordum-io/cap/v2/cordum/agent/v1\xaa\x02\x0fCordum.Agent.V1\xca\x02\x0fcordum\\Agent\\V1\xea\x02\x11Cordum::Agent::V1b\x06proto3"

var (
	file_cordum_agent_v1_handshake_proto_rawDescOnce sync.Once
	file_cordum_agent_v1_handshake_proto_rawDescData []byte
)

func file_cordum_agent_v1_handshake_proto_rawDescGZIP() []byte {
	file_cordum_agent_v1_handshake_proto_rawDescOnce.Do(func() {
		file_cordum_agent_v1_handshake_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cordum_agent_v1_handshake_proto_rawDesc), len(file_cordum_agent_v1_handshake_proto_rawDesc)))
	})
	return file_cordum_agent_v1_handshake_proto_rawDescData
}

var file_cordum_agent_v1_handshake_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_cordum_agent_v1_handshake_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_cordum_agent_v1_handshake_proto_goTypes = []any{
	(ComponentRole)(0),                      // 0: cordum.agent.v1.ComponentRole
	(WorkerHandshakePurpose)(0),             // 1: cordum.agent.v1.WorkerHandshakePurpose
	(WorkerHandshakeProofAlgorithm)(0),      // 2: cordum.agent.v1.WorkerHandshakeProofAlgorithm
	(WorkerHandshakeRejectionReason)(0),     // 3: cordum.agent.v1.WorkerHandshakeRejectionReason
	(*Handshake)(nil),                       // 4: cordum.agent.v1.Handshake
	(*WorkerHandshakeChallengeRequest)(nil), // 5: cordum.agent.v1.WorkerHandshakeChallengeRequest
	(*WorkerHandshakeChallenge)(nil),        // 6: cordum.agent.v1.WorkerHandshakeChallenge
	(*WorkerHandshakeAuthenticate)(nil),     // 7: cordum.agent.v1.WorkerHandshakeAuthenticate
	(*WorkerHandshakeResult)(nil),           // 8: cordum.agent.v1.WorkerHandshakeResult
	nil,                                     // 9: cordum.agent.v1.Handshake.CapabilitiesEntry
	(*timestamppb.Timestamp)(nil),           // 10: google.protobuf.Timestamp
}
var file_cordum_agent_v1_handshake_proto_depIdxs = []int32{
	0,  // 0: cordum.agent.v1.Handshake.role:type_name -> cordum.agent.v1.ComponentRole
	9,  // 1: cordum.agent.v1.Handshake.capabilities:type_name -> cordum.agent.v1.Handshake.CapabilitiesEntry
	2,  // 2: cordum.agent.v1.WorkerHandshakeChallengeRequest.proof_algorithm:type_name -> cordum.agent.v1.WorkerHandshakeProofAlgorithm
	1,  // 3: cordum.agent.v1.WorkerHandshakeChallengeRequest.purpose:type_name -> cordum.agent.v1.WorkerHandshakePurpose
	2,  // 4: cordum.agent.v1.WorkerHandshakeChallenge.proof_algorithm:type_name -> cordum.agent.v1.WorkerHandshakeProofAlgorithm
	1,  // 5: cordum.agent.v1.WorkerHandshakeChallenge.purpose:type_name -> cordum.agent.v1.WorkerHandshakePurpose
	10, // 6: cordum.agent.v1.WorkerHandshakeChallenge.issued_at:type_name -> google.protobuf.Timestamp
	10, // 7: cordum.agent.v1.WorkerHandshakeChallenge.expires_at:type_name -> google.protobuf.Timestamp
	6,  // 8: cordum.agent.v1.WorkerHandshakeAuthenticate.challenge:type_name -> cordum.agent.v1.WorkerHandshakeChallenge
	4,  // 9: cordum.agent.v1.WorkerHandshakeAuthenticate.capability_handshake:type_name -> cordum.agent.v1.Handshake
	6,  // 10: cordum.agent.v1.WorkerHandshakeResult.challenge:type_name -> cordum.agent.v1.WorkerHandshakeChallenge
	3,  // 11: cordum.agent.v1.WorkerHandshakeResult.rejection_reason:type_name -> cordum.agent.v1.WorkerHandshakeRejectionReason
	10, // 12: cordum.agent.v1.WorkerHandshakeResult.token_expires_at:type_name -> google.protobuf.Timestamp
	10, // 13: cordum.agent.v1.WorkerHandshakeResult.issued_at:type_name -> google.protobuf.Timestamp
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_cordum_agent_v1_handshake_proto_init() }
func file_cordum_agent_v1_handshake_proto_init() {
	if File_cordum_agent_v1_handshake_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cordum_agent_v1_handshake_proto_rawDesc), len(file_cordum_agent_v1_handshake_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cordum_agent_v1_handshake_proto_goTypes,
		DependencyIndexes: file_cordum_agent_v1_handshake_proto_depIdxs,
		EnumInfos:         file_cordum_agent_v1_handshake_proto_enumTypes,
		MessageInfos:      file_cordum_agent_v1_handshake_proto_msgTypes,
	}.Build()
	File_cordum_agent_v1_handshake_proto = out.File
	file_cordum_agent_v1_handshake_proto_goTypes = nil
	file_cordum_agent_v1_handshake_proto_depIdxs = nil
}
