// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: cordum/agent/v1/policy.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PolicyEvaluator_EvaluateUnified_FullMethodName = "/cordum.agent.v1.PolicyEvaluator/EvaluateUnified"
)

// PolicyEvaluatorClient is the client API for PolicyEvaluator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PolicyEvaluator exposes the unified job + edge policy entry-point over gRPC.
type PolicyEvaluatorClient interface {
	EvaluateUnified(ctx context.Context, in *PolicyEvaluateRequest, opts ...grpc.CallOption) (*PolicyEvaluateResponse, error)
}

type policyEvaluatorClient struct {
	cc grpc.ClientConnInterface
}

func NewPolicyEvaluatorClient(cc grpc.ClientConnInterface) PolicyEvaluatorClient {
	return &policyEvaluatorClient{cc}
}

func (c *policyEvaluatorClient) EvaluateUnified(ctx context.Context, in *PolicyEvaluateRequest, opts ...grpc.CallOption) (*PolicyEvaluateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PolicyEvaluateResponse)
	err := c.cc.Invoke(ctx, PolicyEvaluator_EvaluateUnified_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PolicyEvaluatorServer is the server API for PolicyEvaluator service.
// All implementations must embed UnimplementedPolicyEvaluatorServer
// for forward compatibility.
//
// PolicyEvaluator exposes the unified job + edge policy entry-point over gRPC.
type PolicyEvaluatorServer interface {
	EvaluateUnified(context.Context, *PolicyEvaluateRequest) (*PolicyEvaluateResponse, error)
	mustEmbedUnimplementedPolicyEvaluatorServer()
}

// UnimplementedPolicyEvaluatorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPolicyEvaluatorServer struct{}

func (UnimplementedPolicyEvaluatorServer) EvaluateUnified(context.Context, *PolicyEvaluateRequest) (*PolicyEvaluateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EvaluateUnified not implemented")
}
func (UnimplementedPolicyEvaluatorServer) mustEmbedUnimplementedPolicyEvaluatorServer() {}
func (UnimplementedPolicyEvaluatorServer) testEmbeddedByValue()                         {}

// UnsafePolicyEvaluatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PolicyEvaluatorServer will
// result in compilation errors.
type UnsafePolicyEvaluatorServer interface {
	mustEmbedUnimplementedPolicyEvaluatorServer()
}

func RegisterPolicyEvaluatorServer(s grpc.ServiceRegistrar, srv PolicyEvaluatorServer) {
	// If the following call panics, it indicates UnimplementedPolicyEvaluatorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PolicyEvaluator_ServiceDesc, srv)
}

func _PolicyEvaluator_EvaluateUnified_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PolicyEvaluateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyEvaluatorServer).EvaluateUnified(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolicyEvaluator_EvaluateUnified_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyEvaluatorServer).EvaluateUnified(ctx, req.(*PolicyEvaluateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PolicyEvaluator_ServiceDesc is the grpc.ServiceDesc for PolicyEvaluator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PolicyEvaluator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cordum.agent.v1.PolicyEvaluator",
	HandlerType: (*PolicyEvaluatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EvaluateUnified",
			Handler:    _PolicyEvaluator_EvaluateUnified_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cordum/agent/v1/policy.proto",
}
