// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: cordum/agent/v1/policy.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RuleType discriminates a rule's match/decide payload schema.
type RuleType int32

const (
	RuleType_RULE_TYPE_UNSPECIFIED RuleType = 0
	RuleType_RULE_TYPE_INPUT       RuleType = 1
	RuleType_RULE_TYPE_OUTPUT      RuleType = 2
	RuleType_RULE_TYPE_VELOCITY    RuleType = 3
	RuleType_RULE_TYPE_EDGE        RuleType = 4
)

// Enum value maps for RuleType.
var (
	RuleType_name = map[int32]string{
		0: "RULE_TYPE_UNSPECIFIED",
		1: "RULE_TYPE_INPUT",
		2: "RULE_TYPE_OUTPUT",
		3: "RULE_TYPE_VELOCITY",
		4: "RULE_TYPE_EDGE",
	}
	RuleType_value = map[string]int32{
		"RULE_TYPE_UNSPECIFIED": 0,
		"RULE_TYPE_INPUT":       1,
		"RULE_TYPE_OUTPUT":      2,
		"RULE_TYPE_VELOCITY":    3,
		"RULE_TYPE_EDGE":        4,
	}
)

func (x RuleType) Enum() *RuleType {
	p := new(RuleType)
	*p = x
	return p
}

func (x RuleType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RuleType) Descriptor() protoreflect.EnumDescriptor {
	return file_cordum_agent_v1_policy_proto_enumTypes[0].Descriptor()
}

func (RuleType) Type() protoreflect.EnumType {
	return &file_cordum_agent_v1_policy_proto_enumTypes[0]
}

func (x RuleType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RuleType.Descriptor instead.
func (RuleType) EnumDescriptor() ([]byte, []int) {
	return file_cordum_agent_v1_policy_proto_rawDescGZIP(), []int{0}
}

// RuleStatus tracks a rule's lifecycle state. Authors edit drafts; published
// rules participate in evaluation; deprecated rules remain queryable for
// audit and rollback but are skipped by evaluators.
type RuleStatus int32

const (
	RuleStatus_RULE_STATUS_UNSPECIFIED RuleStatus = 0
	RuleStatus_RULE_STATUS_DRAFT       RuleStatus = 1
	RuleStatus_RULE_STATUS_PUBLISHED   RuleStatus = 2
	RuleStatus_RULE_STATUS_DEPRECATED  RuleStatus = 3
)

// Enum value maps for RuleStatus.
var (
	RuleStatus_name = map[int32]string{
		0: "RULE_STATUS_UNSPECIFIED",
		1: "RULE_STATUS_DRAFT",
		2: "RULE_STATUS_PUBLISHED",
		3: "RULE_STATUS_DEPRECATED",
	}
	RuleStatus_value = map[string]int32{
		"RULE_STATUS_UNSPECIFIED": 0,
		"RULE_STATUS_DRAFT":       1,
		"RULE_STATUS_PUBLISHED":   2,
		"RULE_STATUS_DEPRECATED":  3,
	}
)

func (x RuleStatus) Enum() *RuleStatus {
	p := new(RuleStatus)
	*p = x
	return p
}

func (x RuleStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RuleStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_cordum_agent_v1_policy_proto_enumTypes[1].Descriptor()
}

func (RuleStatus) Type() protoreflect.EnumType {
	return &file_cordum_agent_v1_policy_proto_enumTypes[1]
}

func (x RuleStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RuleStatus.Descriptor instead.
func (RuleStatus) EnumDescriptor() ([]byte, []int) {
	return file_cordum_agent_v1_policy_proto_rawDescGZIP(), []int{1}
}

// DecisionSource identifies which evaluator produced a Decision: the
// safetykernel job pipeline (JOB) or the edge classifier path (EDGE).
type DecisionSource int32

const (
	DecisionSource_DECISION_SOURCE_UNSPECIFIED DecisionSource = 0
	DecisionSource_DECISION_SOURCE_JOB         DecisionSource = 1
	DecisionSource_DECISION_SOURCE_EDGE        DecisionSource = 2
)

// Enum value maps for DecisionSource.
var (
	DecisionSource_name = map[int32]string{
		0: "DECISION_SOURCE_UNSPECIFIED",
		1: "DECISION_SOURCE_JOB",
		2: "DECISION_SOURCE_EDGE",
	}
	DecisionSource_value = map[string]int32{
		"DECISION_SOURCE_UNSPECIFIED": 0,
		"DECISION_SOURCE_JOB":         1,
		"DECISION_SOURCE_EDGE":        2,
	}
)

func (x DecisionSource) Enum() *DecisionSource {
	p := new(DecisionSource)
	*p = x
	return p
}

func (x DecisionSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DecisionSource) Descriptor() protoreflect.EnumDescriptor {
	return file_cordum_agent_v1_policy_proto_enumTypes[2].Descriptor()
}

func (DecisionSource) Type() protoreflect.EnumType {
	return &file_cordum_agent_v1_policy_proto_enumTypes[2]
}

func (x DecisionSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DecisionSource.Descriptor instead.
func (DecisionSource) EnumDescriptor() ([]byte, []int) {
	return file_cordum_agent_v1_policy_proto_rawDescGZIP(), []int{2}
}

// RuleScopeKind narrows where a rule (or bundle) applies.
type RuleScopeKind int32

const (
	RuleScopeKind_RULE_SCOPE_KIND_UNSPECIFIED RuleScopeKind = 0
	RuleScopeKind_RULE_SCOPE_KIND_GLOBAL      RuleScopeKind = 1
	RuleScopeKind_RULE_SCOPE_KIND_TENANT      RuleScopeKind = 2
	RuleScopeKind_RULE_SCOPE_KIND_WORKFLOW    RuleScopeKind = 3
	RuleScopeKind_RULE_SCOPE_KIND_EDGE_FLEET  RuleScopeKind = 4
	RuleScopeKind_RULE_SCOPE_KIND_EDGE_USER   RuleScopeKind = 5
)

// Enum value maps for RuleScopeKind.
var (
	RuleScopeKind_name = map[int32]string{
		0: "RULE_SCOPE_KIND_UNSPECIFIED",
		1: "RULE_SCOPE_KIND_GLOBAL",
		2: "RULE_SCOPE_KIND_TENANT",
		3: "RULE_SCOPE_KIND_WORKFLOW",
		4: "RULE_SCOPE_KIND_EDGE_FLEET",
		5: "RULE_SCOPE_KIND_EDGE_USER",
	}
	RuleScopeKind_value = map[string]int32{
		"RULE_SCOPE_KIND_UNSPECIFIED": 0,
		"RULE_SCOPE_KIND_GLOBAL":      1,
		"RULE_SCOPE_KIND_TENANT":      2,
		"RULE_SCOPE_KIND_WORKFLOW":    3,
		"RULE_SCOPE_KIND_EDGE_FLEET":  4,
		"RULE_SCOPE_KIND_EDGE_USER":   5,
	}
)

func (x RuleScopeKind) Enum() *RuleScopeKind {
	p := new(RuleScopeKind)
	*p = x
	return p
}

func (x RuleScopeKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RuleScopeKind) Descriptor() protoreflect.EnumDescriptor {
	return file_cordum_agent_v1_policy_proto_enumTypes[3].Descriptor()
}

func (RuleScopeKind) Type() protoreflect.EnumType {
	return &file_cordum_agent_v1_policy_proto_enumTypes[3]
}

func (x RuleScopeKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RuleScopeKind.Descriptor instead.
func (RuleScopeKind) EnumDescriptor() ([]byte, []int) {
	return file_cordum_agent_v1_policy_proto_rawDescGZIP(), []int{3}
}

// EdgeMode is the per-bundle enforcement posture for the edge evaluator,
// migrating the legacy global EdgePolicyMode switch onto bundle metadata so
// different fleets and users can run at different modes simultaneously.
type EdgeMode int32

const (
	EdgeMode_EDGE_MODE_UNSPECIFIED       EdgeMode = 0
	EdgeMode_EDGE_MODE_OBSERVE           EdgeMode = 1
	EdgeMode_EDGE_MODE_ENFORCE           EdgeMode = 2
	EdgeMode_EDGE_MODE_ENTERPRISE_STRICT EdgeMode = 3
)

// Enum value maps for EdgeMode.
var (
	EdgeMode_name = map[int32]string{
		0: "EDGE_MODE_UNSPECIFIED",
		1: "EDGE_MODE_OBSERVE",
		2: "EDGE_MODE_ENFORCE",
		3: "EDGE_MODE_ENTERPRISE_STRICT",
	}
	EdgeMode_value = map[string]int32{
		"EDGE_MODE_UNSPECIFIED":       0,
		"EDGE_MODE_OBSERVE":           1,
		"EDGE_MODE_ENFORCE":           2,
		"EDGE_MODE_ENTERPRISE_STRICT": 3,
	}
)

func (x EdgeMode) Enum() *EdgeMode {
	p := new(EdgeMode)
	*p = x
	return p
}

func (x EdgeMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EdgeMode) Descriptor() protoreflect.EnumDescriptor {
	return file_cordum_agent_v1_policy_proto_enumTypes[4].Descriptor()
}

func (EdgeMode) Type() protoreflect.EnumType {
	return &file_cordum_agent_v1_policy_proto_enumTypes[4]
}

func (x EdgeMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EdgeMode.Descriptor instead.
func (EdgeMode) EnumDescriptor() ([]byte, []int) {
	return file_cordum_agent_v1_policy_proto_rawDescGZIP(), []int{4}
}

// RuleScope narrows where a rule (or bundle) applies. When kind is
// RULE_SCOPE_KIND_GLOBAL, value is unused and may be empty.
type RuleScope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          RuleScopeKind          `protobuf:"varint,1,opt,name=kind,proto3,enum=cordum.agent.v1.RuleScopeKind" json:"kind,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleScope) Reset() {
	*x = RuleScope{}
	mi := &file_cordum_agent_v1_policy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleScope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleScope) ProtoMessage() {}

func (x *RuleScope) ProtoReflect() protoreflect.Message {
	mi := &file_cordum_agent_v1_policy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleScope.ProtoReflect.Descriptor instead.
func (*RuleScope) Descriptor() ([]byte, []int) {
	return file_cordum_agent_v1_policy_proto_rawDescGZIP(), []int{0}
}

func (x *RuleScope) GetKind() RuleScopeKind {
	if x != nil {
		return x.Kind
	}
	return RuleScopeKind_RULE_SCOPE_KIND_UNSPECIFIED
}

func (x *RuleScope) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// AuditMetadata records who created or last updated a Rule or Bundle. The
// updated_* fields are zero-valued on first creation and populated by the
// first subsequent edit.
type AuditMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,2,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	UpdatedBy     string                 `protobuf:"bytes,4,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditMetadata) Reset() {
	*x = AuditMetadata{}
	mi := &file_cordum_agent_v1_policy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditMetadata) ProtoMessage() {}

func (x *AuditMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_cordum_agent_v1_policy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditMetadata.ProtoReflect.Descriptor instead.
func (*AuditMetadata) Descriptor() ([]byte, []int) {
	return file_cordum_agent_v1_policy_proto_rawDescGZIP(), []int{1}
}

func (x *AuditMetadata) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *AuditMetadata) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *AuditMetadata) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *AuditMetadata) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

// Rule is the unified authoring surface for both job-side and edge-side
// policy. The envelope (id, name, type, scope, status, version, audit) is
// shared across all rule types; the type-specific match/decide payloads
// carry the per-RuleType schema as Struct for lossless JSON roundtrip with
// the Go json.RawMessage and the orval-generated dashboard types.
type Rule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          RuleType               `protobuf:"varint,3,opt,name=type,proto3,enum=cordum.agent.v1.RuleType" json:"type,omitempty"`
	Scope         *RuleScope             `protobuf:"bytes,4,opt,name=scope,proto3" json:"scope,omitempty"`
	Status        RuleStatus             `protobuf:"varint,5,opt,name=status,proto3,enum=cordum.agent.v1.RuleStatus" json:"status,omitempty"`
	Version       string                 `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
	Audit         *AuditMetadata         `protobuf:"bytes,7,opt,name=audit,proto3" json:"audit,omitempty"`
	Match         *structpb.Struct       `protobuf:"bytes,8,opt,name=match,proto3" json:"match,omitempty"`
	Decide        *structpb.Struct       `protobuf:"bytes,9,opt,name=decide,proto3" json:"decide,omitempty"`
	Description   string                 `protobuf:"bytes,10,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rule) Reset() {
	*x = Rule{}
	mi := &file_cordum_agent_v1_policy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rule) ProtoMessage() {}

func (x *Rule) ProtoReflect() protoreflect.Message {
	mi := &file_cordum_agent_v1_policy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rule.ProtoReflect.Descriptor instead.
func (*Rule) Descriptor() ([]byte, []int) {
	return file_cordum_agent_v1_policy_proto_rawDescGZIP(), []int{2}
}

func (x *Rule) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Rule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Rule) GetType() RuleType {
	if x != nil {
		return x.Type
	}
	return RuleType_RULE_TYPE_UNSPECIFIED
}

func (x *Rule) GetScope() *RuleScope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *Rule) GetStatus() RuleStatus {
	if x != nil {
		return x.Status
	}
	return RuleStatus_RULE_STATUS_UNSPECIFIED
}

func (x *Rule) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Rule) GetAudit() *AuditMetadata {
	if x != nil {
		return x.Audit
	}
	return nil
}

func (x *Rule) GetMatch() *structpb.Struct {
	if x != nil {
		return x.Match
	}
	return nil
}

func (x *Rule) GetDecide() *structpb.Struct {
	if x != nil {
		return x.Decide
	}
	return nil
}

func (x *Rule) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// TraceStep records one rule evaluation contributing to a Decision. Multiple
// trace steps are emitted when a rule chain or bundle composition produces a
// final decision through ordered evaluation.
type TraceStep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleId        string                 `protobuf:"bytes,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	BundleId      string                 `protobuf:"bytes,2,opt,name=bundle_id,json=bundleId,proto3" json:"bundle_id,omitempty"`
	DecisionType  DecisionType           `protobuf:"varint,3,opt,name=decision_type,json=decisionType,proto3,enum=cordum.agent.v1.DecisionType" json:"decision_type,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Constraints   *structpb.Struct       `protobuf:"bytes,6,opt,name=constraints,proto3" json:"constraints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TraceStep) Reset() {
	*x = TraceStep{}
	mi := &file_cordum_agent_v1_policy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TraceStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraceStep) ProtoMessage() {}

func (x *TraceStep) ProtoReflect() protoreflect.Message {
	mi := &file_cordum_agent_v1_policy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraceStep.ProtoReflect.Descriptor instead.
func (*TraceStep) Descriptor() ([]byte, []int) {
	return file_cordum_agent_v1_policy_proto_rawDescGZIP(), []int{3}
}

func (x *TraceStep) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *TraceStep) GetBundleId() string {
	if x != nil {
		return x.BundleId
	}
	return ""
}

func (x *TraceStep) GetDecisionType() DecisionType {
	if x != nil {
		return x.DecisionType
	}
	return DecisionType_DECISION_TYPE_UNSPECIFIED
}

func (x *TraceStep) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *TraceStep) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *TraceStep) GetConstraints() *structpb.Struct {
	if x != nil {
		return x.Constraints
	}
	return nil
}

// Decision is the unified evaluator output. A single Decision may aggregate
// multiple rule evaluations via trace; type holds the final outcome the
// evaluator derived from the trace. source distinguishes the producing
// evaluator. input_ref and output_ref are pointers into the blob store
// rather than embedded payloads.
type Decision struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        DecisionSource         `protobuf:"varint,1,opt,name=source,proto3,enum=cordum.agent.v1.DecisionSource" json:"source,omitempty"`
	RuleId        string                 `protobuf:"bytes,2,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	BundleId      string                 `protobuf:"bytes,3,opt,name=bundle_id,json=bundleId,proto3" json:"bundle_id,omitempty"`
	BundleVersion string                 `protobuf:"bytes,4,opt,name=bundle_version,json=bundleVersion,proto3" json:"bundle_version,omitempty"`
	Type          DecisionType           `protobuf:"varint,5,opt,name=type,proto3,enum=cordum.agent.v1.DecisionType" json:"type,omitempty"`
	Trace         []*TraceStep           `protobuf:"bytes,6,rep,name=trace,proto3" json:"trace,omitempty"`
	InputRef      string                 `protobuf:"bytes,7,opt,name=input_ref,json=inputRef,proto3" json:"input_ref,omitempty"`
	OutputRef     string                 `protobuf:"bytes,8,opt,name=output_ref,json=outputRef,proto3" json:"output_ref,omitempty"`
	AuditHash     string                 `protobuf:"bytes,9,opt,name=audit_hash,json=auditHash,proto3" json:"audit_hash,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Decision) Reset() {
	*x = Decision{}
	mi := &file_cordum_agent_v1_policy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Decision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Decision) ProtoMessage() {}

func (x *Decision) ProtoReflect() protoreflect.Message {
	mi := &file_cordum_agent_v1_policy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Decision.ProtoReflect.Descriptor instead.
func (*Decision) Descriptor() ([]byte, []int) {
	return file_cordum_agent_v1_policy_proto_rawDescGZIP(), []int{4}
}

func (x *Decision) GetSource() DecisionSource {
	if x != nil {
		return x.Source
	}
	return DecisionSource_DECISION_SOURCE_UNSPECIFIED
}

func (x *Decision) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *Decision) GetBundleId() string {
	if x != nil {
		return x.BundleId
	}
	return ""
}

func (x *Decision) GetBundleVersion() string {
	if x != nil {
		return x.BundleVersion
	}
	return ""
}

func (x *Decision) GetType() DecisionType {
	if x != nil {
		return x.Type
	}
	return DecisionType_DECISION_TYPE_UNSPECIFIED
}

func (x *Decision) GetTrace() []*TraceStep {
	if x != nil {
		return x.Trace
	}
	return nil
}

func (x *Decision) GetInputRef() string {
	if x != nil {
		return x.InputRef
	}
	return ""
}

func (x *Decision) GetOutputRef() string {
	if x != nil {
		return x.OutputRef
	}
	return ""
}

func (x *Decision) GetAuditHash() string {
	if x != nil {
		return x.AuditHash
	}
	return ""
}

func (x *Decision) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// BundleMetadata carries per-bundle authoring metadata that does not affect
// match/decide payloads. edge_mode is the per-bundle enforcement posture for
// edge-scoped bundles, replacing the legacy global EdgePolicyMode switch.
type BundleMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EdgeMode      EdgeMode               `protobuf:"varint,1,opt,name=edge_mode,json=edgeMode,proto3,enum=cordum.agent.v1.EdgeMode" json:"edge_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BundleMetadata) Reset() {
	*x = BundleMetadata{}
	mi := &file_cordum_agent_v1_policy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BundleMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BundleMetadata) ProtoMessage() {}

func (x *BundleMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_cordum_agent_v1_policy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BundleMetadata.ProtoReflect.Descriptor instead.
func (*BundleMetadata) Descriptor() ([]byte, []int) {
	return file_cordum_agent_v1_policy_proto_rawDescGZIP(), []int{5}
}

func (x *BundleMetadata) GetEdgeMode() EdgeMode {
	if x != nil {
		return x.EdgeMode
	}
	return EdgeMode_EDGE_MODE_UNSPECIFIED
}

// BundleVersion is the immutable record of a Bundle deploy. rule_snapshot
// captures the full Rule contents at deploy time so rollback and audit do
// not depend on the live rule store; audit_hash chains the version into the
// audit chain.
type BundleVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	RuleSnapshot  []*Rule                `protobuf:"bytes,2,rep,name=rule_snapshot,json=ruleSnapshot,proto3" json:"rule_snapshot,omitempty"`
	DeployedAt    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=deployed_at,json=deployedAt,proto3" json:"deployed_at,omitempty"`
	AuditHash     string                 `protobuf:"bytes,4,opt,name=audit_hash,json=auditHash,proto3" json:"audit_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BundleVersion) Reset() {
	*x = BundleVersion{}
	mi := &file_cordum_agent_v1_policy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BundleVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BundleVersion) ProtoMessage() {}

func (x *BundleVersion) ProtoReflect() protoreflect.Message {
	mi := &file_cordum_agent_v1_policy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BundleVersion.ProtoReflect.Descriptor instead.
func (*BundleVersion) Descriptor() ([]byte, []int) {
	return file_cordum_agent_v1_policy_proto_rawDescGZIP(), []int{6}
}

func (x *BundleVersion) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *BundleVersion) GetRuleSnapshot() []*Rule {
	if x != nil {
		return x.RuleSnapshot
	}
	return nil
}

func (x *BundleVersion) GetDeployedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeployedAt
	}
	return nil
}

func (x *BundleVersion) GetAuditHash() string {
	if x != nil {
		return x.AuditHash
	}
	return ""
}

// Bundle is a deployable set of rules with a deployment scope. Rules are
// referenced by id rather than embedded so a bundle can rotate its members
// without forcing rule duplication; the snapshot at deploy time lives in
// BundleVersion.rule_snapshot for tamper-evident rollback.
type Bundle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	RuleIds       []string               `protobuf:"bytes,3,rep,name=rule_ids,json=ruleIds,proto3" json:"rule_ids,omitempty"`
	ScopeBinding  *RuleScope             `protobuf:"bytes,4,opt,name=scope_binding,json=scopeBinding,proto3" json:"scope_binding,omitempty"`
	Versions      []*BundleVersion       `protobuf:"bytes,5,rep,name=versions,proto3" json:"versions,omitempty"`
	Metadata      *BundleMetadata        `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bundle) Reset() {
	*x = Bundle{}
	mi := &file_cordum_agent_v1_policy_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bundle) ProtoMessage() {}

func (x *Bundle) ProtoReflect() protoreflect.Message {
	mi := &file_cordum_agent_v1_policy_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bundle.ProtoReflect.Descriptor instead.
func (*Bundle) Descriptor() ([]byte, []int) {
	return file_cordum_agent_v1_policy_proto_rawDescGZIP(), []int{7}
}

func (x *Bundle) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Bundle) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Bundle) GetRuleIds() []string {
	if x != nil {
		return x.RuleIds
	}
	return nil
}

func (x *Bundle) GetScopeBinding() *RuleScope {
	if x != nil {
		return x.ScopeBinding
	}
	return nil
}

func (x *Bundle) GetVersions() []*BundleVersion {
	if x != nil {
		return x.Versions
	}
	return nil
}

func (x *Bundle) GetMetadata() *BundleMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// JobEvaluationContext carries the job-side inputs needed to evaluate a
// unified Rule through the safetykernel path. It intentionally mirrors the
// identity and input-content fields used by PolicyCheckRequest without
// coupling the unified evaluator contract to the legacy endpoint shape.
type JobEvaluationContext struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TenantId         string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	JobId            string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	WorkflowId       string                 `protobuf:"bytes,3,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	Topic            string                 `protobuf:"bytes,4,opt,name=topic,proto3" json:"topic,omitempty"`
	PrincipalId      string                 `protobuf:"bytes,5,opt,name=principal_id,json=principalId,proto3" json:"principal_id,omitempty"`
	Labels           map[string]string      `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MemoryId         string                 `protobuf:"bytes,7,opt,name=memory_id,json=memoryId,proto3" json:"memory_id,omitempty"`
	Capability       string                 `protobuf:"bytes,8,opt,name=capability,proto3" json:"capability,omitempty"`
	RiskTags         []string               `protobuf:"bytes,9,rep,name=risk_tags,json=riskTags,proto3" json:"risk_tags,omitempty"`
	InputContent     []byte                 `protobuf:"bytes,20,opt,name=input_content,json=inputContent,proto3" json:"input_content,omitempty"`
	InputContentType string                 `protobuf:"bytes,21,opt,name=input_content_type,json=inputContentType,proto3" json:"input_content_type,omitempty"`
	InputSizeBytes   int64                  `protobuf:"varint,22,opt,name=input_size_bytes,json=inputSizeBytes,proto3" json:"input_size_bytes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *JobEvaluationContext) Reset() {
	*x = JobEvaluationContext{}
	mi := &file_cordum_agent_v1_policy_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobEvaluationContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobEvaluationContext) ProtoMessage() {}

func (x *JobEvaluationContext) ProtoReflect() protoreflect.Message {
	mi := &file_cordum_agent_v1_policy_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobEvaluationContext.ProtoReflect.Descriptor instead.
func (*JobEvaluationContext) Descriptor() ([]byte, []int) {
	return file_cordum_agent_v1_policy_proto_rawDescGZIP(), []int{8}
}

func (x *JobEvaluationContext) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *JobEvaluationContext) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobEvaluationContext) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *JobEvaluationContext) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *JobEvaluationContext) GetPrincipalId() string {
	if x != nil {
		return x.PrincipalId
	}
	return ""
}

func (x *JobEvaluationContext) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *JobEvaluationContext) GetMemoryId() string {
	if x != nil {
		return x.MemoryId
	}
	return ""
}

func (x *JobEvaluationContext) GetCapability() string {
	if x != nil {
		return x.Capability
	}
	return ""
}

func (x *JobEvaluationContext) GetRiskTags() []string {
	if x != nil {
		return x.RiskTags
	}
	return nil
}

func (x *JobEvaluationContext) GetInputContent() []byte {
	if x != nil {
		return x.InputContent
	}
	return nil
}

func (x *JobEvaluationContext) GetInputContentType() string {
	if x != nil {
		return x.InputContentType
	}
	return ""
}

func (x *JobEvaluationContext) GetInputSizeBytes() int64 {
	if x != nil {
		return x.InputSizeBytes
	}
	return 0
}

// EdgeEvaluationContext carries the edge-side action snapshot needed to
// evaluate a unified edge Rule through the edge classifier path. Raw tool input
// is intentionally absent; callers provide only redacted input and labels.
type EdgeEvaluationContext struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TenantId          string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	PrincipalId       string                 `protobuf:"bytes,2,opt,name=principal_id,json=principalId,proto3" json:"principal_id,omitempty"`
	SessionId         string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ExecutionId       string                 `protobuf:"bytes,4,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	AgentProduct      string                 `protobuf:"bytes,5,opt,name=agent_product,json=agentProduct,proto3" json:"agent_product,omitempty"`
	ToolName          string                 `protobuf:"bytes,6,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	ToolInputRedacted *structpb.Struct       `protobuf:"bytes,7,opt,name=tool_input_redacted,json=toolInputRedacted,proto3" json:"tool_input_redacted,omitempty"`
	InputHash         string                 `protobuf:"bytes,8,opt,name=input_hash,json=inputHash,proto3" json:"input_hash,omitempty"`
	ToolInputHash     string                 `protobuf:"bytes,9,opt,name=tool_input_hash,json=toolInputHash,proto3" json:"tool_input_hash,omitempty"`
	Labels            map[string]string      `protobuf:"bytes,10,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RiskTags          []string               `protobuf:"bytes,11,rep,name=risk_tags,json=riskTags,proto3" json:"risk_tags,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EdgeEvaluationContext) Reset() {
	*x = EdgeEvaluationContext{}
	mi := &file_cordum_agent_v1_policy_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EdgeEvaluationContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EdgeEvaluationContext) ProtoMessage() {}

func (x *EdgeEvaluationContext) ProtoReflect() protoreflect.Message {
	mi := &file_cordum_agent_v1_policy_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EdgeEvaluationContext.ProtoReflect.Descriptor instead.
func (*EdgeEvaluationContext) Descriptor() ([]byte, []int) {
	return file_cordum_agent_v1_policy_proto_rawDescGZIP(), []int{9}
}

func (x *EdgeEvaluationContext) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *EdgeEvaluationContext) GetPrincipalId() string {
	if x != nil {
		return x.PrincipalId
	}
	return ""
}

func (x *EdgeEvaluationContext) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *EdgeEvaluationContext) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *EdgeEvaluationContext) GetAgentProduct() string {
	if x != nil {
		return x.AgentProduct
	}
	return ""
}

func (x *EdgeEvaluationContext) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *EdgeEvaluationContext) GetToolInputRedacted() *structpb.Struct {
	if x != nil {
		return x.ToolInputRedacted
	}
	return nil
}

func (x *EdgeEvaluationContext) GetInputHash() string {
	if x != nil {
		return x.InputHash
	}
	return ""
}

func (x *EdgeEvaluationContext) GetToolInputHash() string {
	if x != nil {
		return x.ToolInputHash
	}
	return ""
}

func (x *EdgeEvaluationContext) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *EdgeEvaluationContext) GetRiskTags() []string {
	if x != nil {
		return x.RiskTags
	}
	return nil
}

// PolicyEvaluateRequest is the unified evaluator entry-point request. Callers
// either provide an inline Rule or a (bundle_id, scope) pair that resolves the
// currently active BundleVersion before evaluation. Exactly one of
// job_context or edge_context must be populated, and it must match Rule.type.
type PolicyEvaluateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rule          *Rule                  `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"`
	BundleId      string                 `protobuf:"bytes,2,opt,name=bundle_id,json=bundleId,proto3" json:"bundle_id,omitempty"`
	Scope         *RuleScope             `protobuf:"bytes,3,opt,name=scope,proto3" json:"scope,omitempty"`
	JobContext    *JobEvaluationContext  `protobuf:"bytes,10,opt,name=job_context,json=jobContext,proto3" json:"job_context,omitempty"`
	EdgeContext   *EdgeEvaluationContext `protobuf:"bytes,11,opt,name=edge_context,json=edgeContext,proto3" json:"edge_context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyEvaluateRequest) Reset() {
	*x = PolicyEvaluateRequest{}
	mi := &file_cordum_agent_v1_policy_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyEvaluateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyEvaluateRequest) ProtoMessage() {}

func (x *PolicyEvaluateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cordum_agent_v1_policy_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyEvaluateRequest.ProtoReflect.Descriptor instead.
func (*PolicyEvaluateRequest) Descriptor() ([]byte, []int) {
	return file_cordum_agent_v1_policy_proto_rawDescGZIP(), []int{10}
}

func (x *PolicyEvaluateRequest) GetRule() *Rule {
	if x != nil {
		return x.Rule
	}
	return nil
}

func (x *PolicyEvaluateRequest) GetBundleId() string {
	if x != nil {
		return x.BundleId
	}
	return ""
}

func (x *PolicyEvaluateRequest) GetScope() *RuleScope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *PolicyEvaluateRequest) GetJobContext() *JobEvaluationContext {
	if x != nil {
		return x.JobContext
	}
	return nil
}

func (x *PolicyEvaluateRequest) GetEdgeContext() *EdgeEvaluationContext {
	if x != nil {
		return x.EdgeContext
	}
	return nil
}

// PolicyEvaluateResponse wraps the unified Decision emitted by the selected
// evaluator. The legacy PolicyCheckResponse remains available on the transition
// endpoints; this response is for the unified Rule/Decision surface.
type PolicyEvaluateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Decision      *Decision              `protobuf:"bytes,1,opt,name=decision,proto3" json:"decision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyEvaluateResponse) Reset() {
	*x = PolicyEvaluateResponse{}
	mi := &file_cordum_agent_v1_policy_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyEvaluateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyEvaluateResponse) ProtoMessage() {}

func (x *PolicyEvaluateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cordum_agent_v1_policy_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyEvaluateResponse.ProtoReflect.Descriptor instead.
func (*PolicyEvaluateResponse) Descriptor() ([]byte, []int) {
	return file_cordum_agent_v1_policy_proto_rawDescGZIP(), []int{11}
}

func (x *PolicyEvaluateResponse) GetDecision() *Decision {
	if x != nil {
		return x.Decision
	}
	return nil
}

var File_cordum_agent_v1_policy_proto protoreflect.FileDescriptor

const file_cordum_agent_v1_policy_proto_rawDesc = "" +
	"\n" +
	"\x1ccordum/agent/v1/policy.proto\x12\x0fcordum.agent.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1ccordum/agent/v1/safety.proto\"U\n" +
	"\tRuleScope\x122\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x1e.cordum.agent.v1.RuleScopeKindR\x04kind\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xc3\x01\n" +
	"\rAuditMetadata\x129\n" +
	"\n" +
	"created_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"created_by\x18\x02 \x01(\tR\tcreatedBy\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"updated_by\x18\x04 \x01(\tR\tupdatedBy\"\x92\x03\n" +
	"\x04Rule\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12-\n" +
	"\x04type\x18\x03 \x01(\x0e2\x19.cordum.agent.v1.RuleTypeR\x04type\x120\n" +
	"\x05scope\x18\x04 \x01(\v2\x1a.cordum.agent.v1.RuleScopeR\x05scope\x123\n" +
	"\x06status\x18\x05 \x01(\x0e2\x1b.cordum.agent.v1.RuleStatusR\x06status\x12\x18\n" +
	"\aversion\x18\x06 \x01(\tR\aversion\x124\n" +
	"\x05audit\x18\a \x01(\v2\x1e.cordum.agent.v1.AuditMetadataR\x05audit\x12-\n" +
	"\x05match\x18\b \x01(\v2\x17.google.protobuf.StructR\x05match\x12/\n" +
	"\x06decide\x18\t \x01(\v2\x17.google.protobuf.StructR\x06decide\x12 \n" +
	"\vdescription\x18\n" +
	" \x01(\tR\vdescription\"\x92\x02\n" +
	"\tTraceStep\x12\x17\n" +
	"\arule_id\x18\x01 \x01(\tR\x06ruleId\x12\x1b\n" +
	"\tbundle_id\x18\x02 \x01(\tR\bbundleId\x12B\n" +
	"\rdecision_type\x18\x03 \x01(\x0e2\x1d.cordum.agent.v1.DecisionTypeR\fdecisionType\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x129\n" +
	"\vconstraints\x18\x06 \x01(\v2\x17.google.protobuf.StructR\vconstraints\"\x9a\x03\n" +
	"\bDecision\x127\n" +
	"\x06source\x18\x01 \x01(\x0e2\x1f.cordum.agent.v1.DecisionSourceR\x06source\x12\x17\n" +
	"\arule_id\x18\x02 \x01(\tR\x06ruleId\x12\x1b\n" +
	"\tbundle_id\x18\x03 \x01(\tR\bbundleId\x12%\n" +
	"\x0ebundle_version\x18\x04 \x01(\tR\rbundleVersion\x121\n" +
	"\x04type\x18\x05 \x01(\x0e2\x1d.cordum.agent.v1.DecisionTypeR\x04type\x120\n" +
	"\x05trace\x18\x06 \x03(\v2\x1a.cordum.agent.v1.TraceStepR\x05trace\x12\x1b\n" +
	"\tinput_ref\x18\a \x01(\tR\binputRef\x12\x1d\n" +
	"\n" +
	"output_ref\x18\b \x01(\tR\toutputRef\x12\x1d\n" +
	"\n" +
	"audit_hash\x18\t \x01(\tR\tauditHash\x128\n" +
	"\ttimestamp\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"H\n" +
	"\x0eBundleMetadata\x126\n" +
	"\tedge_mode\x18\x01 \x01(\x0e2\x19.cordum.agent.v1.EdgeModeR\bedgeMode\"\xc1\x01\n" +
	"\rBundleVersion\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12:\n" +
	"\rrule_snapshot\x18\x02 \x03(\v2\x15.cordum.agent.v1.RuleR\fruleSnapshot\x12;\n" +
	"\vdeployed_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"deployedAt\x12\x1d\n" +
	"\n" +
	"audit_hash\x18\x04 \x01(\tR\tauditHash\"\x81\x02\n" +
	"\x06Bundle\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\brule_ids\x18\x03 \x03(\tR\aruleIds\x12?\n" +
	"\rscope_binding\x18\x04 \x01(\v2\x1a.cordum.agent.v1.RuleScopeR\fscopeBinding\x12:\n" +
	"\bversions\x18\x05 \x03(\v2\x1e.cordum.agent.v1.BundleVersionR\bversions\x12;\n" +
	"\bmetadata\x18\x06 \x01(\v2\x1f.cordum.agent.v1.BundleMetadataR\bmetadata\"\x81\x04\n" +
	"\x14JobEvaluationContext\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12\x1f\n" +
	"\vworkflow_id\x18\x03 \x01(\tR\n" +
	"workflowId\x12\x14\n" +
	"\x05topic\x18\x04 \x01(\tR\x05topic\x12!\n" +
	"\fprincipal_id\x18\x05 \x01(\tR\vprincipalId\x12I\n" +
	"\x06labels\x18\x06 \x03(\v21.cordum.agent.v1.JobEvaluationContext.LabelsEntryR\x06labels\x12\x1b\n" +
	"\tmemory_id\x18\a \x01(\tR\bmemoryId\x12\x1e\n" +
	"\n" +
	"capability\x18\b \x01(\tR\n" +
	"capability\x12\x1b\n" +
	"\trisk_tags\x18\t \x03(\tR\briskTags\x12#\n" +
	"\rinput_content\x18\x14 \x01(\fR\finputContent\x12,\n" +
	"\x12input_content_type\x18\x15 \x01(\tR\x10inputContentType\x12(\n" +
	"\x10input_size_bytes\x18\x16 \x01(\x03R\x0einputSizeBytes\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8f\x04\n" +
	"\x15EdgeEvaluationContext\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12!\n" +
	"\fprincipal_id\x18\x02 \x01(\tR\vprincipalId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12!\n" +
	"\fexecution_id\x18\x04 \x01(\tR\vexecutionId\x12#\n" +
	"\ragent_product\x18\x05 \x01(\tR\fagentProduct\x12\x1b\n" +
	"\ttool_name\x18\x06 \x01(\tR\btoolName\x12G\n" +
	"\x13tool_input_redacted\x18\a \x01(\v2\x17.google.protobuf.StructR\x11toolInputRedacted\x12\x1d\n" +
	"\n" +
	"input_hash\x18\b \x01(\tR\tinputHash\x12&\n" +
	"\x0ftool_input_hash\x18\t \x01(\tR\rtoolInputHash\x12J\n" +
	"\x06labels\x18\n" +
	" \x03(\v22.cordum.agent.v1.EdgeEvaluationContext.LabelsEntryR\x06labels\x12\x1b\n" +
	"\trisk_tags\x18\v \x03(\tR\briskTags\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa4\x02\n" +
	"\x15PolicyEvaluateRequest\x12)\n" +
	"\x04rule\x18\x01 \x01(\v2\x15.cordum.agent.v1.RuleR\x04rule\x12\x1b\n" +
	"\tbundle_id\x18\x02 \x01(\tR\bbundleId\x120\n" +
	"\x05scope\x18\x03 \x01(\v2\x1a.cordum.agent.v1.RuleScopeR\x05scope\x12F\n" +
	"\vjob_context\x18\n" +
	" \x01(\v2%.cordum.agent.v1.JobEvaluationContextR\n" +
	"jobContext\x12I\n" +
	"\fedge_context\x18\v \x01(\v2&.cordum.agent.v1.EdgeEvaluationContextR\vedgeContext\"O\n" +
	"\x16PolicyEvaluateResponse\x125\n" +
	"\bdecision\x18\x01 \x01(\v2\x19.cordum.agent.v1.DecisionR\bdecision*|\n" +
	"\bRuleType\x12\x19\n" +
	"\x15RULE_TYPE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fRULE_TYPE_INPUT\x10\x01\x12\x14\n" +
	"\x10RULE_TYPE_OUTPUT\x10\x02\x12\x16\n" +
	"\x12RULE_TYPE_VELOCITY\x10\x03\x12\x12\n" +
	"\x0eRULE_TYPE_EDGE\x10\x04*w\n" +
	"\n" +
	"RuleStatus\x12\x1b\n" +
	"\x17RULE_STATUS_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11RULE_STATUS_DRAFT\x10\x01\x12\x19\n" +
	"\x15RULE_STATUS_PUBLISHED\x10\x02\x12\x1a\n" +
	"\x16RULE_STATUS_DEPRECATED\x10\x03*d\n" +
	"\x0eDecisionSource\x12\x1f\n" +
	"\x1bDECISION_SOURCE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13DECISION_SOURCE_JOB\x10\x01\x12\x18\n" +
	"\x14DECISION_SOURCE_EDGE\x10\x02*\xc5\x01\n" +
	"\rRuleScopeKind\x12\x1f\n" +
	"\x1bRULE_SCOPE_KIND_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16RULE_SCOPE_KIND_GLOBAL\x10\x01\x12\x1a\n" +
	"\x16RULE_SCOPE_KIND_TENANT\x10\x02\x12\x1c\n" +
	"\x18RULE_SCOPE_KIND_WORKFLOW\x10\x03\x12\x1e\n" +
	"\x1aRULE_SCOPE_KIND_EDGE_FLEET\x10\x04\x12\x1d\n" +
	"\x19RULE_SCOPE_KIND_EDGE_USER\x10\x05*t\n" +
	"\bEdgeMode\x12\x19\n" +
	"\x15EDGE_MODE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11EDGE_MODE_OBSERVE\x10\x01\x12\x15\n" +
	"\x11EDGE_MODE_ENFORCE\x10\x02\x12\x1f\n" +
	"\x1bEDGE_MODE_ENTERPRISE_STRICT\x10\x032u\n" +
	"\x0fPolicyEvaluator\x12b\n" +
	"\x0fEvaluateUnified\x12&.cordum.agent.v1.PolicyEvaluateRequest\x1a'.cordum.agent.v1.PolicyEvaluateResponseB\x7f\n" +
	"\x16io.cordum.cap.agent.v1P\x01Z+github.com/cordum-io/cap/v2/cordum/agent/v1\xaa\x02\x0fCordum.Agent.V1\xca\x02\x0fcordum\\Agent\\V1\xea\x02\x11Cordum::Agent::V1b\x06proto3"

var (
	file_cordum_agent_v1_policy_proto_rawDescOnce sync.Once
	file_cordum_agent_v1_policy_proto_rawDescData []byte
)

func file_cordum_agent_v1_policy_proto_rawDescGZIP() []byte {
	file_cordum_agent_v1_policy_proto_rawDescOnce.Do(func() {
		file_cordum_agent_v1_policy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cordum_agent_v1_policy_proto_rawDesc), len(file_cordum_agent_v1_policy_proto_rawDesc)))
	})
	return file_cordum_agent_v1_policy_proto_rawDescData
}

var file_cordum_agent_v1_policy_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_cordum_agent_v1_policy_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_cordum_agent_v1_policy_proto_goTypes = []any{
	(RuleType)(0),                  // 0: cordum.agent.v1.RuleType
	(RuleStatus)(0),                // 1: cordum.agent.v1.RuleStatus
	(DecisionSource)(0),            // 2: cordum.agent.v1.DecisionSource
	(RuleScopeKind)(0),             // 3: cordum.agent.v1.RuleScopeKind
	(EdgeMode)(0),                  // 4: cordum.agent.v1.EdgeMode
	(*RuleScope)(nil),              // 5: cordum.agent.v1.RuleScope
	(*AuditMetadata)(nil),          // 6: cordum.agent.v1.AuditMetadata
	(*Rule)(nil),                   // 7: cordum.agent.v1.Rule
	(*TraceStep)(nil),              // 8: cordum.agent.v1.TraceStep
	(*Decision)(nil),               // 9: cordum.agent.v1.Decision
	(*BundleMetadata)(nil),         // 10: cordum.agent.v1.BundleMetadata
	(*BundleVersion)(nil),          // 11: cordum.agent.v1.BundleVersion
	(*Bundle)(nil),                 // 12: cordum.agent.v1.Bundle
	(*JobEvaluationContext)(nil),   // 13: cordum.agent.v1.JobEvaluationContext
	(*EdgeEvaluationContext)(nil),  // 14: cordum.agent.v1.EdgeEvaluationContext
	(*PolicyEvaluateRequest)(nil),  // 15: cordum.agent.v1.PolicyEvaluateRequest
	(*PolicyEvaluateResponse)(nil), // 16: cordum.agent.v1.PolicyEvaluateResponse
	nil,                            // 17: cordum.agent.v1.JobEvaluationContext.LabelsEntry
	nil,                            // 18: cordum.agent.v1.EdgeEvaluationContext.LabelsEntry
	(*timestamppb.Timestamp)(nil),  // 19: google.protobuf.Timestamp
	(*structpb.Struct)(nil),        // 20: google.protobuf.Struct
	(DecisionType)(0),              // 21: cordum.agent.v1.DecisionType
}
var file_cordum_agent_v1_policy_proto_depIdxs = []int32{
	3,  // 0: cordum.agent.v1.RuleScope.kind:type_name -> cordum.agent.v1.RuleScopeKind
	19, // 1: cordum.agent.v1.AuditMetadata.created_at:type_name -> google.protobuf.Timestamp
	19, // 2: cordum.agent.v1.AuditMetadata.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 3: cordum.agent.v1.Rule.type:type_name -> cordum.agent.v1.RuleType
	5,  // 4: cordum.agent.v1.Rule.scope:type_name -> cordum.agent.v1.RuleScope
	1,  // 5: cordum.agent.v1.Rule.status:type_name -> cordum.agent.v1.RuleStatus
	6,  // 6: cordum.agent.v1.Rule.audit:type_name -> cordum.agent.v1.AuditMetadata
	20, // 7: cordum.agent.v1.Rule.match:type_name -> google.protobuf.Struct
	20, // 8: cordum.agent.v1.Rule.decide:type_name -> google.protobuf.Struct
	21, // 9: cordum.agent.v1.TraceStep.decision_type:type_name -> cordum.agent.v1.DecisionType
	19, // 10: cordum.agent.v1.TraceStep.timestamp:type_name -> google.protobuf.Timestamp
	20, // 11: cordum.agent.v1.TraceStep.constraints:type_name -> google.protobuf.Struct
	2,  // 12: cordum.agent.v1.Decision.source:type_name -> cordum.agent.v1.DecisionSource
	21, // 13: cordum.agent.v1.Decision.type:type_name -> cordum.agent.v1.DecisionType
	8,  // 14: cordum.agent.v1.Decision.trace:type_name -> cordum.agent.v1.TraceStep
	19, // 15: cordum.agent.v1.Decision.timestamp:type_name -> google.protobuf.Timestamp
	4,  // 16: cordum.agent.v1.BundleMetadata.edge_mode:type_name -> cordum.agent.v1.EdgeMode
	7,  // 17: cordum.agent.v1.BundleVersion.rule_snapshot:type_name -> cordum.agent.v1.Rule
	19, // 18: cordum.agent.v1.BundleVersion.deployed_at:type_name -> google.protobuf.Timestamp
	5,  // 19: cordum.agent.v1.Bundle.scope_binding:type_name -> cordum.agent.v1.RuleScope
	11, // 20: cordum.agent.v1.Bundle.versions:type_name -> cordum.agent.v1.BundleVersion
	10, // 21: cordum.agent.v1.Bundle.metadata:type_name -> cordum.agent.v1.BundleMetadata
	17, // 22: cordum.agent.v1.JobEvaluationContext.labels:type_name -> cordum.agent.v1.JobEvaluationContext.LabelsEntry
	20, // 23: cordum.agent.v1.EdgeEvaluationContext.tool_input_redacted:type_name -> google.protobuf.Struct
	18, // 24: cordum.agent.v1.EdgeEvaluationContext.labels:type_name -> cordum.agent.v1.EdgeEvaluationContext.LabelsEntry
	7,  // 25: cordum.agent.v1.PolicyEvaluateRequest.rule:type_name -> cordum.agent.v1.Rule
	5,  // 26: cordum.agent.v1.PolicyEvaluateRequest.scope:type_name -> cordum.agent.v1.RuleScope
	13, // 27: cordum.agent.v1.PolicyEvaluateRequest.job_context:type_name -> cordum.agent.v1.JobEvaluationContext
	14, // 28: cordum.agent.v1.PolicyEvaluateRequest.edge_context:type_name -> cordum.agent.v1.EdgeEvaluationContext
	9,  // 29: cordum.agent.v1.PolicyEvaluateResponse.decision:type_name -> cordum.agent.v1.Decision
	15, // 30: cordum.agent.v1.PolicyEvaluator.EvaluateUnified:input_type -> cordum.agent.v1.PolicyEvaluateRequest
	16, // 31: cordum.agent.v1.PolicyEvaluator.EvaluateUnified:output_type -> cordum.agent.v1.PolicyEvaluateResponse
	31, // [31:32] is the sub-list for method output_type
	30, // [30:31] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_cordum_agent_v1_policy_proto_init() }
func file_cordum_agent_v1_policy_proto_init() {
	if File_cordum_agent_v1_policy_proto != nil {
		return
	}
	file_cordum_agent_v1_safety_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cordum_agent_v1_policy_proto_rawDesc), len(file_cordum_agent_v1_policy_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cordum_agent_v1_policy_proto_goTypes,
		DependencyIndexes: file_cordum_agent_v1_policy_proto_depIdxs,
		EnumInfos:         file_cordum_agent_v1_policy_proto_enumTypes,
		MessageInfos:      file_cordum_agent_v1_policy_proto_msgTypes,
	}.Build()
	File_cordum_agent_v1_policy_proto = out.File
	file_cordum_agent_v1_policy_proto_goTypes = nil
	file_cordum_agent_v1_policy_proto_depIdxs = nil
}
