# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from cordum.agent.v1 import policy_pb2 as cordum_dot_agent_dot_v1_dot_policy__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in cordum/agent/v1/policy_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PolicyEvaluatorStub(object):
    """PolicyEvaluator exposes the unified job + edge policy entry-point over gRPC.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EvaluateUnified = channel.unary_unary(
                '/cordum.agent.v1.PolicyEvaluator/EvaluateUnified',
                request_serializer=cordum_dot_agent_dot_v1_dot_policy__pb2.PolicyEvaluateRequest.SerializeToString,
                response_deserializer=cordum_dot_agent_dot_v1_dot_policy__pb2.PolicyEvaluateResponse.FromString,
                _registered_method=True)


class PolicyEvaluatorServicer(object):
    """PolicyEvaluator exposes the unified job + edge policy entry-point over gRPC.
    """

    def EvaluateUnified(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PolicyEvaluatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EvaluateUnified': grpc.unary_unary_rpc_method_handler(
                    servicer.EvaluateUnified,
                    request_deserializer=cordum_dot_agent_dot_v1_dot_policy__pb2.PolicyEvaluateRequest.FromString,
                    response_serializer=cordum_dot_agent_dot_v1_dot_policy__pb2.PolicyEvaluateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cordum.agent.v1.PolicyEvaluator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cordum.agent.v1.PolicyEvaluator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PolicyEvaluator(object):
    """PolicyEvaluator exposes the unified job + edge policy entry-point over gRPC.
    """

    @staticmethod
    def EvaluateUnified(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cordum.agent.v1.PolicyEvaluator/EvaluateUnified',
            cordum_dot_agent_dot_v1_dot_policy__pb2.PolicyEvaluateRequest.SerializeToString,
            cordum_dot_agent_dot_v1_dot_policy__pb2.PolicyEvaluateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
