"""Focused tests for hermetic Python protobuf generation checks."""

from __future__ import annotations

import importlib.metadata
import importlib.util
import shutil
import sys
from pathlib import Path, PurePosixPath
from types import ModuleType
from typing import Mapping
from unittest.mock import patch

import pytest


SCRIPT = Path(__file__).resolve().parents[1] / "scripts" / "generate_protos.py"


def _load_generator() -> ModuleType:
    spec = importlib.util.spec_from_file_location("cap_generate_protos", SCRIPT)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


generator = _load_generator()


def test_pins_match_tracked_generator_headers() -> None:
    assert generator.load_pins() == {
        "grpcio": "1.76.0",
        "grpcio-tools": "1.76.0",
        "protobuf": "6.33.5",
    }


def test_tool_versions_fail_closed_when_missing() -> None:
    missing = importlib.metadata.PackageNotFoundError("grpcio-tools")
    with patch.object(generator.metadata, "version", side_effect=missing):
        with pytest.raises(generator.CodegenError, match="required codegen tool is missing"):
            generator.verify_tool_versions()


def test_tool_versions_fail_closed_on_pin_mismatch() -> None:
    installed: Mapping[str, str] = {
        "grpcio": "1.76.0",
        "grpcio-tools": "1.77.0",
        "protobuf": "6.33.5",
    }
    with patch.object(generator.metadata, "version", side_effect=installed.__getitem__):
        with pytest.raises(
            generator.CodegenError,
            match=r"grpcio-tools.*1\.77\.0.*1\.76\.0",
        ):
            generator.verify_tool_versions()


def test_protoc_timeout_fails_closed(tmp_path: Path) -> None:
    timeout = generator.subprocess.TimeoutExpired(("grpc_tools.protoc",), 600)
    with patch.object(generator, "_grpc_include", return_value=tmp_path), patch.object(
        generator.subprocess, "run", side_effect=timeout
    ) as run:
        with pytest.raises(generator.CodegenError, match="timed out"):
            generator.run_protoc(tmp_path / "generated", tuple())
    assert run.call_args.kwargs["timeout"] == generator.CODEGEN_TIMEOUT_SECONDS


def test_canonical_set_is_sorted_and_yields_exact_outputs() -> None:
    protos = generator.canonical_protos()
    assert [path.name for path in protos] == sorted(path.name for path in protos)
    assert [path.stem for path in protos] == [
        "alert", "buspacket", "handshake", "heartbeat", "job", "policy", "safety",
    ]
    outputs = generator.expected_outputs(protos)
    assert len(outputs) == 14
    assert outputs[0] == PurePosixPath("cordum/agent/v1/alert_pb2.py")
    assert outputs[-1] == PurePosixPath("cordum/agent/v1/safety_pb2_grpc.py")


def _write_outputs(root: Path, outputs: tuple[PurePosixPath, ...], newline: bytes) -> None:
    for relative in outputs:
        target = root / Path(*relative.parts)
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(b"header" + newline + relative.as_posix().encode() + newline)


def test_compare_accepts_only_crlf_normalization(tmp_path: Path) -> None:
    outputs = generator.expected_outputs(generator.canonical_protos())
    generated, tracked = tmp_path / "generated", tmp_path / "tracked"
    _write_outputs(generated, outputs, b"\n")
    _write_outputs(tracked, outputs, b"\r\n")
    generator.compare_outputs(generated, tracked, outputs)


def test_compare_reports_extra_files(tmp_path: Path) -> None:
    outputs = generator.expected_outputs(generator.canonical_protos())
    generated, tracked = tmp_path / "generated", tmp_path / "tracked"
    _write_outputs(generated, outputs, b"\n")
    _write_outputs(tracked, outputs, b"\n")
    extra = generated / "cordum/agent/v1/extra_pb2.py"
    extra.write_text("extra\n", encoding="utf-8")
    with pytest.raises(generator.CodegenError) as raised:
        generator.compare_outputs(generated, tracked, outputs)
    assert "extra generated outputs" in str(raised.value)


def test_compare_reports_semantic_byte_drift(tmp_path: Path) -> None:
    outputs = generator.expected_outputs(generator.canonical_protos())
    generated, tracked = tmp_path / "generated", tmp_path / "tracked"
    _write_outputs(generated, outputs, b"\n")
    _write_outputs(tracked, outputs, b"\n")
    drift = tracked / Path(*outputs[0].parts)
    drift.write_text("different\n", encoding="utf-8")
    with pytest.raises(generator.CodegenError) as raised:
        generator.compare_outputs(generated, tracked, outputs)
    message = str(raised.value)
    assert "generated byte drift" in message
    assert outputs[0].as_posix() in message


def test_main_check_uses_temp_output_and_never_mutates_tracked(capsys: pytest.CaptureFixture[str]) -> None:
    before = {path: path.read_bytes() for path in generator.TRACKED_ROOT.rglob("*_pb2*.py")}

    def copy_tracked(destination: Path, _protos: tuple[Path, ...]) -> None:
        shutil.copytree(generator.TRACKED_ROOT, destination, dirs_exist_ok=True)

    pins = {"grpcio": "1.76.0", "grpcio-tools": "1.76.0", "protobuf": "6.33.5"}
    with patch.object(generator, "verify_tool_versions", return_value=pins), patch.object(
        generator, "run_protoc", side_effect=copy_tracked
    ):
        assert generator.main(("--check",)) == 0
    report = capsys.readouterr().out
    assert '"outputs": 14' in report
    assert before == {path: path.read_bytes() for path in before}


def test_main_fails_closed_when_check_fails(capsys: pytest.CaptureFixture[str]) -> None:
    failure = generator.CodegenError("semantic drift")
    with patch.object(generator, "check_generated", side_effect=failure):
        assert generator.main(("--check",)) == 1
    captured = capsys.readouterr()
    assert captured.out == ""
    assert "Python codegen check failed: semantic drift" in captured.err
