// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cordum/agent/v1/alert.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_cordum_2fagent_2fv1_2falert_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_cordum_2fagent_2fv1_2falert_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "cordum/agent/v1/job.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_cordum_2fagent_2fv1_2falert_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_cordum_2fagent_2fv1_2falert_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_cordum_2fagent_2fv1_2falert_2eproto;
namespace cordum {
namespace agent {
namespace v1 {
class SystemAlert;
struct SystemAlertDefaultTypeInternal;
extern SystemAlertDefaultTypeInternal _SystemAlert_default_instance_;
class SystemAlert_DetailsEntry_DoNotUse;
struct SystemAlert_DetailsEntry_DoNotUseDefaultTypeInternal;
extern SystemAlert_DetailsEntry_DoNotUseDefaultTypeInternal _SystemAlert_DetailsEntry_DoNotUse_default_instance_;
}  // namespace v1
}  // namespace agent
}  // namespace cordum
PROTOBUF_NAMESPACE_OPEN
template<> ::cordum::agent::v1::SystemAlert* Arena::CreateMaybeMessage<::cordum::agent::v1::SystemAlert>(Arena*);
template<> ::cordum::agent::v1::SystemAlert_DetailsEntry_DoNotUse* Arena::CreateMaybeMessage<::cordum::agent::v1::SystemAlert_DetailsEntry_DoNotUse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace cordum {
namespace agent {
namespace v1 {

enum AlertSeverity : int {
  ALERT_SEVERITY_UNSPECIFIED = 0,
  ALERT_SEVERITY_INFO = 1,
  ALERT_SEVERITY_WARNING = 2,
  ALERT_SEVERITY_ERROR = 3,
  ALERT_SEVERITY_CRITICAL = 4,
  AlertSeverity_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  AlertSeverity_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool AlertSeverity_IsValid(int value);
constexpr AlertSeverity AlertSeverity_MIN = ALERT_SEVERITY_UNSPECIFIED;
constexpr AlertSeverity AlertSeverity_MAX = ALERT_SEVERITY_CRITICAL;
constexpr int AlertSeverity_ARRAYSIZE = AlertSeverity_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* AlertSeverity_descriptor();
template<typename T>
inline const std::string& AlertSeverity_Name(T enum_t_value) {
  static_assert(::std::is_same<T, AlertSeverity>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function AlertSeverity_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    AlertSeverity_descriptor(), enum_t_value);
}
inline bool AlertSeverity_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, AlertSeverity* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<AlertSeverity>(
    AlertSeverity_descriptor(), name, value);
}
// ===================================================================

class SystemAlert_DetailsEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<SystemAlert_DetailsEntry_DoNotUse, 
    std::string, std::string,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING> {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<SystemAlert_DetailsEntry_DoNotUse, 
    std::string, std::string,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING> SuperType;
  SystemAlert_DetailsEntry_DoNotUse();
  explicit PROTOBUF_CONSTEXPR SystemAlert_DetailsEntry_DoNotUse(
      ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);
  explicit SystemAlert_DetailsEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const SystemAlert_DetailsEntry_DoNotUse& other);
  static const SystemAlert_DetailsEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const SystemAlert_DetailsEntry_DoNotUse*>(&_SystemAlert_DetailsEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(std::string* s) {
    return ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(s->data(), static_cast<int>(s->size()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "cordum.agent.v1.SystemAlert.DetailsEntry.key");
 }
  static bool ValidateValue(std::string* s) {
    return ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(s->data(), static_cast<int>(s->size()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "cordum.agent.v1.SystemAlert.DetailsEntry.value");
 }
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  friend struct ::TableStruct_cordum_2fagent_2fv1_2falert_2eproto;
};

// -------------------------------------------------------------------

class SystemAlert final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:cordum.agent.v1.SystemAlert) */ {
 public:
  inline SystemAlert() : SystemAlert(nullptr) {}
  ~SystemAlert() override;
  explicit PROTOBUF_CONSTEXPR SystemAlert(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SystemAlert(const SystemAlert& from);
  SystemAlert(SystemAlert&& from) noexcept
    : SystemAlert() {
    *this = ::std::move(from);
  }

  inline SystemAlert& operator=(const SystemAlert& from) {
    CopyFrom(from);
    return *this;
  }
  inline SystemAlert& operator=(SystemAlert&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SystemAlert& default_instance() {
    return *internal_default_instance();
  }
  static inline const SystemAlert* internal_default_instance() {
    return reinterpret_cast<const SystemAlert*>(
               &_SystemAlert_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(SystemAlert& a, SystemAlert& b) {
    a.Swap(&b);
  }
  inline void Swap(SystemAlert* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SystemAlert* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SystemAlert* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SystemAlert>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SystemAlert& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SystemAlert& from) {
    SystemAlert::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SystemAlert* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "cordum.agent.v1.SystemAlert";
  }
  protected:
  explicit SystemAlert(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  enum : int {
    kDetailsFieldNumber = 8,
    kLevelFieldNumber = 1,
    kMessageFieldNumber = 2,
    kComponentFieldNumber = 3,
    kCodeFieldNumber = 4,
    kSourceComponentFieldNumber = 7,
    kTraceIdFieldNumber = 9,
    kSeverityFieldNumber = 5,
    kErrorCodeEnumFieldNumber = 6,
  };
  // map<string, string> details = 8 [json_name = "details"];
  int details_size() const;
  private:
  int _internal_details_size() const;
  public:
  void clear_details();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >&
      _internal_details() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >*
      _internal_mutable_details();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >&
      details() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >*
      mutable_details();

  // string level = 1 [json_name = "level", deprecated = true];
  PROTOBUF_DEPRECATED void clear_level();
  PROTOBUF_DEPRECATED const std::string& level() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  PROTOBUF_DEPRECATED void set_level(ArgT0&& arg0, ArgT... args);
  PROTOBUF_DEPRECATED std::string* mutable_level();
  PROTOBUF_NODISCARD PROTOBUF_DEPRECATED std::string* release_level();
  PROTOBUF_DEPRECATED void set_allocated_level(std::string* level);
  private:
  const std::string& _internal_level() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_level(const std::string& value);
  std::string* _internal_mutable_level();
  public:

  // string message = 2 [json_name = "message"];
  void clear_message();
  const std::string& message() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_message(ArgT0&& arg0, ArgT... args);
  std::string* mutable_message();
  PROTOBUF_NODISCARD std::string* release_message();
  void set_allocated_message(std::string* message);
  private:
  const std::string& _internal_message() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_message(const std::string& value);
  std::string* _internal_mutable_message();
  public:

  // string component = 3 [json_name = "component", deprecated = true];
  PROTOBUF_DEPRECATED void clear_component();
  PROTOBUF_DEPRECATED const std::string& component() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  PROTOBUF_DEPRECATED void set_component(ArgT0&& arg0, ArgT... args);
  PROTOBUF_DEPRECATED std::string* mutable_component();
  PROTOBUF_NODISCARD PROTOBUF_DEPRECATED std::string* release_component();
  PROTOBUF_DEPRECATED void set_allocated_component(std::string* component);
  private:
  const std::string& _internal_component() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_component(const std::string& value);
  std::string* _internal_mutable_component();
  public:

  // string code = 4 [json_name = "code", deprecated = true];
  PROTOBUF_DEPRECATED void clear_code();
  PROTOBUF_DEPRECATED const std::string& code() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  PROTOBUF_DEPRECATED void set_code(ArgT0&& arg0, ArgT... args);
  PROTOBUF_DEPRECATED std::string* mutable_code();
  PROTOBUF_NODISCARD PROTOBUF_DEPRECATED std::string* release_code();
  PROTOBUF_DEPRECATED void set_allocated_code(std::string* code);
  private:
  const std::string& _internal_code() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_code(const std::string& value);
  std::string* _internal_mutable_code();
  public:

  // string source_component = 7 [json_name = "sourceComponent"];
  void clear_source_component();
  const std::string& source_component() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_source_component(ArgT0&& arg0, ArgT... args);
  std::string* mutable_source_component();
  PROTOBUF_NODISCARD std::string* release_source_component();
  void set_allocated_source_component(std::string* source_component);
  private:
  const std::string& _internal_source_component() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_source_component(const std::string& value);
  std::string* _internal_mutable_source_component();
  public:

  // string trace_id = 9 [json_name = "traceId"];
  void clear_trace_id();
  const std::string& trace_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_trace_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_trace_id();
  PROTOBUF_NODISCARD std::string* release_trace_id();
  void set_allocated_trace_id(std::string* trace_id);
  private:
  const std::string& _internal_trace_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_trace_id(const std::string& value);
  std::string* _internal_mutable_trace_id();
  public:

  // .cordum.agent.v1.AlertSeverity severity = 5 [json_name = "severity"];
  void clear_severity();
  ::cordum::agent::v1::AlertSeverity severity() const;
  void set_severity(::cordum::agent::v1::AlertSeverity value);
  private:
  ::cordum::agent::v1::AlertSeverity _internal_severity() const;
  void _internal_set_severity(::cordum::agent::v1::AlertSeverity value);
  public:

  // .cordum.agent.v1.ErrorCode error_code_enum = 6 [json_name = "errorCodeEnum"];
  void clear_error_code_enum();
  ::cordum::agent::v1::ErrorCode error_code_enum() const;
  void set_error_code_enum(::cordum::agent::v1::ErrorCode value);
  private:
  ::cordum::agent::v1::ErrorCode _internal_error_code_enum() const;
  void _internal_set_error_code_enum(::cordum::agent::v1::ErrorCode value);
  public:

  // @@protoc_insertion_point(class_scope:cordum.agent.v1.SystemAlert)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::MapField<
        SystemAlert_DetailsEntry_DoNotUse,
        std::string, std::string,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING> details_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr level_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr message_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr component_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr code_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr source_component_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr trace_id_;
    int severity_;
    int error_code_enum_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_cordum_2fagent_2fv1_2falert_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// SystemAlert

// string level = 1 [json_name = "level", deprecated = true];
inline void SystemAlert::clear_level() {
  _impl_.level_.ClearToEmpty();
}
inline const std::string& SystemAlert::level() const {
  // @@protoc_insertion_point(field_get:cordum.agent.v1.SystemAlert.level)
  return _internal_level();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SystemAlert::set_level(ArgT0&& arg0, ArgT... args) {
 
 _impl_.level_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:cordum.agent.v1.SystemAlert.level)
}
inline std::string* SystemAlert::mutable_level() {
  std::string* _s = _internal_mutable_level();
  // @@protoc_insertion_point(field_mutable:cordum.agent.v1.SystemAlert.level)
  return _s;
}
inline const std::string& SystemAlert::_internal_level() const {
  return _impl_.level_.Get();
}
inline void SystemAlert::_internal_set_level(const std::string& value) {
  
  _impl_.level_.Set(value, GetArenaForAllocation());
}
inline std::string* SystemAlert::_internal_mutable_level() {
  
  return _impl_.level_.Mutable(GetArenaForAllocation());
}
inline std::string* SystemAlert::release_level() {
  // @@protoc_insertion_point(field_release:cordum.agent.v1.SystemAlert.level)
  return _impl_.level_.Release();
}
inline void SystemAlert::set_allocated_level(std::string* level) {
  if (level != nullptr) {
    
  } else {
    
  }
  _impl_.level_.SetAllocated(level, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.level_.IsDefault()) {
    _impl_.level_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:cordum.agent.v1.SystemAlert.level)
}

// string message = 2 [json_name = "message"];
inline void SystemAlert::clear_message() {
  _impl_.message_.ClearToEmpty();
}
inline const std::string& SystemAlert::message() const {
  // @@protoc_insertion_point(field_get:cordum.agent.v1.SystemAlert.message)
  return _internal_message();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SystemAlert::set_message(ArgT0&& arg0, ArgT... args) {
 
 _impl_.message_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:cordum.agent.v1.SystemAlert.message)
}
inline std::string* SystemAlert::mutable_message() {
  std::string* _s = _internal_mutable_message();
  // @@protoc_insertion_point(field_mutable:cordum.agent.v1.SystemAlert.message)
  return _s;
}
inline const std::string& SystemAlert::_internal_message() const {
  return _impl_.message_.Get();
}
inline void SystemAlert::_internal_set_message(const std::string& value) {
  
  _impl_.message_.Set(value, GetArenaForAllocation());
}
inline std::string* SystemAlert::_internal_mutable_message() {
  
  return _impl_.message_.Mutable(GetArenaForAllocation());
}
inline std::string* SystemAlert::release_message() {
  // @@protoc_insertion_point(field_release:cordum.agent.v1.SystemAlert.message)
  return _impl_.message_.Release();
}
inline void SystemAlert::set_allocated_message(std::string* message) {
  if (message != nullptr) {
    
  } else {
    
  }
  _impl_.message_.SetAllocated(message, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.message_.IsDefault()) {
    _impl_.message_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:cordum.agent.v1.SystemAlert.message)
}

// string component = 3 [json_name = "component", deprecated = true];
inline void SystemAlert::clear_component() {
  _impl_.component_.ClearToEmpty();
}
inline const std::string& SystemAlert::component() const {
  // @@protoc_insertion_point(field_get:cordum.agent.v1.SystemAlert.component)
  return _internal_component();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SystemAlert::set_component(ArgT0&& arg0, ArgT... args) {
 
 _impl_.component_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:cordum.agent.v1.SystemAlert.component)
}
inline std::string* SystemAlert::mutable_component() {
  std::string* _s = _internal_mutable_component();
  // @@protoc_insertion_point(field_mutable:cordum.agent.v1.SystemAlert.component)
  return _s;
}
inline const std::string& SystemAlert::_internal_component() const {
  return _impl_.component_.Get();
}
inline void SystemAlert::_internal_set_component(const std::string& value) {
  
  _impl_.component_.Set(value, GetArenaForAllocation());
}
inline std::string* SystemAlert::_internal_mutable_component() {
  
  return _impl_.component_.Mutable(GetArenaForAllocation());
}
inline std::string* SystemAlert::release_component() {
  // @@protoc_insertion_point(field_release:cordum.agent.v1.SystemAlert.component)
  return _impl_.component_.Release();
}
inline void SystemAlert::set_allocated_component(std::string* component) {
  if (component != nullptr) {
    
  } else {
    
  }
  _impl_.component_.SetAllocated(component, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.component_.IsDefault()) {
    _impl_.component_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:cordum.agent.v1.SystemAlert.component)
}

// string code = 4 [json_name = "code", deprecated = true];
inline void SystemAlert::clear_code() {
  _impl_.code_.ClearToEmpty();
}
inline const std::string& SystemAlert::code() const {
  // @@protoc_insertion_point(field_get:cordum.agent.v1.SystemAlert.code)
  return _internal_code();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SystemAlert::set_code(ArgT0&& arg0, ArgT... args) {
 
 _impl_.code_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:cordum.agent.v1.SystemAlert.code)
}
inline std::string* SystemAlert::mutable_code() {
  std::string* _s = _internal_mutable_code();
  // @@protoc_insertion_point(field_mutable:cordum.agent.v1.SystemAlert.code)
  return _s;
}
inline const std::string& SystemAlert::_internal_code() const {
  return _impl_.code_.Get();
}
inline void SystemAlert::_internal_set_code(const std::string& value) {
  
  _impl_.code_.Set(value, GetArenaForAllocation());
}
inline std::string* SystemAlert::_internal_mutable_code() {
  
  return _impl_.code_.Mutable(GetArenaForAllocation());
}
inline std::string* SystemAlert::release_code() {
  // @@protoc_insertion_point(field_release:cordum.agent.v1.SystemAlert.code)
  return _impl_.code_.Release();
}
inline void SystemAlert::set_allocated_code(std::string* code) {
  if (code != nullptr) {
    
  } else {
    
  }
  _impl_.code_.SetAllocated(code, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.code_.IsDefault()) {
    _impl_.code_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:cordum.agent.v1.SystemAlert.code)
}

// .cordum.agent.v1.AlertSeverity severity = 5 [json_name = "severity"];
inline void SystemAlert::clear_severity() {
  _impl_.severity_ = 0;
}
inline ::cordum::agent::v1::AlertSeverity SystemAlert::_internal_severity() const {
  return static_cast< ::cordum::agent::v1::AlertSeverity >(_impl_.severity_);
}
inline ::cordum::agent::v1::AlertSeverity SystemAlert::severity() const {
  // @@protoc_insertion_point(field_get:cordum.agent.v1.SystemAlert.severity)
  return _internal_severity();
}
inline void SystemAlert::_internal_set_severity(::cordum::agent::v1::AlertSeverity value) {
  
  _impl_.severity_ = value;
}
inline void SystemAlert::set_severity(::cordum::agent::v1::AlertSeverity value) {
  _internal_set_severity(value);
  // @@protoc_insertion_point(field_set:cordum.agent.v1.SystemAlert.severity)
}

// .cordum.agent.v1.ErrorCode error_code_enum = 6 [json_name = "errorCodeEnum"];
inline void SystemAlert::clear_error_code_enum() {
  _impl_.error_code_enum_ = 0;
}
inline ::cordum::agent::v1::ErrorCode SystemAlert::_internal_error_code_enum() const {
  return static_cast< ::cordum::agent::v1::ErrorCode >(_impl_.error_code_enum_);
}
inline ::cordum::agent::v1::ErrorCode SystemAlert::error_code_enum() const {
  // @@protoc_insertion_point(field_get:cordum.agent.v1.SystemAlert.error_code_enum)
  return _internal_error_code_enum();
}
inline void SystemAlert::_internal_set_error_code_enum(::cordum::agent::v1::ErrorCode value) {
  
  _impl_.error_code_enum_ = value;
}
inline void SystemAlert::set_error_code_enum(::cordum::agent::v1::ErrorCode value) {
  _internal_set_error_code_enum(value);
  // @@protoc_insertion_point(field_set:cordum.agent.v1.SystemAlert.error_code_enum)
}

// string source_component = 7 [json_name = "sourceComponent"];
inline void SystemAlert::clear_source_component() {
  _impl_.source_component_.ClearToEmpty();
}
inline const std::string& SystemAlert::source_component() const {
  // @@protoc_insertion_point(field_get:cordum.agent.v1.SystemAlert.source_component)
  return _internal_source_component();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SystemAlert::set_source_component(ArgT0&& arg0, ArgT... args) {
 
 _impl_.source_component_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:cordum.agent.v1.SystemAlert.source_component)
}
inline std::string* SystemAlert::mutable_source_component() {
  std::string* _s = _internal_mutable_source_component();
  // @@protoc_insertion_point(field_mutable:cordum.agent.v1.SystemAlert.source_component)
  return _s;
}
inline const std::string& SystemAlert::_internal_source_component() const {
  return _impl_.source_component_.Get();
}
inline void SystemAlert::_internal_set_source_component(const std::string& value) {
  
  _impl_.source_component_.Set(value, GetArenaForAllocation());
}
inline std::string* SystemAlert::_internal_mutable_source_component() {
  
  return _impl_.source_component_.Mutable(GetArenaForAllocation());
}
inline std::string* SystemAlert::release_source_component() {
  // @@protoc_insertion_point(field_release:cordum.agent.v1.SystemAlert.source_component)
  return _impl_.source_component_.Release();
}
inline void SystemAlert::set_allocated_source_component(std::string* source_component) {
  if (source_component != nullptr) {
    
  } else {
    
  }
  _impl_.source_component_.SetAllocated(source_component, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.source_component_.IsDefault()) {
    _impl_.source_component_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:cordum.agent.v1.SystemAlert.source_component)
}

// map<string, string> details = 8 [json_name = "details"];
inline int SystemAlert::_internal_details_size() const {
  return _impl_.details_.size();
}
inline int SystemAlert::details_size() const {
  return _internal_details_size();
}
inline void SystemAlert::clear_details() {
  _impl_.details_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >&
SystemAlert::_internal_details() const {
  return _impl_.details_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >&
SystemAlert::details() const {
  // @@protoc_insertion_point(field_map:cordum.agent.v1.SystemAlert.details)
  return _internal_details();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >*
SystemAlert::_internal_mutable_details() {
  return _impl_.details_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >*
SystemAlert::mutable_details() {
  // @@protoc_insertion_point(field_mutable_map:cordum.agent.v1.SystemAlert.details)
  return _internal_mutable_details();
}

// string trace_id = 9 [json_name = "traceId"];
inline void SystemAlert::clear_trace_id() {
  _impl_.trace_id_.ClearToEmpty();
}
inline const std::string& SystemAlert::trace_id() const {
  // @@protoc_insertion_point(field_get:cordum.agent.v1.SystemAlert.trace_id)
  return _internal_trace_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SystemAlert::set_trace_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.trace_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:cordum.agent.v1.SystemAlert.trace_id)
}
inline std::string* SystemAlert::mutable_trace_id() {
  std::string* _s = _internal_mutable_trace_id();
  // @@protoc_insertion_point(field_mutable:cordum.agent.v1.SystemAlert.trace_id)
  return _s;
}
inline const std::string& SystemAlert::_internal_trace_id() const {
  return _impl_.trace_id_.Get();
}
inline void SystemAlert::_internal_set_trace_id(const std::string& value) {
  
  _impl_.trace_id_.Set(value, GetArenaForAllocation());
}
inline std::string* SystemAlert::_internal_mutable_trace_id() {
  
  return _impl_.trace_id_.Mutable(GetArenaForAllocation());
}
inline std::string* SystemAlert::release_trace_id() {
  // @@protoc_insertion_point(field_release:cordum.agent.v1.SystemAlert.trace_id)
  return _impl_.trace_id_.Release();
}
inline void SystemAlert::set_allocated_trace_id(std::string* trace_id) {
  if (trace_id != nullptr) {
    
  } else {
    
  }
  _impl_.trace_id_.SetAllocated(trace_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.trace_id_.IsDefault()) {
    _impl_.trace_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:cordum.agent.v1.SystemAlert.trace_id)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace v1
}  // namespace agent
}  // namespace cordum

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::cordum::agent::v1::AlertSeverity> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::cordum::agent::v1::AlertSeverity>() {
  return ::cordum::agent::v1::AlertSeverity_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_cordum_2fagent_2fv1_2falert_2eproto
