// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cordum/agent/v1/buspacket.proto

#include "cordum/agent/v1/buspacket.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace cordum {
namespace agent {
namespace v1 {
PROTOBUF_CONSTEXPR BusPacket::BusPacket(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.trace_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.sender_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.signature_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.auth_token_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.created_at_)*/nullptr
  , /*decltype(_impl_.protocol_version_)*/0
  , /*decltype(_impl_.payload_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_._oneof_case_)*/{}} {}
struct BusPacketDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BusPacketDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~BusPacketDefaultTypeInternal() {}
  union {
    BusPacket _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BusPacketDefaultTypeInternal _BusPacket_default_instance_;
}  // namespace v1
}  // namespace agent
}  // namespace cordum
static ::_pb::Metadata file_level_metadata_cordum_2fagent_2fv1_2fbuspacket_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_cordum_2fagent_2fv1_2fbuspacket_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_cordum_2fagent_2fv1_2fbuspacket_2eproto = nullptr;

const uint32_t TableStruct_cordum_2fagent_2fv1_2fbuspacket_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::cordum::agent::v1::BusPacket, _internal_metadata_),
  ~0u,  // no _extensions_
  PROTOBUF_FIELD_OFFSET(::cordum::agent::v1::BusPacket, _impl_._oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::cordum::agent::v1::BusPacket, _impl_.trace_id_),
  PROTOBUF_FIELD_OFFSET(::cordum::agent::v1::BusPacket, _impl_.sender_id_),
  PROTOBUF_FIELD_OFFSET(::cordum::agent::v1::BusPacket, _impl_.created_at_),
  PROTOBUF_FIELD_OFFSET(::cordum::agent::v1::BusPacket, _impl_.protocol_version_),
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  PROTOBUF_FIELD_OFFSET(::cordum::agent::v1::BusPacket, _impl_.signature_),
  PROTOBUF_FIELD_OFFSET(::cordum::agent::v1::BusPacket, _impl_.auth_token_),
  PROTOBUF_FIELD_OFFSET(::cordum::agent::v1::BusPacket, _impl_.payload_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::cordum::agent::v1::BusPacket)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::cordum::agent::v1::_BusPacket_default_instance_._instance,
};

const char descriptor_table_protodef_cordum_2fagent_2fv1_2fbuspacket_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\037cordum/agent/v1/buspacket.proto\022\017cordu"
  "m.agent.v1\032\037google/protobuf/timestamp.pr"
  "oto\032\031cordum/agent/v1/job.proto\032\037cordum/a"
  "gent/v1/heartbeat.proto\032\033cordum/agent/v1"
  "/alert.proto\032\037cordum/agent/v1/handshake."
  "proto\"\336\010\n\tBusPacket\022\031\n\010trace_id\030\001 \001(\tR\007t"
  "raceId\022\033\n\tsender_id\030\002 \001(\tR\010senderId\0229\n\nc"
  "reated_at\030\003 \001(\0132\032.google.protobuf.Timest"
  "ampR\tcreatedAt\022)\n\020protocol_version\030\004 \001(\005"
  "R\017protocolVersion\022>\n\013job_request\030\n \001(\0132\033"
  ".cordum.agent.v1.JobRequestH\000R\njobReques"
  "t\022;\n\njob_result\030\013 \001(\0132\032.cordum.agent.v1."
  "JobResultH\000R\tjobResult\022:\n\theartbeat\030\014 \001("
  "\0132\032.cordum.agent.v1.HeartbeatH\000R\theartbe"
  "at\0224\n\005alert\030\r \001(\0132\034.cordum.agent.v1.Syst"
  "emAlertH\000R\005alert\022A\n\014job_progress\030\017 \001(\0132\034"
  ".cordum.agent.v1.JobProgressH\000R\013jobProgr"
  "ess\022;\n\njob_cancel\030\020 \001(\0132\032.cordum.agent.v"
  "1.JobCancelH\000R\tjobCancel\022:\n\thandshake\030\021 "
  "\001(\0132\032.cordum.agent.v1.HandshakeH\000R\thands"
  "hake\022\177\n\"worker_handshake_challenge_reque"
  "st\030\023 \001(\01320.cordum.agent.v1.WorkerHandsha"
  "keChallengeRequestH\000R\037workerHandshakeCha"
  "llengeRequest\022i\n\032worker_handshake_challe"
  "nge\030\024 \001(\0132).cordum.agent.v1.WorkerHandsh"
  "akeChallengeH\000R\030workerHandshakeChallenge"
  "\022r\n\035worker_handshake_authenticate\030\025 \001(\0132"
  ",.cordum.agent.v1.WorkerHandshakeAuthent"
  "icateH\000R\033workerHandshakeAuthenticate\022`\n\027"
  "worker_handshake_result\030\026 \001(\0132&.cordum.a"
  "gent.v1.WorkerHandshakeResultH\000R\025workerH"
  "andshakeResult\022\034\n\tsignature\030\016 \001(\014R\tsigna"
  "ture\022\035\n\nauth_token\030\022 \001(\tR\tauthTokenB\t\n\007p"
  "ayloadB\177\n\026io.cordum.cap.agent.v1P\001Z+gith"
  "ub.com/cordum-io/cap/v2/cordum/agent/v1\252"
  "\002\017Cordum.Agent.V1\312\002\017cordum\\Agent\\V1\352\002\021Co"
  "rdum::Agent::V1b\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_cordum_2fagent_2fv1_2fbuspacket_2eproto_deps[5] = {
  &::descriptor_table_cordum_2fagent_2fv1_2falert_2eproto,
  &::descriptor_table_cordum_2fagent_2fv1_2fhandshake_2eproto,
  &::descriptor_table_cordum_2fagent_2fv1_2fheartbeat_2eproto,
  &::descriptor_table_cordum_2fagent_2fv1_2fjob_2eproto,
  &::descriptor_table_google_2fprotobuf_2ftimestamp_2eproto,
};
static ::_pbi::once_flag descriptor_table_cordum_2fagent_2fv1_2fbuspacket_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_cordum_2fagent_2fv1_2fbuspacket_2eproto = {
    false, false, 1463, descriptor_table_protodef_cordum_2fagent_2fv1_2fbuspacket_2eproto,
    "cordum/agent/v1/buspacket.proto",
    &descriptor_table_cordum_2fagent_2fv1_2fbuspacket_2eproto_once, descriptor_table_cordum_2fagent_2fv1_2fbuspacket_2eproto_deps, 5, 1,
    schemas, file_default_instances, TableStruct_cordum_2fagent_2fv1_2fbuspacket_2eproto::offsets,
    file_level_metadata_cordum_2fagent_2fv1_2fbuspacket_2eproto, file_level_enum_descriptors_cordum_2fagent_2fv1_2fbuspacket_2eproto,
    file_level_service_descriptors_cordum_2fagent_2fv1_2fbuspacket_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_cordum_2fagent_2fv1_2fbuspacket_2eproto_getter() {
  return &descriptor_table_cordum_2fagent_2fv1_2fbuspacket_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_cordum_2fagent_2fv1_2fbuspacket_2eproto(&descriptor_table_cordum_2fagent_2fv1_2fbuspacket_2eproto);
namespace cordum {
namespace agent {
namespace v1 {

// ===================================================================

class BusPacket::_Internal {
 public:
  static const ::PROTOBUF_NAMESPACE_ID::Timestamp& created_at(const BusPacket* msg);
  static const ::cordum::agent::v1::JobRequest& job_request(const BusPacket* msg);
  static const ::cordum::agent::v1::JobResult& job_result(const BusPacket* msg);
  static const ::cordum::agent::v1::Heartbeat& heartbeat(const BusPacket* msg);
  static const ::cordum::agent::v1::SystemAlert& alert(const BusPacket* msg);
  static const ::cordum::agent::v1::JobProgress& job_progress(const BusPacket* msg);
  static const ::cordum::agent::v1::JobCancel& job_cancel(const BusPacket* msg);
  static const ::cordum::agent::v1::Handshake& handshake(const BusPacket* msg);
  static const ::cordum::agent::v1::WorkerHandshakeChallengeRequest& worker_handshake_challenge_request(const BusPacket* msg);
  static const ::cordum::agent::v1::WorkerHandshakeChallenge& worker_handshake_challenge(const BusPacket* msg);
  static const ::cordum::agent::v1::WorkerHandshakeAuthenticate& worker_handshake_authenticate(const BusPacket* msg);
  static const ::cordum::agent::v1::WorkerHandshakeResult& worker_handshake_result(const BusPacket* msg);
};

const ::PROTOBUF_NAMESPACE_ID::Timestamp&
BusPacket::_Internal::created_at(const BusPacket* msg) {
  return *msg->_impl_.created_at_;
}
const ::cordum::agent::v1::JobRequest&
BusPacket::_Internal::job_request(const BusPacket* msg) {
  return *msg->_impl_.payload_.job_request_;
}
const ::cordum::agent::v1::JobResult&
BusPacket::_Internal::job_result(const BusPacket* msg) {
  return *msg->_impl_.payload_.job_result_;
}
const ::cordum::agent::v1::Heartbeat&
BusPacket::_Internal::heartbeat(const BusPacket* msg) {
  return *msg->_impl_.payload_.heartbeat_;
}
const ::cordum::agent::v1::SystemAlert&
BusPacket::_Internal::alert(const BusPacket* msg) {
  return *msg->_impl_.payload_.alert_;
}
const ::cordum::agent::v1::JobProgress&
BusPacket::_Internal::job_progress(const BusPacket* msg) {
  return *msg->_impl_.payload_.job_progress_;
}
const ::cordum::agent::v1::JobCancel&
BusPacket::_Internal::job_cancel(const BusPacket* msg) {
  return *msg->_impl_.payload_.job_cancel_;
}
const ::cordum::agent::v1::Handshake&
BusPacket::_Internal::handshake(const BusPacket* msg) {
  return *msg->_impl_.payload_.handshake_;
}
const ::cordum::agent::v1::WorkerHandshakeChallengeRequest&
BusPacket::_Internal::worker_handshake_challenge_request(const BusPacket* msg) {
  return *msg->_impl_.payload_.worker_handshake_challenge_request_;
}
const ::cordum::agent::v1::WorkerHandshakeChallenge&
BusPacket::_Internal::worker_handshake_challenge(const BusPacket* msg) {
  return *msg->_impl_.payload_.worker_handshake_challenge_;
}
const ::cordum::agent::v1::WorkerHandshakeAuthenticate&
BusPacket::_Internal::worker_handshake_authenticate(const BusPacket* msg) {
  return *msg->_impl_.payload_.worker_handshake_authenticate_;
}
const ::cordum::agent::v1::WorkerHandshakeResult&
BusPacket::_Internal::worker_handshake_result(const BusPacket* msg) {
  return *msg->_impl_.payload_.worker_handshake_result_;
}
void BusPacket::clear_created_at() {
  if (GetArenaForAllocation() == nullptr && _impl_.created_at_ != nullptr) {
    delete _impl_.created_at_;
  }
  _impl_.created_at_ = nullptr;
}
void BusPacket::set_allocated_job_request(::cordum::agent::v1::JobRequest* job_request) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_payload();
  if (job_request) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(job_request));
    if (message_arena != submessage_arena) {
      job_request = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, job_request, submessage_arena);
    }
    set_has_job_request();
    _impl_.payload_.job_request_ = job_request;
  }
  // @@protoc_insertion_point(field_set_allocated:cordum.agent.v1.BusPacket.job_request)
}
void BusPacket::clear_job_request() {
  if (_internal_has_job_request()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.payload_.job_request_;
    }
    clear_has_payload();
  }
}
void BusPacket::set_allocated_job_result(::cordum::agent::v1::JobResult* job_result) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_payload();
  if (job_result) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(job_result));
    if (message_arena != submessage_arena) {
      job_result = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, job_result, submessage_arena);
    }
    set_has_job_result();
    _impl_.payload_.job_result_ = job_result;
  }
  // @@protoc_insertion_point(field_set_allocated:cordum.agent.v1.BusPacket.job_result)
}
void BusPacket::clear_job_result() {
  if (_internal_has_job_result()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.payload_.job_result_;
    }
    clear_has_payload();
  }
}
void BusPacket::set_allocated_heartbeat(::cordum::agent::v1::Heartbeat* heartbeat) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_payload();
  if (heartbeat) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(heartbeat));
    if (message_arena != submessage_arena) {
      heartbeat = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, heartbeat, submessage_arena);
    }
    set_has_heartbeat();
    _impl_.payload_.heartbeat_ = heartbeat;
  }
  // @@protoc_insertion_point(field_set_allocated:cordum.agent.v1.BusPacket.heartbeat)
}
void BusPacket::clear_heartbeat() {
  if (_internal_has_heartbeat()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.payload_.heartbeat_;
    }
    clear_has_payload();
  }
}
void BusPacket::set_allocated_alert(::cordum::agent::v1::SystemAlert* alert) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_payload();
  if (alert) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(alert));
    if (message_arena != submessage_arena) {
      alert = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, alert, submessage_arena);
    }
    set_has_alert();
    _impl_.payload_.alert_ = alert;
  }
  // @@protoc_insertion_point(field_set_allocated:cordum.agent.v1.BusPacket.alert)
}
void BusPacket::clear_alert() {
  if (_internal_has_alert()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.payload_.alert_;
    }
    clear_has_payload();
  }
}
void BusPacket::set_allocated_job_progress(::cordum::agent::v1::JobProgress* job_progress) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_payload();
  if (job_progress) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(job_progress));
    if (message_arena != submessage_arena) {
      job_progress = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, job_progress, submessage_arena);
    }
    set_has_job_progress();
    _impl_.payload_.job_progress_ = job_progress;
  }
  // @@protoc_insertion_point(field_set_allocated:cordum.agent.v1.BusPacket.job_progress)
}
void BusPacket::clear_job_progress() {
  if (_internal_has_job_progress()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.payload_.job_progress_;
    }
    clear_has_payload();
  }
}
void BusPacket::set_allocated_job_cancel(::cordum::agent::v1::JobCancel* job_cancel) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_payload();
  if (job_cancel) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(job_cancel));
    if (message_arena != submessage_arena) {
      job_cancel = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, job_cancel, submessage_arena);
    }
    set_has_job_cancel();
    _impl_.payload_.job_cancel_ = job_cancel;
  }
  // @@protoc_insertion_point(field_set_allocated:cordum.agent.v1.BusPacket.job_cancel)
}
void BusPacket::clear_job_cancel() {
  if (_internal_has_job_cancel()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.payload_.job_cancel_;
    }
    clear_has_payload();
  }
}
void BusPacket::set_allocated_handshake(::cordum::agent::v1::Handshake* handshake) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_payload();
  if (handshake) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(handshake));
    if (message_arena != submessage_arena) {
      handshake = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, handshake, submessage_arena);
    }
    set_has_handshake();
    _impl_.payload_.handshake_ = handshake;
  }
  // @@protoc_insertion_point(field_set_allocated:cordum.agent.v1.BusPacket.handshake)
}
void BusPacket::clear_handshake() {
  if (_internal_has_handshake()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.payload_.handshake_;
    }
    clear_has_payload();
  }
}
void BusPacket::set_allocated_worker_handshake_challenge_request(::cordum::agent::v1::WorkerHandshakeChallengeRequest* worker_handshake_challenge_request) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_payload();
  if (worker_handshake_challenge_request) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(worker_handshake_challenge_request));
    if (message_arena != submessage_arena) {
      worker_handshake_challenge_request = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, worker_handshake_challenge_request, submessage_arena);
    }
    set_has_worker_handshake_challenge_request();
    _impl_.payload_.worker_handshake_challenge_request_ = worker_handshake_challenge_request;
  }
  // @@protoc_insertion_point(field_set_allocated:cordum.agent.v1.BusPacket.worker_handshake_challenge_request)
}
void BusPacket::clear_worker_handshake_challenge_request() {
  if (_internal_has_worker_handshake_challenge_request()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.payload_.worker_handshake_challenge_request_;
    }
    clear_has_payload();
  }
}
void BusPacket::set_allocated_worker_handshake_challenge(::cordum::agent::v1::WorkerHandshakeChallenge* worker_handshake_challenge) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_payload();
  if (worker_handshake_challenge) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(worker_handshake_challenge));
    if (message_arena != submessage_arena) {
      worker_handshake_challenge = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, worker_handshake_challenge, submessage_arena);
    }
    set_has_worker_handshake_challenge();
    _impl_.payload_.worker_handshake_challenge_ = worker_handshake_challenge;
  }
  // @@protoc_insertion_point(field_set_allocated:cordum.agent.v1.BusPacket.worker_handshake_challenge)
}
void BusPacket::clear_worker_handshake_challenge() {
  if (_internal_has_worker_handshake_challenge()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.payload_.worker_handshake_challenge_;
    }
    clear_has_payload();
  }
}
void BusPacket::set_allocated_worker_handshake_authenticate(::cordum::agent::v1::WorkerHandshakeAuthenticate* worker_handshake_authenticate) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_payload();
  if (worker_handshake_authenticate) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(worker_handshake_authenticate));
    if (message_arena != submessage_arena) {
      worker_handshake_authenticate = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, worker_handshake_authenticate, submessage_arena);
    }
    set_has_worker_handshake_authenticate();
    _impl_.payload_.worker_handshake_authenticate_ = worker_handshake_authenticate;
  }
  // @@protoc_insertion_point(field_set_allocated:cordum.agent.v1.BusPacket.worker_handshake_authenticate)
}
void BusPacket::clear_worker_handshake_authenticate() {
  if (_internal_has_worker_handshake_authenticate()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.payload_.worker_handshake_authenticate_;
    }
    clear_has_payload();
  }
}
void BusPacket::set_allocated_worker_handshake_result(::cordum::agent::v1::WorkerHandshakeResult* worker_handshake_result) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_payload();
  if (worker_handshake_result) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(worker_handshake_result));
    if (message_arena != submessage_arena) {
      worker_handshake_result = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, worker_handshake_result, submessage_arena);
    }
    set_has_worker_handshake_result();
    _impl_.payload_.worker_handshake_result_ = worker_handshake_result;
  }
  // @@protoc_insertion_point(field_set_allocated:cordum.agent.v1.BusPacket.worker_handshake_result)
}
void BusPacket::clear_worker_handshake_result() {
  if (_internal_has_worker_handshake_result()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.payload_.worker_handshake_result_;
    }
    clear_has_payload();
  }
}
BusPacket::BusPacket(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:cordum.agent.v1.BusPacket)
}
BusPacket::BusPacket(const BusPacket& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  BusPacket* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.trace_id_){}
    , decltype(_impl_.sender_id_){}
    , decltype(_impl_.signature_){}
    , decltype(_impl_.auth_token_){}
    , decltype(_impl_.created_at_){nullptr}
    , decltype(_impl_.protocol_version_){}
    , decltype(_impl_.payload_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.trace_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.trace_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_trace_id().empty()) {
    _this->_impl_.trace_id_.Set(from._internal_trace_id(), 
      _this->GetArenaForAllocation());
  }
  _impl_.sender_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.sender_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_sender_id().empty()) {
    _this->_impl_.sender_id_.Set(from._internal_sender_id(), 
      _this->GetArenaForAllocation());
  }
  _impl_.signature_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.signature_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_signature().empty()) {
    _this->_impl_.signature_.Set(from._internal_signature(), 
      _this->GetArenaForAllocation());
  }
  _impl_.auth_token_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.auth_token_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_auth_token().empty()) {
    _this->_impl_.auth_token_.Set(from._internal_auth_token(), 
      _this->GetArenaForAllocation());
  }
  if (from._internal_has_created_at()) {
    _this->_impl_.created_at_ = new ::PROTOBUF_NAMESPACE_ID::Timestamp(*from._impl_.created_at_);
  }
  _this->_impl_.protocol_version_ = from._impl_.protocol_version_;
  clear_has_payload();
  switch (from.payload_case()) {
    case kJobRequest: {
      _this->_internal_mutable_job_request()->::cordum::agent::v1::JobRequest::MergeFrom(
          from._internal_job_request());
      break;
    }
    case kJobResult: {
      _this->_internal_mutable_job_result()->::cordum::agent::v1::JobResult::MergeFrom(
          from._internal_job_result());
      break;
    }
    case kHeartbeat: {
      _this->_internal_mutable_heartbeat()->::cordum::agent::v1::Heartbeat::MergeFrom(
          from._internal_heartbeat());
      break;
    }
    case kAlert: {
      _this->_internal_mutable_alert()->::cordum::agent::v1::SystemAlert::MergeFrom(
          from._internal_alert());
      break;
    }
    case kJobProgress: {
      _this->_internal_mutable_job_progress()->::cordum::agent::v1::JobProgress::MergeFrom(
          from._internal_job_progress());
      break;
    }
    case kJobCancel: {
      _this->_internal_mutable_job_cancel()->::cordum::agent::v1::JobCancel::MergeFrom(
          from._internal_job_cancel());
      break;
    }
    case kHandshake: {
      _this->_internal_mutable_handshake()->::cordum::agent::v1::Handshake::MergeFrom(
          from._internal_handshake());
      break;
    }
    case kWorkerHandshakeChallengeRequest: {
      _this->_internal_mutable_worker_handshake_challenge_request()->::cordum::agent::v1::WorkerHandshakeChallengeRequest::MergeFrom(
          from._internal_worker_handshake_challenge_request());
      break;
    }
    case kWorkerHandshakeChallenge: {
      _this->_internal_mutable_worker_handshake_challenge()->::cordum::agent::v1::WorkerHandshakeChallenge::MergeFrom(
          from._internal_worker_handshake_challenge());
      break;
    }
    case kWorkerHandshakeAuthenticate: {
      _this->_internal_mutable_worker_handshake_authenticate()->::cordum::agent::v1::WorkerHandshakeAuthenticate::MergeFrom(
          from._internal_worker_handshake_authenticate());
      break;
    }
    case kWorkerHandshakeResult: {
      _this->_internal_mutable_worker_handshake_result()->::cordum::agent::v1::WorkerHandshakeResult::MergeFrom(
          from._internal_worker_handshake_result());
      break;
    }
    case PAYLOAD_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:cordum.agent.v1.BusPacket)
}

inline void BusPacket::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.trace_id_){}
    , decltype(_impl_.sender_id_){}
    , decltype(_impl_.signature_){}
    , decltype(_impl_.auth_token_){}
    , decltype(_impl_.created_at_){nullptr}
    , decltype(_impl_.protocol_version_){0}
    , decltype(_impl_.payload_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}
  };
  _impl_.trace_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.trace_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.sender_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.sender_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.signature_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.signature_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.auth_token_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.auth_token_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  clear_has_payload();
}

BusPacket::~BusPacket() {
  // @@protoc_insertion_point(destructor:cordum.agent.v1.BusPacket)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void BusPacket::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.trace_id_.Destroy();
  _impl_.sender_id_.Destroy();
  _impl_.signature_.Destroy();
  _impl_.auth_token_.Destroy();
  if (this != internal_default_instance()) delete _impl_.created_at_;
  if (has_payload()) {
    clear_payload();
  }
}

void BusPacket::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void BusPacket::clear_payload() {
// @@protoc_insertion_point(one_of_clear_start:cordum.agent.v1.BusPacket)
  switch (payload_case()) {
    case kJobRequest: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.payload_.job_request_;
      }
      break;
    }
    case kJobResult: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.payload_.job_result_;
      }
      break;
    }
    case kHeartbeat: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.payload_.heartbeat_;
      }
      break;
    }
    case kAlert: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.payload_.alert_;
      }
      break;
    }
    case kJobProgress: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.payload_.job_progress_;
      }
      break;
    }
    case kJobCancel: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.payload_.job_cancel_;
      }
      break;
    }
    case kHandshake: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.payload_.handshake_;
      }
      break;
    }
    case kWorkerHandshakeChallengeRequest: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.payload_.worker_handshake_challenge_request_;
      }
      break;
    }
    case kWorkerHandshakeChallenge: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.payload_.worker_handshake_challenge_;
      }
      break;
    }
    case kWorkerHandshakeAuthenticate: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.payload_.worker_handshake_authenticate_;
      }
      break;
    }
    case kWorkerHandshakeResult: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.payload_.worker_handshake_result_;
      }
      break;
    }
    case PAYLOAD_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = PAYLOAD_NOT_SET;
}


void BusPacket::Clear() {
// @@protoc_insertion_point(message_clear_start:cordum.agent.v1.BusPacket)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.trace_id_.ClearToEmpty();
  _impl_.sender_id_.ClearToEmpty();
  _impl_.signature_.ClearToEmpty();
  _impl_.auth_token_.ClearToEmpty();
  if (GetArenaForAllocation() == nullptr && _impl_.created_at_ != nullptr) {
    delete _impl_.created_at_;
  }
  _impl_.created_at_ = nullptr;
  _impl_.protocol_version_ = 0;
  clear_payload();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* BusPacket::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string trace_id = 1 [json_name = "traceId"];
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_trace_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "cordum.agent.v1.BusPacket.trace_id"));
        } else
          goto handle_unusual;
        continue;
      // string sender_id = 2 [json_name = "senderId"];
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_sender_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "cordum.agent.v1.BusPacket.sender_id"));
        } else
          goto handle_unusual;
        continue;
      // .google.protobuf.Timestamp created_at = 3 [json_name = "createdAt"];
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_created_at(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 protocol_version = 4 [json_name = "protocolVersion"];
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.protocol_version_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .cordum.agent.v1.JobRequest job_request = 10 [json_name = "jobRequest"];
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 82)) {
          ptr = ctx->ParseMessage(_internal_mutable_job_request(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .cordum.agent.v1.JobResult job_result = 11 [json_name = "jobResult"];
      case 11:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 90)) {
          ptr = ctx->ParseMessage(_internal_mutable_job_result(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .cordum.agent.v1.Heartbeat heartbeat = 12 [json_name = "heartbeat"];
      case 12:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 98)) {
          ptr = ctx->ParseMessage(_internal_mutable_heartbeat(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .cordum.agent.v1.SystemAlert alert = 13 [json_name = "alert"];
      case 13:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 106)) {
          ptr = ctx->ParseMessage(_internal_mutable_alert(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bytes signature = 14 [json_name = "signature"];
      case 14:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 114)) {
          auto str = _internal_mutable_signature();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .cordum.agent.v1.JobProgress job_progress = 15 [json_name = "jobProgress"];
      case 15:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 122)) {
          ptr = ctx->ParseMessage(_internal_mutable_job_progress(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .cordum.agent.v1.JobCancel job_cancel = 16 [json_name = "jobCancel"];
      case 16:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 130)) {
          ptr = ctx->ParseMessage(_internal_mutable_job_cancel(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .cordum.agent.v1.Handshake handshake = 17 [json_name = "handshake"];
      case 17:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 138)) {
          ptr = ctx->ParseMessage(_internal_mutable_handshake(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string auth_token = 18 [json_name = "authToken"];
      case 18:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 146)) {
          auto str = _internal_mutable_auth_token();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "cordum.agent.v1.BusPacket.auth_token"));
        } else
          goto handle_unusual;
        continue;
      // .cordum.agent.v1.WorkerHandshakeChallengeRequest worker_handshake_challenge_request = 19 [json_name = "workerHandshakeChallengeRequest"];
      case 19:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 154)) {
          ptr = ctx->ParseMessage(_internal_mutable_worker_handshake_challenge_request(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .cordum.agent.v1.WorkerHandshakeChallenge worker_handshake_challenge = 20 [json_name = "workerHandshakeChallenge"];
      case 20:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 162)) {
          ptr = ctx->ParseMessage(_internal_mutable_worker_handshake_challenge(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .cordum.agent.v1.WorkerHandshakeAuthenticate worker_handshake_authenticate = 21 [json_name = "workerHandshakeAuthenticate"];
      case 21:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 170)) {
          ptr = ctx->ParseMessage(_internal_mutable_worker_handshake_authenticate(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .cordum.agent.v1.WorkerHandshakeResult worker_handshake_result = 22 [json_name = "workerHandshakeResult"];
      case 22:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 178)) {
          ptr = ctx->ParseMessage(_internal_mutable_worker_handshake_result(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* BusPacket::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:cordum.agent.v1.BusPacket)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string trace_id = 1 [json_name = "traceId"];
  if (!this->_internal_trace_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_trace_id().data(), static_cast<int>(this->_internal_trace_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "cordum.agent.v1.BusPacket.trace_id");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_trace_id(), target);
  }

  // string sender_id = 2 [json_name = "senderId"];
  if (!this->_internal_sender_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_sender_id().data(), static_cast<int>(this->_internal_sender_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "cordum.agent.v1.BusPacket.sender_id");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_sender_id(), target);
  }

  // .google.protobuf.Timestamp created_at = 3 [json_name = "createdAt"];
  if (this->_internal_has_created_at()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, _Internal::created_at(this),
        _Internal::created_at(this).GetCachedSize(), target, stream);
  }

  // int32 protocol_version = 4 [json_name = "protocolVersion"];
  if (this->_internal_protocol_version() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(4, this->_internal_protocol_version(), target);
  }

  // .cordum.agent.v1.JobRequest job_request = 10 [json_name = "jobRequest"];
  if (_internal_has_job_request()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(10, _Internal::job_request(this),
        _Internal::job_request(this).GetCachedSize(), target, stream);
  }

  // .cordum.agent.v1.JobResult job_result = 11 [json_name = "jobResult"];
  if (_internal_has_job_result()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(11, _Internal::job_result(this),
        _Internal::job_result(this).GetCachedSize(), target, stream);
  }

  // .cordum.agent.v1.Heartbeat heartbeat = 12 [json_name = "heartbeat"];
  if (_internal_has_heartbeat()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(12, _Internal::heartbeat(this),
        _Internal::heartbeat(this).GetCachedSize(), target, stream);
  }

  // .cordum.agent.v1.SystemAlert alert = 13 [json_name = "alert"];
  if (_internal_has_alert()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(13, _Internal::alert(this),
        _Internal::alert(this).GetCachedSize(), target, stream);
  }

  // bytes signature = 14 [json_name = "signature"];
  if (!this->_internal_signature().empty()) {
    target = stream->WriteBytesMaybeAliased(
        14, this->_internal_signature(), target);
  }

  // .cordum.agent.v1.JobProgress job_progress = 15 [json_name = "jobProgress"];
  if (_internal_has_job_progress()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(15, _Internal::job_progress(this),
        _Internal::job_progress(this).GetCachedSize(), target, stream);
  }

  // .cordum.agent.v1.JobCancel job_cancel = 16 [json_name = "jobCancel"];
  if (_internal_has_job_cancel()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(16, _Internal::job_cancel(this),
        _Internal::job_cancel(this).GetCachedSize(), target, stream);
  }

  // .cordum.agent.v1.Handshake handshake = 17 [json_name = "handshake"];
  if (_internal_has_handshake()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(17, _Internal::handshake(this),
        _Internal::handshake(this).GetCachedSize(), target, stream);
  }

  // string auth_token = 18 [json_name = "authToken"];
  if (!this->_internal_auth_token().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_auth_token().data(), static_cast<int>(this->_internal_auth_token().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "cordum.agent.v1.BusPacket.auth_token");
    target = stream->WriteStringMaybeAliased(
        18, this->_internal_auth_token(), target);
  }

  // .cordum.agent.v1.WorkerHandshakeChallengeRequest worker_handshake_challenge_request = 19 [json_name = "workerHandshakeChallengeRequest"];
  if (_internal_has_worker_handshake_challenge_request()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(19, _Internal::worker_handshake_challenge_request(this),
        _Internal::worker_handshake_challenge_request(this).GetCachedSize(), target, stream);
  }

  // .cordum.agent.v1.WorkerHandshakeChallenge worker_handshake_challenge = 20 [json_name = "workerHandshakeChallenge"];
  if (_internal_has_worker_handshake_challenge()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(20, _Internal::worker_handshake_challenge(this),
        _Internal::worker_handshake_challenge(this).GetCachedSize(), target, stream);
  }

  // .cordum.agent.v1.WorkerHandshakeAuthenticate worker_handshake_authenticate = 21 [json_name = "workerHandshakeAuthenticate"];
  if (_internal_has_worker_handshake_authenticate()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(21, _Internal::worker_handshake_authenticate(this),
        _Internal::worker_handshake_authenticate(this).GetCachedSize(), target, stream);
  }

  // .cordum.agent.v1.WorkerHandshakeResult worker_handshake_result = 22 [json_name = "workerHandshakeResult"];
  if (_internal_has_worker_handshake_result()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(22, _Internal::worker_handshake_result(this),
        _Internal::worker_handshake_result(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cordum.agent.v1.BusPacket)
  return target;
}

size_t BusPacket::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:cordum.agent.v1.BusPacket)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string trace_id = 1 [json_name = "traceId"];
  if (!this->_internal_trace_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_trace_id());
  }

  // string sender_id = 2 [json_name = "senderId"];
  if (!this->_internal_sender_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_sender_id());
  }

  // bytes signature = 14 [json_name = "signature"];
  if (!this->_internal_signature().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_signature());
  }

  // string auth_token = 18 [json_name = "authToken"];
  if (!this->_internal_auth_token().empty()) {
    total_size += 2 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_auth_token());
  }

  // .google.protobuf.Timestamp created_at = 3 [json_name = "createdAt"];
  if (this->_internal_has_created_at()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.created_at_);
  }

  // int32 protocol_version = 4 [json_name = "protocolVersion"];
  if (this->_internal_protocol_version() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_protocol_version());
  }

  switch (payload_case()) {
    // .cordum.agent.v1.JobRequest job_request = 10 [json_name = "jobRequest"];
    case kJobRequest: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.payload_.job_request_);
      break;
    }
    // .cordum.agent.v1.JobResult job_result = 11 [json_name = "jobResult"];
    case kJobResult: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.payload_.job_result_);
      break;
    }
    // .cordum.agent.v1.Heartbeat heartbeat = 12 [json_name = "heartbeat"];
    case kHeartbeat: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.payload_.heartbeat_);
      break;
    }
    // .cordum.agent.v1.SystemAlert alert = 13 [json_name = "alert"];
    case kAlert: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.payload_.alert_);
      break;
    }
    // .cordum.agent.v1.JobProgress job_progress = 15 [json_name = "jobProgress"];
    case kJobProgress: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.payload_.job_progress_);
      break;
    }
    // .cordum.agent.v1.JobCancel job_cancel = 16 [json_name = "jobCancel"];
    case kJobCancel: {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.payload_.job_cancel_);
      break;
    }
    // .cordum.agent.v1.Handshake handshake = 17 [json_name = "handshake"];
    case kHandshake: {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.payload_.handshake_);
      break;
    }
    // .cordum.agent.v1.WorkerHandshakeChallengeRequest worker_handshake_challenge_request = 19 [json_name = "workerHandshakeChallengeRequest"];
    case kWorkerHandshakeChallengeRequest: {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.payload_.worker_handshake_challenge_request_);
      break;
    }
    // .cordum.agent.v1.WorkerHandshakeChallenge worker_handshake_challenge = 20 [json_name = "workerHandshakeChallenge"];
    case kWorkerHandshakeChallenge: {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.payload_.worker_handshake_challenge_);
      break;
    }
    // .cordum.agent.v1.WorkerHandshakeAuthenticate worker_handshake_authenticate = 21 [json_name = "workerHandshakeAuthenticate"];
    case kWorkerHandshakeAuthenticate: {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.payload_.worker_handshake_authenticate_);
      break;
    }
    // .cordum.agent.v1.WorkerHandshakeResult worker_handshake_result = 22 [json_name = "workerHandshakeResult"];
    case kWorkerHandshakeResult: {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.payload_.worker_handshake_result_);
      break;
    }
    case PAYLOAD_NOT_SET: {
      break;
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData BusPacket::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    BusPacket::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*BusPacket::GetClassData() const { return &_class_data_; }


void BusPacket::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<BusPacket*>(&to_msg);
  auto& from = static_cast<const BusPacket&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:cordum.agent.v1.BusPacket)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_trace_id().empty()) {
    _this->_internal_set_trace_id(from._internal_trace_id());
  }
  if (!from._internal_sender_id().empty()) {
    _this->_internal_set_sender_id(from._internal_sender_id());
  }
  if (!from._internal_signature().empty()) {
    _this->_internal_set_signature(from._internal_signature());
  }
  if (!from._internal_auth_token().empty()) {
    _this->_internal_set_auth_token(from._internal_auth_token());
  }
  if (from._internal_has_created_at()) {
    _this->_internal_mutable_created_at()->::PROTOBUF_NAMESPACE_ID::Timestamp::MergeFrom(
        from._internal_created_at());
  }
  if (from._internal_protocol_version() != 0) {
    _this->_internal_set_protocol_version(from._internal_protocol_version());
  }
  switch (from.payload_case()) {
    case kJobRequest: {
      _this->_internal_mutable_job_request()->::cordum::agent::v1::JobRequest::MergeFrom(
          from._internal_job_request());
      break;
    }
    case kJobResult: {
      _this->_internal_mutable_job_result()->::cordum::agent::v1::JobResult::MergeFrom(
          from._internal_job_result());
      break;
    }
    case kHeartbeat: {
      _this->_internal_mutable_heartbeat()->::cordum::agent::v1::Heartbeat::MergeFrom(
          from._internal_heartbeat());
      break;
    }
    case kAlert: {
      _this->_internal_mutable_alert()->::cordum::agent::v1::SystemAlert::MergeFrom(
          from._internal_alert());
      break;
    }
    case kJobProgress: {
      _this->_internal_mutable_job_progress()->::cordum::agent::v1::JobProgress::MergeFrom(
          from._internal_job_progress());
      break;
    }
    case kJobCancel: {
      _this->_internal_mutable_job_cancel()->::cordum::agent::v1::JobCancel::MergeFrom(
          from._internal_job_cancel());
      break;
    }
    case kHandshake: {
      _this->_internal_mutable_handshake()->::cordum::agent::v1::Handshake::MergeFrom(
          from._internal_handshake());
      break;
    }
    case kWorkerHandshakeChallengeRequest: {
      _this->_internal_mutable_worker_handshake_challenge_request()->::cordum::agent::v1::WorkerHandshakeChallengeRequest::MergeFrom(
          from._internal_worker_handshake_challenge_request());
      break;
    }
    case kWorkerHandshakeChallenge: {
      _this->_internal_mutable_worker_handshake_challenge()->::cordum::agent::v1::WorkerHandshakeChallenge::MergeFrom(
          from._internal_worker_handshake_challenge());
      break;
    }
    case kWorkerHandshakeAuthenticate: {
      _this->_internal_mutable_worker_handshake_authenticate()->::cordum::agent::v1::WorkerHandshakeAuthenticate::MergeFrom(
          from._internal_worker_handshake_authenticate());
      break;
    }
    case kWorkerHandshakeResult: {
      _this->_internal_mutable_worker_handshake_result()->::cordum::agent::v1::WorkerHandshakeResult::MergeFrom(
          from._internal_worker_handshake_result());
      break;
    }
    case PAYLOAD_NOT_SET: {
      break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void BusPacket::CopyFrom(const BusPacket& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:cordum.agent.v1.BusPacket)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BusPacket::IsInitialized() const {
  return true;
}

void BusPacket::InternalSwap(BusPacket* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.trace_id_, lhs_arena,
      &other->_impl_.trace_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.sender_id_, lhs_arena,
      &other->_impl_.sender_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.signature_, lhs_arena,
      &other->_impl_.signature_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.auth_token_, lhs_arena,
      &other->_impl_.auth_token_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(BusPacket, _impl_.protocol_version_)
      + sizeof(BusPacket::_impl_.protocol_version_)
      - PROTOBUF_FIELD_OFFSET(BusPacket, _impl_.created_at_)>(
          reinterpret_cast<char*>(&_impl_.created_at_),
          reinterpret_cast<char*>(&other->_impl_.created_at_));
  swap(_impl_.payload_, other->_impl_.payload_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::PROTOBUF_NAMESPACE_ID::Metadata BusPacket::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_cordum_2fagent_2fv1_2fbuspacket_2eproto_getter, &descriptor_table_cordum_2fagent_2fv1_2fbuspacket_2eproto_once,
      file_level_metadata_cordum_2fagent_2fv1_2fbuspacket_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace agent
}  // namespace cordum
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::cordum::agent::v1::BusPacket*
Arena::CreateMaybeMessage< ::cordum::agent::v1::BusPacket >(Arena* arena) {
  return Arena::CreateMessageInternal< ::cordum::agent::v1::BusPacket >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
